
/* Phase 85 — conservative continuous-effect layer foundation. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGContinuousEffects=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const VERSION='phase85-continuous-effects-1';const SAFE_TRAITS=['deathtouch','trample','vigilance','firstStrike','doubleStrike','flying','reach','menace','lifelink','indestructible','phasing'];
const clone=x=>JSON.parse(JSON.stringify(x));const ctrl=o=>Number(o?.controllerId??o?.owner??0)||0;const lc=v=>String(v||'').trim().toLowerCase();
function bi(v,fallback=0n){try{return BigInt(String(v??fallback).replace(/,/g,''))}catch{return fallback}}
function normalizeEffect(e={}){let kind=['pt-mod','keyword-grant','manual'].includes(String(e.kind))?String(e.kind):'manual',scope=e.scope&&typeof e.scope==='object'?clone(e.scope):{};return{id:String(e.id||e.effectId||''),kind,layer:String(e.layer|| (kind==='keyword-grant'?'6':kind==='pt-mod'?'7c':'manual')),scope,powerDelta:bi(e.powerDelta).toString(),toughnessDelta:bi(e.toughnessDelta).toString(),traits:Array.isArray(e.traits)?e.traits.filter(x=>SAFE_TRAITS.includes(String(x))):[],duration:String(e.duration||'source'),sourceObjectId:e.sourceObjectId?String(e.sourceObjectId):null,sourceController:Number(e.sourceController||0)||0,sourceCopies:bi(e.sourceCopies,1n).toString(),timestamp:Number(e.timestamp||0),oracleText:String(e.oracleText||''),automation:e.automation==='exact'?'exact':'manual'} }
function staticEffects(state={}){let out=[];for(const source of state.battle||[]){if(globalThis.MTGPhasing?.isPhasedOut(source))continue;for(const raw of source.continuousEffects||[]){let e=normalizeEffect({...raw,sourceObjectId:source.id,sourceController:ctrl(source),sourceCopies:String(source.q??'1'),timestamp:Number(raw.timestamp??source.order??0)});e.id='static:'+String(source.id)+':'+String(raw.id||out.length);out.push(e)}}return out}
function temporaryEffects(state={}){return (Array.isArray(state.continuousEffects)?state.continuousEffects:[]).map(normalizeEffect)}
function active(state={}){return [...staticEffects(state),...temporaryEffects(state)].sort((a,b)=>{let la=a.layer==='6'?6:a.layer==='7c'?73:999,lb=b.layer==='6'?6:b.layer==='7c'?73:999;return la-lb||a.timestamp-b.timestamp||a.id.localeCompare(b.id)})}
function hasType(o,t){let want=lc(t);if(!want)return true;return new RegExp('(?:^|\\W)'+want+'(?:$|\\W)','i').test(lc(o?.typeLine||o?.type||''))}
function hasSubtype(o,t){let want=lc(t);return !want||(o?.sub||o?.subtypes||[]).some(x=>lc(x)===want)}
function applies(e={},target={}){let s=e.scope||{},sc=Number(e.sourceController||0),tc=ctrl(target);if(s.objectId&&String(s.objectId)!==String(target.id))return false;if(s.controller==='you'&&sc&&sc!==tc)return false;if(s.controller==='opponent'&&sc&&sc===tc)return false;if(s.type&&!hasType(target,s.type))return false;if(s.subtype&&!hasSubtype(target,s.subtype))return false;if(s.token===true&&!target.token)return false;if(s.token===false&&target.token)return false;if(s.another&&e.sourceObjectId&&String(e.sourceObjectId)===String(target.id))return false;return true}
function baseStats(o={}){let m=o.combatMeta||{},p=m.power??o.power,t=m.toughness??o.toughness;return{power:p==null||String(p).trim()===''?null:bi(p).toString(),toughness:t==null||String(t).trim()===''?null:bi(t).toString(),traits:{...(m.traits||{})}}}
function derived(state={},o={}){let b=baseStats(o),power=b.power==null?null:bi(b.power),toughness=b.toughness==null?null:bi(b.toughness),traits={...b.traits},applied=[],review=[];for(const e of active(state)){if(!applies(e,o))continue;if(e.automation!=='exact'||!['6','7c'].includes(e.layer)){review.push(e);continue}if(e.kind==='keyword-grant'){for(const k of e.traits)traits[k]=true;applied.push(e)}else if(e.kind==='pt-mod'){let copies=bi(e.sourceCopies,1n);if(copies<1n)copies=1n;if(power!==null)power+=bi(e.powerDelta)*copies;if(toughness!==null)toughness+=bi(e.toughnessDelta)*copies;applied.push(e)}else review.push(e)}return{power:power===null?null:power.toString(),toughness:toughness===null?null:toughness.toString(),traits,damageMarked:String(o.damageMarked??'0'),deathtouchMarked:!!o.deathtouchMarked,appliedEffects:applied.map(x=>x.id),reviewRequired:review.length>0,reviewEffects:review.map(x=>x.id)}}
function expiresAtCleanup(e={}){let d=String(e.duration||'').toLowerCase();return d==='until-end-of-turn'||d==='this-turn'}
function expireTemporary(state={}){let before=Array.isArray(state.continuousEffects)?state.continuousEffects.length:0;state.continuousEffects=(state.continuousEffects||[]).filter(e=>!expiresAtCleanup(e));return before-state.continuousEffects.length}
function summary(state={}){let effects=active(state);return{count:effects.length,temporary:temporaryEffects(state).length,static:staticEffects(state).length,review:effects.filter(e=>e.automation!=='exact'||!['6','7c'].includes(e.layer)).length}}
function localQA(){let checks=[],q=(n,v)=>checks.push([n,!!v]),anthem={id:'lord',owner:1,controllerId:1,typeLine:'Creature — Knight',continuousEffects:[{id:'anthem',kind:'pt-mod',layer:'7c',scope:{controller:'you',type:'Creature',another:true},powerDelta:'1',toughnessDelta:'1',automation:'exact'}]},ally={id:'ally',owner:1,controllerId:1,typeLine:'Creature — Knight',combatMeta:{power:'2',toughness:'2',traits:{}}},enemy={id:'enemy',owner:2,controllerId:2,typeLine:'Creature — Goblin',combatMeta:{power:'2',toughness:'2',traits:{}}},st={battle:[anthem,ally,enemy],continuousEffects:[{id:'temp',kind:'keyword-grant',layer:'6',scope:{controller:'you',type:'Creature'},traits:['flying'],duration:'until-end-of-turn',sourceController:1,timestamp:5,automation:'exact'}]};let a=derived(st,ally),e=derived(st,enemy),s=derived(st,anthem);q('controller-scoped anthem modifies ally',a.power==='3'&&a.toughness==='3');q('anthem excludes source when another',s.power===null&&s.toughness===null);q('opponent creature is unaffected',e.power==='2'&&e.toughness==='2');q('temporary keyword grant is derived',a.traits.flying===true);let cohortState={battle:[{...anthem,q:'3'},ally],continuousEffects:[]};q('continuous source cohort counts each copy',derived(cohortState,cohortState.battle[1]).power==='5');q('cleanup expiration identifies EOT effect',expireTemporary(st)===1&&st.continuousEffects.length===0);q('safe layers do not require review',a.reviewRequired===false);q('version identifies Phase 85',VERSION.includes('phase85'));return{ok:checks.every(x=>x[1]),checks}}
return{VERSION,SAFE_TRAITS,bi,normalizeEffect,staticEffects,temporaryEffects,active,applies,baseStats,derived,expiresAtCleanup,expireTemporary,summary,localQA};
});
