
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGMatchRecords=api})(typeof self!=='undefined'?self:this,function(){
'use strict';
const VERSION='phase10-match-records-1';
const clone=x=>JSON.parse(JSON.stringify(x));
function fallenOrder(state){return (state?.events||[]).filter(e=>e.type==='PLAYER_FALLEN').map(e=>({playerId:Number(e.payload?.playerId??e.actorId),seq:Number(e.seq||0),at:e.at,reason:e.payload?.reason||'unknown'}));}
function placements(state,players=[]){const ids=players.map(p=>Number(p.id));const fallen=fallenOrder(state);const alive=ids.filter(id=>!state?.fallen?.[id]);const rank={};if(alive.length===1)rank[alive[0]]=1;fallen.slice().reverse().forEach((x,i)=>{if(rank[x.playerId]==null)rank[x.playerId]=(alive.length===1?2:1)+i});ids.forEach(id=>{if(rank[id]==null)rank[id]=ids.length});return ids.map(id=>({playerId:id,placement:rank[id],reason:state?.fallen?.[id]?.reason||null})).sort((a,b)=>a.placement-b.placement||a.playerId-b.playerId);}
function canFinalize(state,players=[]){if(state?.matchFinalization)return false;const alive=players.filter(p=>!state?.fallen?.[p.id]);return players.length>=2&&alive.length===1;}
function buildPayload(state,players=[],room=null){const alive=players.filter(p=>!state?.fallen?.[p.id]);if(alive.length!==1)return null;return{matchId:state.meta?.matchId||null,winnerId:alive[0].id,placements:placements(state,players),turnCount:Number(state.turn||0),room:room||null,playerCount:players.length,finalizedAt:Date.now()};}
function finalize(state,players=[],room=null,actorId=null,engine){if(!canFinalize(state,players))return null;const payload=buildPayload(state,players,room);if(!payload)return null;if(engine?.dispatch)return engine.dispatch(state,'MATCH_FINALIZED',payload,actorId,{source:'match-finalizer'});state.matchFinalization=clone(payload);return payload;}
function localRecord(state,players=[],localPlayerId,deck){const f=state?.matchFinalization;if(!f)return null;const place=(f.placements||[]).find(x=>Number(x.playerId)===Number(localPlayerId));const result=Number(f.winnerId)===Number(localPlayerId)?'win':'loss';return{id:f.matchId||state.meta?.matchId,battleName:state.meta?.battleName||null,localPlayerId:Number(localPlayerId),date:new Date(f.finalizedAt||Date.now()).toISOString(),room:f.room||null,players:players.map(p=>({id:p.id,name:p.name||('Player '+p.id),commander:p.commander||null})),winnerId:f.winnerId,placement:place?.placement||null,result,turnCount:f.turnCount||state.turn||0,durationMs:Math.max(0,(f.finalizedAt||Date.now())-(state.meta?.startedAt||f.finalizedAt||Date.now())),deckId:deck?.id||null,deckVersionId:deck?.currentVersionId||null,commander:deck?.commander||players.find(p=>Number(p.id)===Number(localPlayerId))?.commander||null,finalState:{life:clone(state.life||{}),poison:clone(state.poison||{}),cmd:clone(state.cmd||{}),fallen:clone(state.fallen||{})},eliminations:fallenOrder(state),timeline:(state.events||[]).map(e=>({id:e.id,seq:e.seq,type:e.type,actorId:e.actorId,payload:clone(e.payload||{}),at:e.at})),awards:[]};}
return{VERSION,fallenOrder,placements,canFinalize,buildPayload,finalize,localRecord};
});

