
/* Phase 95 — generalized Last Known Information, pre/post event context, atomic batch identity, and zone-incarnation tracking. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGLKI=api})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const VERSION='phase95-generalized-lki-lookback-1';
const OBSERVATION=Object.freeze({POST_EVENT:'POST_EVENT',PRE_EVENT_LOOKBACK:'PRE_EVENT_LOOKBACK',CUSTOM_LKI:'CUSTOM_LKI'});
const clone=x=>JSON.parse(JSON.stringify(x));
const lc=v=>String(v||'').toLowerCase();
function stableId(o){return String(o?.stableObjectId||o?.id||'')}
function initialIncarnation(o){let id=stableId(o);return String(o?.incarnationId||o?.zoneObjectId||(id?id+'@origin':''))}
function normalizeIdentity(o){if(!o||typeof o!=='object')return o;let id=String(o.id||o.stableObjectId||'');if(!id)return o;o.stableObjectId=String(o.stableObjectId||id);o.incarnationId=initialIncarnation(o);o.zoneChangeId=String(o.zoneChangeId||'origin:'+o.stableObjectId);return o}
function nextIncarnation(o,event,toZone){normalizeIdentity(o);let prior=String(o.incarnationId||initialIncarnation(o)),sid=stableId(o),seq=Number(event?.seq||0),eid=String(event?.id||('evt'+seq));o.previousIncarnationId=prior;o.incarnationId=sid+'@'+seq;o.zoneChangeId='zc:'+eid+':'+sid;o.zoneEnteredAtSeq=seq;o.zone=String(toZone||'').toLowerCase()||null;return o}
function allZoneRecords(state={}){let out=[];for(const o of state.battle||[])out.push({zone:'battlefield',object:o});for(const [zone,list] of Object.entries(state.zones||{}))for(const o of list||[])out.push({zone:String(zone).toLowerCase(),object:o});return out}
function findRecord(state,id){id=String(id||'');if(!id)return null;return allZoneRecords(state).find(r=>String(r.object?.id)===id||String(r.object?.stableObjectId)===id||String(r.object?.incarnationId)===id)||null}
function derivedView(state,o){let base=clone(o||{}),d=null;try{if(root.MTGLayerEngine?.derived)d=root.MTGLayerEngine.derived(state,o);else if(root.MTGContinuousEffects?.derived)d=root.MTGContinuousEffects.derived(state,o)}catch{}if(d&&typeof d==='object'){for(const k of ['name','controllerId','typeLine','types','subtypes','colors','traits','power','toughness','damageMarked','deathtouchMarked','reviewRequired','reviewEffects'])if(d[k]!==undefined)base[k]=clone(d[k]);if(Array.isArray(d.subtypes))base.sub=d.subtypes.slice()}normalizeIdentity(base);return base}
function objectSnapshot(state,record){if(!record?.object)return null;let view=record.zone==='battlefield'?derivedView(state,record.object):clone(record.object);normalizeIdentity(view);return{objectId:String(view.id||view.stableObjectId||''),stableObjectId:String(view.stableObjectId||view.id||''),incarnationId:String(view.incarnationId||''),zoneChangeId:String(view.zoneChangeId||''),zone:String(record.zone||''),view}}
function addId(set,v){if(v!==null&&v!==undefined&&String(v)!=='')set.add(String(v))}
function touchedObjectIds(state={},type='',payload={}){let ids=new Set(),p=payload||{};for(const k of ['objectId','sourceObjectId','targetObjectId','blockerObjectId','attackerObjectId','sourceId'])addId(ids,p[k]);for(const x of p.objectIds||[])addId(ids,x);addId(ids,p.object?.id);addId(ids,p.cohort?.id);if(p.target?.kind==='object')addId(ids,p.target.objectId);for(const t of p.targets||[])if(t?.kind==='object')addId(ids,t.objectId);if(type==='STATE_BASED_ACTIONS_APPLIED'){for(const [src,tgt] of Object.entries(state.attachments?.links||{})){addId(ids,src);addId(ids,tgt)}}if(type==='COMBAT_DAMAGE_RESOLVED'||type==='COMBAT_DAMAGE_STEP_RESOLVED'){for(const a of state.combat?.damageAssignments||[]){addId(ids,a.sourceObjectId);if(a.target?.kind==='object')addId(ids,a.target.objectId)}}if(type==='TURN_ADVANCED')for(const o of state.battle||[])addId(ids,o.id);if(type==='PERMANENT_PHASE_STATUS_SET')addId(ids,p.objectId);return ids}
function needsLife(type){return ['COMBAT_DAMAGE_RESOLVED','COMBAT_DAMAGE_STEP_RESOLVED','LIFE_CHANGED','LIFE_CHANGED_EXACT','LIFE_LOST','DAMAGE_DEALT','COMMANDER_DAMAGE_DEALT'].includes(String(type||''))}
function needsLibrary(type,p={}){return String(type||'')==='TURN_ADVANCED'||(String(type||'')==='LIBRARY_COUNT_CHANGED'&&lc(p.reason)==='draw')}
function capture(state={},type='',payload={}){let ids=touchedObjectIds(state,type,payload),objects=[];for(const id of ids){let r=findRecord(state,id);if(r){let x=objectSnapshot(state,r);if(x)objects.push(x)}}let battle=objects.filter(x=>x.zone==='battlefield').map(x=>clone(x.view));let out={version:VERSION,stateSeq:Number(state?.meta?.seq||0),active:Number(state?.active||0)||null,phase:String(state?.phase||''),turn:Number(state?.turn||0)||0,objects,battle};if(needsLife(type))out.life=clone(state.life||{});if(needsLibrary(type,payload))out.libraryCounts=clone(state.libraryCounts||{});return out}
function atomicBatchId(event,meta={}){return String(meta.atomicBatchId||event?.payload?.atomicBatchId||event?.atomicBatchId||('batch:'+String(event?.id||event?.seq||Date.now())))}
function prepareEvent(state,event,meta={}){if(!event)return event;event.atomicBatchId=atomicBatchId(event,meta);event.phase95Context={version:VERSION,atomicBatchId:event.atomicBatchId,pre:capture(state,event.type,event.payload),post:null};return event}
function finalizeEvent(state,event){if(!event)return event;if(!event.phase95Context)prepareEvent(state,event,{});event.phase95Context.post=capture(state,event.type,event.payload);let pre=event.phase95Context.pre?.objects||[],post=event.phase95Context.post?.objects||[],postInc=new Set(post.map(x=>String(x.incarnationId||'')));event.phase95Context.lki=pre.filter(x=>!postInc.has(String(x.incarnationId||''))).map(clone);return event}
function preState(event,fallback={}){return event?.phase95Context?.pre||fallback||{}}
function postState(event,fallback={}){return event?.phase95Context?.post||fallback||{}}
function preObject(event,id){id=String(id||'');let x=(event?.phase95Context?.pre?.objects||[]).find(o=>String(o.objectId)===id||String(o.stableObjectId)===id||String(o.incarnationId)===id);return x?clone(x.view):null}
function postObject(event,id){id=String(id||'');let x=(event?.phase95Context?.post?.objects||[]).find(o=>String(o.objectId)===id||String(o.stableObjectId)===id||String(o.incarnationId)===id);return x?clone(x.view):null}
function lkiObject(event,id){id=String(id||'');let x=(event?.phase95Context?.lki||[]).find(o=>String(o.objectId)===id||String(o.stableObjectId)===id||String(o.incarnationId)===id);return x?clone(x.view):preObject(event,id)}
function localQA(engine){let c=[],q=(n,v)=>c.push([n,!!v]);if(!engine)return{ok:false,checks:[['engine supplied',false]]};let st=engine.normalizeState({life:{1:40,2:40},battle:[{id:'watch',name:'Watcher',owner:1,controllerId:1,typeLine:'Creature — Cleric',oracleText:'Whenever another creature dies, you gain 1 life.',combatMeta:{power:'1',toughness:'1',traits:{}},damageMarked:'1'},{id:'other',name:'Other',owner:2,controllerId:2,typeLine:'Creature — Elf',combatMeta:{power:'2',toughness:'2',traits:{}},damageMarked:'2'}],events:[],snapshots:[],feed:[]});let e=engine.dispatch(st,'STATE_BASED_ACTIONS_APPLIED',{objectIds:['watch','other']},1,{source:'qa',atomicBatchId:'qa-sba'});q('event stores one atomic SBA batch id',e.atomicBatchId==='qa-sba'&&e.phase95Context?.atomicBatchId==='qa-sba');q('simultaneous deaths retain both pre-event objects',e.phase95Context?.pre?.battle?.length===2);q('pre-event source characteristics survive as LKI',lkiObject(e,'watch')?.oracleText?.includes('another creature dies'));q('post-event battlefield no longer contains dead objects',!(e.phase95Context?.post?.battle||[]).some(o=>['watch','other'].includes(String(o.id))));let gy=(st.zones?.graveyard||[]).find(o=>o.id==='watch');q('SBA zone move advances semantic incarnation',!!gy?.previousIncarnationId&&gy.incarnationId!==gy.previousIncarnationId);let oldInc=gy?.incarnationId;let z=engine.dispatch(st,'OBJECT_ZONE_CHANGED',{objectId:'watch',toZone:'battlefield'},1,{source:'qa'});let cur=st.battle.find(o=>o.id==='watch');q('later zone move creates another incarnation without changing stable UI id',cur?.id==='watch'&&cur?.incarnationId!==oldInc&&cur?.stableObjectId==='watch');q('zone event exposes old incarnation through look-back',preObject(z,'watch')?.incarnationId===oldInc);let copy=engine.normalizeState(JSON.parse(JSON.stringify(st))),last=copy.events?.at(-1);q('serialized/reconnected event retains Phase 95 context',last?.phase95Context?.version===VERSION&&last?.phase95Context?.pre?.objects?.length>=1);q('version identifies Phase 95',VERSION.includes('phase95'));return{ok:c.every(x=>x[1]),checks:c}}
return{VERSION,OBSERVATION,normalizeIdentity,nextIncarnation,findRecord,touchedObjectIds,capture,prepareEvent,finalizeEvent,preState,postState,preObject,postObject,lkiObject,localQA};
});
