
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MTGCombatSteps=api})(typeof window!=='undefined'?window:globalThis,function(){
 const VERSION='phase94-combat-step-identity-1';
 const VALID_STEPS=['first','normal','complete'];
 function traits(o,state=null){return state&&typeof MTGContinuousEffects!=='undefined'?MTGContinuousEffects.derived(state,o).traits:(o?.combatMeta?.traits||{})}
 function has(o,k,state=null){return !!traits(o,state)[k]}
 function participantIds(state){const s=new Set();for(const a of state.combat?.attackers||[])s.add(String(a.objectId));for(const b of state.combat?.blockers||[])s.add(String(b.blockerObjectId));return [...s]}
 function participantObjects(state){const ids=new Set(participantIds(state));return (state.battle||[]).filter(o=>ids.has(String(o.id)))}
 function needsFirstStep(state){return participantObjects(state).some(o=>has(o,'firstStrike',state)||has(o,'doubleStrike',state))}
 function eligibleObject(o,step,state=null){if(!o)return false;if(state&&typeof MTGAdvancedCombatDamage!=='undefined')return MTGAdvancedCombatDamage.stepEligible(state,o,step);const first=has(o,'firstStrike',state),dbl=has(o,'doubleStrike',state);if(step==='first')return first||dbl;if(step==='normal')return dbl||!first;return false}
 function eligibleSourceIds(state,step){return participantObjects(state).filter(o=>eligibleObject(o,step,state)).map(o=>String(o.id))}
 function normalize(state={}){state.combatSteps??={active:false,current:'idle',firstStepRequired:false,completed:[],resolvedAssignmentIds:[],sequence:0,firstSnapshot:{captured:false,sources:{}}};let x=state.combatSteps;x.active=!!x.active;x.current=String(x.current||'idle');x.firstStepRequired=!!x.firstStepRequired;x.completed=Array.isArray(x.completed)?x.completed.filter(v=>v==='first'||v==='normal'):[];x.resolvedAssignmentIds=Array.isArray(x.resolvedAssignmentIds)?x.resolvedAssignmentIds.map(String):[];x.sequence=Number.isInteger(Number(x.sequence))?Number(x.sequence):0;x.firstSnapshot=typeof MTGAdvancedCombatDamage!=='undefined'?MTGAdvancedCombatDamage.normalizeSnapshot(x.firstSnapshot):x.firstSnapshot||{captured:false,sources:{}};return x}
 function startIntent(state){return{type:'COMBAT_DAMAGE_SEQUENCE_STARTED',payload:{firstStepRequired:needsFirstStep(state)}}}
 function current(state){return normalize(state).current}
 function assignmentAllowed(state,sourceObjectId,step=current(state)){const x=normalize(state),o=(state.battle||[]).find(v=>String(v.id)===String(sourceObjectId));if(!x.active)return{ok:true,reason:'legacy-unscheduled'};if(step!==x.current)return{ok:false,reason:'wrong-step'};if(!eligibleObject(o,step,state))return{ok:false,reason:'source-not-eligible'};return{ok:true,reason:'eligible'}}
 function nextStep(state){const x=normalize(state);if(!x.active)return null;if(x.current==='first')return'normal';if(x.current==='normal')return'complete';return null}
 function summary(state){const x=normalize(state);return{...x,eligibleSourceIds:x.active&&VALID_STEPS.includes(x.current)?eligibleSourceIds(state,x.current):[]}}
 function localQA(engine){
  let st=engine.normalizeState({life:{1:40,2:40},battle:[{id:'fs',name:'First',owner:1,controllerId:1,combatMeta:{power:'2',toughness:'2',traits:{firstStrike:true}}},{id:'ds',name:'Double',owner:1,controllerId:1,combatMeta:{power:'2',toughness:'2',traits:{doubleStrike:true}}},{id:'n',name:'Normal',owner:2,controllerId:2,combatMeta:{power:'3',toughness:'3',traits:{}}}],combat:{active:true,attackers:[{objectId:'fs',defender:{kind:'player',playerId:2}},{objectId:'ds',defender:{kind:'player',playerId:2}}],blockers:[{blockerObjectId:'n',attackerObjectId:'ds'}]},events:[],snapshots:[],feed:[]});
  const emit=(type,payload={},actor=1)=>engine.reduce(st,engine.makeEvent(st,type,payload,actor,{source:'qa'}));
  const checks=[];emit('COMBAT_DAMAGE_SEQUENCE_STARTED',{firstStepRequired:needsFirstStep(st)});checks.push(['first-strike step is scheduled when required',st.combatSteps.active&&st.combatSteps.current==='first']);checks.push(['first strike and double strike are first-step eligible',eligibleSourceIds(st,'first').sort().join(',')==='ds,fs']);checks.push(['ordinary blocker is not first-step eligible',!eligibleSourceIds(st,'first').includes('n')]);
  emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'f1',sourceObjectId:'fs',target:{kind:'player',playerId:2},amount:'2',flags:{step:'first'}});emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'d1',sourceObjectId:'ds',target:{kind:'object',objectId:'n'},amount:'2',flags:{step:'first'}});emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'bad',sourceObjectId:'n',target:{kind:'object',objectId:'ds'},amount:'3',flags:{step:'first'}},2);checks.push(['ineligible first-step assignment is rejected',!st.combat.damageAssignments.some(a=>a.assignmentId==='bad')]);
  emit('COMBAT_DAMAGE_STEP_RESOLVED',{step:'first'});checks.push(['first-step player damage resolves exactly once',String(st.life[2])==='38']);emit('COMBAT_DAMAGE_STEP_RESOLVED',{step:'first'});checks.push(['repeat first-step resolution is idempotent',String(st.life[2])==='38']);
  emit('COMBAT_DAMAGE_STEP_ADVANCED',{});checks.push(['sequence advances to normal step',st.combatSteps.current==='normal']);checks.push(['double strike and ordinary blocker are normal-step eligible',eligibleSourceIds(st,'normal').sort().join(',')==='ds,n']);checks.push(['first-strike-only source is excluded from normal step',!eligibleSourceIds(st,'normal').includes('fs')]);
  emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'d2',sourceObjectId:'ds',target:{kind:'object',objectId:'n'},amount:'2',flags:{step:'normal'}});emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'n2',sourceObjectId:'n',target:{kind:'object',objectId:'ds'},amount:'3',flags:{step:'normal'}},2);emit('COMBAT_DAMAGE_STEP_RESOLVED',{step:'normal'});checks.push(['normal-step damage marks both surviving participants',String(st.battle.find(o=>o.id==='n').damageMarked)==='4'&&String(st.battle.find(o=>o.id==='ds').damageMarked)==='3']);
  emit('COMBAT_DAMAGE_STEP_ADVANCED',{});checks.push(['sequence completes after normal step',st.combatSteps.current==='complete'&&!st.combatSteps.active]);checks.push(['resolved assignment ids are retained for idempotence',st.combatSteps.resolvedAssignmentIds.length===4]);return{ok:checks.every(x=>x[1]),checks,state:st,summary:summary(st)}
 }
 return{VERSION,normalize,participantIds,participantObjects,needsFirstStep,eligibleObject,eligibleSourceIds,startIntent,current,assignmentAllowed,nextStep,summary,localQA}
});

