
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGProfileStore=api})(typeof self!=='undefined'?self:this,function(){
  'use strict';
  const VERSION='0.6.0-phase20',KEY='mtgte_profile_v2',LEGACY_KEY='mtgte_profile';
  const DEFAULT_PRIVACY={profile:'friends',gameHistory:'friends',stats:'friends',deckLibrary:'private',onlineStatus:'friends',friendRequests:'friends'};
  const DEFAULT_PREFS={smartPriority:'standard',assistMode:true,announcer:true,haptics:true,reduceMotion:false,highContrast:false,hudDensity:'comfortable'};
  const clone=x=>JSON.parse(JSON.stringify(x));
  const now=()=>new Date().toISOString();
  const uid=(p='id')=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,10);
  const cleanName=n=>String(n||'').trim().replace(/\s+/g,' ').slice(0,32);
  function friendCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='TME-';for(let i=0;i<6;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s}
  function usernameFrom(name,id=''){let base=cleanName(name).toLowerCase().replace(/[^a-z0-9]+/g,'').slice(0,18)||'player';return base+(id?'-'+String(id).slice(-4).toLowerCase():'')}
  function createProfile({displayName,username,avatarId='celestial-guardian',mode='guest'}={}){const id=uid('usr'),name=cleanName(displayName)||'Player';return{schemaVersion:3,id,auth:{mode,provider:null,subject:null},displayName:name,name,username:String(username||usernameFrom(name,id)).toLowerCase(),friendCode:friendCode(),code:null,avatarId:(typeof MTGAvatars!=='undefined'?MTGAvatars.normalize(avatarId):avatarId),createdAt:now(),updatedAt:now(),friends:[],recentPlayers:[],playgroups:[],decks:[],history:[],stats:{games:0,wins:0,losses:0},privacy:clone(DEFAULT_PRIVACY),preferences:clone(DEFAULT_PREFS)}}
  function migrate(raw){if(!raw)return null;if(typeof MTGIntegrity!=='undefined'){try{raw=MTGIntegrity.migrateProfile(raw).profile}catch{}}if(raw.schemaVersion===2||raw.schemaVersion===3){raw.code=raw.friendCode||raw.code;raw.friendCode=raw.friendCode||raw.code;raw.displayName=raw.displayName||raw.name||'Player';raw.name=raw.displayName;raw.friends=raw.friends||[];raw.decks=raw.decks||[];raw.history=raw.history||[];raw.recentPlayers=raw.recentPlayers||[];raw.playgroups=raw.playgroups||[];raw.privacy={...DEFAULT_PRIVACY,...(raw.privacy||{})};raw.preferences={...DEFAULT_PREFS,...(raw.preferences||{})};raw.stats={games:0,wins:0,losses:0,...(raw.stats||{})};raw.sync=raw.sync||null;raw.syncJournal=raw.syncJournal||{schemaVersion:1,entries:[],lastAckRevision:0};raw.avatarId=(typeof MTGAvatars!=='undefined'?MTGAvatars.normalize(raw.avatarId):raw.avatarId||'celestial-guardian');return raw}
    const p=createProfile({displayName:raw.name||raw.displayName||'Player'});p.friends=(raw.friends||[]).map(f=>({...f,code:String(f.code||'').replace(/^TME-/,'')}));if(raw.code){p.friendCode='TME-'+String(raw.code).replace(/^TME-/,'').toUpperCase();p.code=String(raw.code).replace(/^TME-/,'').toUpperCase()}return p}
  function adapter(storage,keyOverride){storage=storage||((typeof localStorage!=='undefined')?localStorage:null);return{load(){if(!storage)return null;let raw=null;try{raw=JSON.parse(storage.getItem(keyOverride||KEY)||'null')}catch{};if(!raw){try{raw=JSON.parse(storage.getItem(LEGACY_KEY)||'null')}catch{}}return migrate(raw)},save(profile){if(!storage)return profile;const p=migrate(clone(profile));p.updatedAt=now();p.code=String(p.friendCode||'').replace(/^TME-/,'');p.name=p.displayName;storage.setItem(keyOverride||KEY,JSON.stringify(p));storage.setItem(LEGACY_KEY,JSON.stringify({name:p.displayName,code:p.code,friends:p.friends}));return p},clear(){storage?.removeItem(keyOverride||KEY);storage?.removeItem(LEGACY_KEY)}}}
  function normalizeDeckInput(deck={}){return{name:cleanName(deck.name)||cleanName(deck.commander)||'Untitled Deck',commander:deck.commander||null,partner:deck.partner||null,format:deck.format||'Commander',colorIdentity:Array.isArray(deck.colorIdentity)?deck.colorIdentity:[],list:Array.isArray(deck.list)?deck.list:[],rawText:String(deck.rawText||''),notes:String(deck.notes||''),favorite:!!deck.favorite,privacy:deck.privacy||'private',mechanics:Array.isArray(deck.mechanics)?deck.mechanics:[],quickActions:Array.isArray(deck.quickActions)?deck.quickActions:[]}}
  function fingerprint(list=[]){return list.map(c=>`${Number(c.q||1)}:${String(c.n||c.name||'').trim().toLowerCase()}`).sort().join('|')}
  function saveDeck(profile,deck){const p=migrate(clone(profile)),d=normalizeDeckInput(deck),fp=fingerprint(d.list),existing=p.decks.find(x=>x.id===deck.id)||p.decks.find(x=>x.name===d.name&&x.commander===d.commander);if(existing){const latest=existing.versions?.[existing.versions.length-1];if(!latest||latest.fingerprint!==fp){existing.versions=existing.versions||[];existing.versions.push({id:uid('dv'),createdAt:now(),fingerprint:fp,list:d.list,rawText:d.rawText,mechanics:d.mechanics,quickActions:d.quickActions});existing.currentVersionId=existing.versions[existing.versions.length-1].id}Object.assign(existing,{...d,id:existing.id,updatedAt:now(),games:existing.games||0,wins:existing.wins||0,losses:existing.losses||0});return{profile:p,deck:existing,created:false}}
    const version={id:uid('dv'),createdAt:now(),fingerprint:fp,list:d.list,rawText:d.rawText,mechanics:d.mechanics,quickActions:d.quickActions};const created={...d,id:uid('deck'),createdAt:now(),updatedAt:now(),lastPlayedAt:null,games:0,wins:0,losses:0,versions:[version],currentVersionId:version.id};p.decks.unshift(created);return{profile:p,deck:created,created:true}}
  function removeDeck(profile,deckId){const p=migrate(clone(profile));p.decks=p.decks.filter(d=>d.id!==deckId);return p}
  function recordRecentPlayer(profile,person){const p=migrate(clone(profile)),code=String(person.friendCode||person.code||'').replace(/^TME-/,'');if(!code)return p;p.recentPlayers=p.recentPlayers.filter(x=>String(x.code)!==code);p.recentPlayers.unshift({name:person.name||person.displayName||'Player',code,lastPlayedAt:now()});p.recentPlayers=p.recentPlayers.slice(0,50);return p}
  function recordMatch(profile,match){const p=migrate(clone(profile)),id=match.id||uid('match');if(p.history.some(x=>String(x.id)===String(id)))return p;const m={id,date:match.date||now(),room:match.room||null,players:match.players||[],localPlayerId:match.localPlayerId??null,winnerId:match.winnerId||null,placement:match.placement??null,result:match.result||null,turnCount:Number(match.turnCount||0),durationMs:Number(match.durationMs||0),deckId:match.deckId||null,deckVersionId:match.deckVersionId||null,commander:match.commander||null,finalState:match.finalState||null,eliminations:match.eliminations||[],timeline:match.timeline||[],awards:match.awards||[]};p.history.unshift(m);p.history=p.history.slice(0,250);p.stats.games++;if(match.result==='win')p.stats.wins++;else if(match.result==='loss')p.stats.losses++;if(m.deckId){const d=p.decks.find(x=>x.id===m.deckId);if(d){d.games=(d.games||0)+1;if(match.result==='win')d.wins=(d.wins||0)+1;else if(match.result==='loss')d.losses=(d.losses||0)+1;d.lastPlayedAt=m.date}}return p}
  function savePlaygroup(profile,group){if(typeof MTGPlaygroups!=='undefined')return MTGPlaygroups.save(migrate(profile),group);const p=migrate(clone(profile));p.playgroups=p.playgroups||[];const i=p.playgroups.findIndex(x=>x.id===group.id);if(i>=0)p.playgroups[i]=clone(group);else p.playgroups.unshift(clone(group));return p}
  function removePlaygroup(profile,id){if(typeof MTGPlaygroups!=='undefined')return MTGPlaygroups.remove(migrate(profile),id);const p=migrate(clone(profile));p.playgroups=(p.playgroups||[]).filter(x=>String(x.id)!==String(id));return p}
  function setPrivacy(profile,key,value){const p=migrate(clone(profile));if(Object.hasOwn(DEFAULT_PRIVACY,key))p.privacy[key]=value;return p}
  function setAvatar(profile,avatarId){const p=migrate(clone(profile));p.avatarId=(typeof MTGAvatars!=='undefined'?MTGAvatars.normalize(avatarId):String(avatarId||'celestial-guardian'));p.updatedAt=now();return p}
  function setPreference(profile,key,value){const p=migrate(clone(profile));if(Object.hasOwn(DEFAULT_PREFS,key))p.preferences[key]=value;return p}
  function publicProfile(profile,viewer='public'){const p=migrate(clone(profile)),canFriends=viewer==='friend';const visible=k=>p.privacy[k]==='public'||(canFriends&&p.privacy[k]==='friends');return{id:p.id,displayName:p.displayName,username:p.username,friendCode:p.friendCode,avatarId:p.avatarId,onlineStatus:visible('onlineStatus')?'available':null,stats:visible('stats')?p.stats:null,decks:visible('deckLibrary')?p.decks.map(d=>({id:d.id,name:d.name,commander:d.commander,format:d.format,favorite:d.favorite,games:d.games,wins:d.wins,losses:d.losses})):[]}}
  function activeDeck(profile,deckId){return migrate(profile)?.decks?.find(d=>d.id===deckId)||null}
  return{VERSION,KEY,DEFAULT_PRIVACY,DEFAULT_PREFS,createProfile,migrate,adapter,saveDeck,removeDeck,recordRecentPlayer,recordMatch,savePlaygroup,removePlaygroup,setPrivacy,setAvatar,setPreference,publicProfile,activeDeck,fingerprint};
});

