
/* Phase 84 — cleanup-step priority exception + repeated cleanup loop. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGCleanupLoop=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const VERSION='phase84-cleanup-loop-1';
function normalize(loop={}){return{iteration:Math.max(0,Number(loop.iteration||0)),collecting:!!loop.collecting,exceptional:!!loop.exceptional,priorityGranted:!!loop.priorityGranted,repeatRequired:!!loop.repeatRequired,sbaObserved:Math.max(0,Number(loop.sbaObserved||0)),lastReason:loop.lastReason?String(loop.lastReason):null,lastCheckpointSeq:Math.max(0,Number(loop.lastCheckpointSeq||0))}}
function begin(loop={},repeat=false){let x=normalize(loop);return{...x,iteration:repeat?Math.max(1,x.iteration+1):1,collecting:true,exceptional:false,priorityGranted:false,repeatRequired:false,sbaObserved:0,lastReason:repeat?'repeated-cleanup':'cleanup-entry'}}
function observeSba(loop={},count=0){let x=normalize(loop),n=Math.max(0,Number(count||0));return{...x,sbaObserved:x.sbaObserved+n}}
function checkpoint(loop={},info={}){let x=normalize(loop),sba=x.sbaObserved+Math.max(0,Number(info.sbaCount||0)),triggers=Math.max(0,Number(info.triggerCount||0)),exceptional=sba>0||triggers>0;return{...x,collecting:false,exceptional,priorityGranted:exceptional,repeatRequired:exceptional,sbaObserved:0,lastReason:exceptional?(sba&&triggers?'sba-and-triggers':sba?'state-based-actions':'triggered-abilities'):'clean',lastCheckpointSeq:Math.max(0,Number(info.seq||x.lastCheckpointSeq||0))}}
function shouldRepeat(state={}){let x=normalize(state.cleanupLoop||{});return String(state.phase||'').toUpperCase()==='CLEANUP'&&x.repeatRequired===true}
function allowsExceptionalPriority(state={}){let x=normalize(state.cleanupLoop||{});return String(state.phase||'').toUpperCase()==='CLEANUP'&&x.priorityGranted===true}
function clearRepeat(loop={}){let x=normalize(loop);return{...x,collecting:false,exceptional:false,priorityGranted:false,repeatRequired:false,sbaObserved:0,lastReason:'cleanup-cleared'}}
function localQA(){let c=[],q=(n,v)=>c.push([n,!!v]),a=begin({},false),b=checkpoint(a,{sbaCount:0,triggerCount:0,seq:10}),x=checkpoint(begin({},false),{sbaCount:1,triggerCount:0,seq:11}),y=checkpoint(begin({},false),{sbaCount:0,triggerCount:2,seq:12}),held=observeSba(begin({},false),1),resumed=checkpoint(held,{sbaCount:0,triggerCount:0,seq:13}),r=begin(y,true);q('first cleanup begins at iteration one',a.iteration===1&&a.collecting);q('clean cleanup grants no priority',!b.exceptional&&!b.priorityGranted&&!b.repeatRequired);q('cleanup SBA creates exception',x.exceptional&&x.priorityGranted&&x.repeatRequired&&x.lastReason==='state-based-actions');q('cleanup trigger creates exception',y.exceptional&&y.repeatRequired&&y.lastReason==='triggered-abilities');q('paused cleanup remembers an earlier SBA until checkpoint resumes',held.sbaObserved===1&&resumed.exceptional&&resumed.lastReason==='state-based-actions'&&resumed.sbaObserved===0);q('repeat cleanup increments iteration',r.iteration===2&&r.collecting&&!r.repeatRequired&&r.sbaObserved===0);q('repeat helper keys off cleanup state',shouldRepeat({phase:'CLEANUP',cleanupLoop:y}));q('normal phase never uses cleanup exception priority',!allowsExceptionalPriority({phase:'END',cleanupLoop:y}));q('clear repeat removes exceptional state',!clearRepeat(y).repeatRequired&&!clearRepeat(y).priorityGranted&&clearRepeat(y).sbaObserved===0);q('version identifies Phase 84',VERSION.includes('phase84'));return{ok:c.every(x=>x[1]),checks:c}}
return{VERSION,normalize,begin,observeSba,checkpoint,shouldRepeat,allowsExceptionalPriority,clearRepeat,localQA};
});
