
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGOpponentDetails=api})(typeof self!=='undefined'?self:this,function(){
'use strict';
const VERSION='phase58-opponent-detail-drawer-1';
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}
function commanderLedger(state={},playerId){const row=state.cmd?.[playerId]||{};return Object.entries(row).map(([source,amount])=>({source,amount:Math.max(0,n(amount))})).filter(x=>x.amount>0).sort((a,b)=>b.amount-a.amount||String(a.source).localeCompare(String(b.source)))}
function summary(state={},player={},viewerId=null){const id=Number(player.id),life=n(state.life?.[id],40),poison=Math.max(0,n(state.poison?.[id])),tax=Math.max(0,n(state.tax?.[id])),casts=Math.max(0,n(state.cmdCasts?.[id])),ledger=commanderLedger(state,id);return{id,name:String(player.name||('Player '+id)),commander:String(player.commander||'Commander'),life,poison,tax,casts,fallen:!!state.fallen?.[id],active:Number(state.active)===id,hasPriority:Number(state.priority??state.respond)===id,monarch:Number(state.mon)===id,initiative:Number(state.ini)===id,commanderDamage:ledger,maxCommanderDamage:ledger[0]?.amount||0,viewerId:viewerId==null?null:Number(viewerId)}}
function actions(info={}){if(info.fallen)return[{id:'inspect',label:'SPECTATE PUBLIC STATE'}];return[{id:'damage',label:'DAMAGE'},{id:'commander-damage',label:'COMMANDER DAMAGE'},{id:'target',label:'TARGET'},{id:'inspect',label:'PUBLIC STATE'}]}
function publicSummary(info={}){return{id:info.id,name:info.name,commander:info.commander,life:info.life,poison:info.poison,tax:info.tax,casts:info.casts,fallen:!!info.fallen,active:!!info.active,hasPriority:!!info.hasPriority,monarch:!!info.monarch,initiative:!!info.initiative,commanderDamage:(info.commanderDamage||[]).map(x=>({source:x.source,amount:x.amount}))}}
function localQA(){const st={life:{2:31},poison:{2:4},tax:{2:2},cmdCasts:{2:2},cmd:{2:{'player:1':8,'player:3':14}},fallen:{2:false},active:2,priority:2,mon:2,ini:null};const p={id:2,name:'Opponent',commander:'Sky Warden',deckList:['hidden']};const s=summary(st,p,1),checks=[];checks.push(['life is public',s.life===31]);checks.push(['poison is public',s.poison===4]);checks.push(['commander tax is public',s.tax===2]);checks.push(['active state is public',s.active]);checks.push(['priority state is public',s.hasPriority]);checks.push(['monarch state is public',s.monarch]);checks.push(['commander damage is source separated',s.commanderDamage.length===2]);checks.push(['largest commander damage is derived',s.maxCommanderDamage===14]);checks.push(['normal opponent exposes damage shortcut',actions(s).some(x=>x.id==='damage')]);checks.push(['fallen opponent removes damage shortcut',!actions({...s,fallen:true}).some(x=>x.id==='damage')]);checks.push(['public summary excludes private deck fields',!('deckList' in publicSummary(s))]);checks.push(['public summary preserves commander damage ledger',publicSummary(s).commanderDamage[0].amount===14]);return{ok:checks.every(x=>x[1]),checks}}
return{VERSION,commanderLedger,summary,actions,publicSummary,localQA};
});

