
/* Phase 107 — Convoke, Delve, Improvise, Affinity, Emerge & Offering. Hardens the canonical Phase 91 cost transaction. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGAlternativePayments=api})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const VERSION='phase107-cost-reduction-alternative-payment-1';
const clone=x=>x==null?x:JSON.parse(JSON.stringify(x));
const SUPPORTED=new Set(['convoke','delve','improvise','affinity','emerge','offering']);
const SIMPLE_MANA=new Set(['W','U','B','R','G','C']);
const COLOR_MANA=new Set(['W','U','B','R','G']);
const ctrl=o=>Number(o?.controllerId??o?.owner??0)||0;
function normalizeCard(c={}){return root.MTGDeckEngine?.normalizeCard?root.MTGDeckEngine.normalizeCard(c):{...c,n:String(c.n||c.name||'Unknown Card'),manaCost:String(c.manaCost||c.mana_cost||''),oracleText:String(c.oracleText||c.oracle_text||''),typeLine:String(c.typeLine||c.type_line||'')}}
function quantity(o){try{return BigInt(String(o?.q??'1'))}catch{return 1n}}
function derived(state,o){return root.MTGLayerEngine?.derived?root.MTGLayerEngine.derived(state,o):o}
function typeLine(state,o){let d=derived(state,o)||o;return String(d?.typeLine||d?.type||o?.typeLine||o?.type||'')}
function hasWord(text,word){let safe=String(word||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp('(?:^|[^A-Za-z0-9])'+safe+'(?:$|[^A-Za-z0-9])','i').test(String(text||''))}
function stripPlural(w=''){let s=String(w||'').trim();if(/ies$/i.test(s)&&s.length>3)return s.slice(0,-3)+'y';if(/ses$/i.test(s)&&s.length>3)return s.slice(0,-2);if(/s$/i.test(s)&&!/(ss|us)$/i.test(s))return s.slice(0,-1);return s}
function qualityTokens(q=''){return String(q||'').trim().split(/\s+/).map(stripPlural).filter(Boolean)}
function qualitySupported(q=''){let x=String(q||'').trim();if(!x||x.length>80||/[^A-Za-z0-9 '\-]/.test(x))return false;if(/\b(?:historic|modified|legendary nonland|nonland|nonartifact|noncreature|colored|colorless|mana value|power|toughness|you own|opponent|card in|cards in)\b/i.test(x))return false;return true}
function matchesQuality(state,o,q=''){if(!qualitySupported(q))return false;let tl=typeLine(state,o);return qualityTokens(q).every(w=>hasWord(tl,w))}
function parseMana(raw=''){return root.MTGAdvancedCastingCosts?.parseMana?root.MTGAdvancedCastingCosts.parseMana(raw):{generic:0,xCount:0,symbols:[],review:['Phase 91 mana parser unavailable.']}}
function manaCostSimple(raw=''){let p=parseMana(raw);return !(p.review||[]).length&&(p.symbols||[]).every(s=>SIMPLE_MANA.has(String(s))) }
function manaValueOf(o={}){let explicit=o?.manaValue??o?.mana_value;if(explicit!==undefined&&explicit!==null&&Number.isFinite(Number(explicit)))return{known:true,value:Math.max(0,Number(explicit))};let c={manaCost:String(o?.manaCost||o?.mana_cost||'')};if(root.MTGAdvancedSpellResolution?.cardManaValue){let r=root.MTGAdvancedSpellResolution.cardManaValue(c,0);if(r?.known)return{known:true,value:Math.max(0,Number(r.value||0))};return{known:false,reason:(r?.reasons||[]).join(' ')||'unknown-mana-value'}}let p=parseMana(c.manaCost);if((p.review||[]).length)return{known:false,reason:'unsupported-mana-cost'};return{known:true,value:Number(p.generic||0)+(p.symbols||[]).length}}
function colorsOf(state,o={}){let d=derived(state,o)||o,raw=Array.isArray(d?.colors)?d.colors:Array.isArray(o?.colors)?o.colors:[],out=[];for(let c of raw){let x=String(c||'').trim().toUpperCase(),map={WHITE:'W',BLUE:'U',BLACK:'B',RED:'R',GREEN:'G'};x=map[x]||x;if(COLOR_MANA.has(x)&&!out.includes(x))out.push(x)}return out}
function parse(card={}){
 let c=normalizeCard(card),text=String(c.oracleText||''),lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean),mechanics=[],alternates=[],review=[],counts={};
 const add=(kind,data={})=>{counts[kind]=(counts[kind]||0)+1;let m={id:'p107_'+kind+'_'+counts[kind],kind,...data};mechanics.push(m);return m};
 for(const raw of lines){let line=raw.replace(/\s*\([^)]*\)\s*$/,'').trim(),m;
  if(/^Convoke\b/i.test(line)){add('convoke',{label:'Convoke'});continue}
  if(/^Delve\b/i.test(line)){add('delve',{label:'Delve'});continue}
  if(/^Improvise\b/i.test(line)){add('improvise',{label:'Improvise'});continue}
  if((m=line.match(/^Affinity for (.+?)\.?$/i))){let quality=String(m[1]).trim();add('affinity',{quality,label:'Affinity for '+quality});if(!qualitySupported(quality))review.push('Affinity scope “'+quality+'” is not in the exact public type-line subset.');continue}
  if((m=line.match(/^Emerge from (.+?)\s+((?:\{[^}]+\})+)\.?$/i))){let quality=String(m[1]).trim(),cost=String(m[2]);let em=add('emerge',{quality,cost,label:'Emerge from '+quality+' '+cost});alternates.push({id:'p107_emerge_alt_'+counts.emerge,label:em.label,manaCost:cost,withoutMana:false,mechanic:'emerge'});if(!qualitySupported(quality))review.push('Emerge quality “'+quality+'” is not in the exact public type-line subset.');if((parseMana(cost).review||[]).length)review.push('Emerge cost “'+cost+'” is not exactly representable.');continue}
  if((m=line.match(/^Emerge\s+((?:\{[^}]+\})+)\.?$/i))){let cost=String(m[1]);let em=add('emerge',{quality:'creature',cost,label:'Emerge '+cost});alternates.push({id:'p107_emerge_alt_'+counts.emerge,label:em.label,manaCost:cost,withoutMana:false,mechanic:'emerge'});if((parseMana(cost).review||[]).length)review.push('Emerge cost “'+cost+'” is not exactly representable.');continue}
  if((m=line.match(/^(.+?) offering\.?$/i))){let quality=String(m[1]).trim();add('offering',{quality,label:quality+' offering'});if(!qualitySupported(quality))review.push('Offering quality “'+quality+'” is not in the exact public type-line subset.');continue}
 }
 for(const kind of ['convoke','delve','improvise'])if((counts[kind]||0)>1)mechanics=mechanics.filter((x,i,a)=>x.kind!==kind||a.findIndex(y=>y.kind===kind)===i);
 if((counts.emerge||0)>1)review.push('Multiple Emerge alternatives require MANUAL / JUDGE REVIEW in Phase 107.');
 if((counts.offering||0)>1)review.push('Multiple Offering abilities require MANUAL / JUDGE REVIEW in Phase 107.');
 for(const kind of SUPPORTED){let present=new RegExp('(?:^|\\n)(?:.+? )?'+kind+'\\b','i').test(text);if(present&&!(counts[kind]||0))review.push(kind[0].toUpperCase()+kind.slice(1)+' text could not be parsed exactly.');}
 return{mechanics,alternates,review:[...new Set(review)]};
}
function mechanic(p,kind){return(p?.phase107Costs||[]).find(x=>String(x.kind)===String(kind))||null}
function selectedBase(p={}){return root.MTGAdvancedCastingCosts?.selectedBase?root.MTGAdvancedCastingCosts.selectedBase(p):{mechanic:null}}
function selectedEmerge(p={}){return String(selectedBase(p)?.mechanic||'').toLowerCase()==='emerge'?mechanic(p,'emerge'):null}
function choice(p,kind){let v=p?.choices?.phase107?.[kind];if(v!==undefined)return v;return p?.choices?.[kind]}
function individualPermanents(state,pred){let pid=Number(state?._p107PlayerId||0);return(state?.battle||[]).filter(o=>ctrl(o)===pid&&quantity(o)===1n&&(!pred||pred(o))).map(o=>({objectId:String(o.id),label:String(o.name||o.id),object:o}))}
function permanentCandidates(state,p,kind){let st={...state,_p107PlayerId:Number(p?.playerId||0)},m=kind==='emerge'?selectedEmerge(p):mechanic(p,kind);if(!m)return[];
 if(kind==='emerge')return individualPermanents(st,o=>matchesQuality(state,o,m.quality||'creature')).map(x=>{let mv=manaValueOf(x.object);return{objectId:x.objectId,label:x.label+(mv.known?' · mana value '+mv.value:' · mana value ?'),manaValue:mv.known?mv.value:null}}).filter(x=>x.manaValue!==null);
 if(kind==='offering')return individualPermanents(st,o=>matchesQuality(state,o,m.quality)).map(x=>{let mc=String(x.object.manaCost||x.object.mana_cost||'');return{objectId:x.objectId,label:x.label+' · '+(mc||'{0}'),manaCost:mc}}).filter(x=>manaCostSimple(x.manaCost));
 return[];
}
function tapCandidates(state,p,kind){let pid=Number(p?.playerId||0),reserved=new Set();for(const c of p?.additionalCosts||[])if(c.kind==='tap'&&p?.choices?.additional?.[c.id])reserved.add(String(p.choices.additional[c.id]));if(kind==='improvise')for(const oid of choice(p,'convoke')||[])reserved.add(String(oid));return(state?.battle||[]).filter(o=>ctrl(o)===pid&&quantity(o)===1n&&!o.tapped&&!reserved.has(String(o.id))&&(kind==='convoke'?matchesQuality(state,o,'creature'):matchesQuality(state,o,'artifact'))).map(o=>({objectId:String(o.id),label:String(o.name||o.id),colors:colorsOf(state,o)}))}
function delveCandidates(state,p){return(state?.zones?.graveyard||[]).filter(o=>Number(o.owner??p?.playerId)===Number(p?.playerId)&&quantity(o)===1n).map(o=>({objectId:String(o.id),label:String(o.name||o.id)}))}
function sameIds(value,candidates){if(!Array.isArray(value)||value.length>100||value.some(x=>typeof x!=='string'))return false;let u=[...new Set(value)],legal=new Set((candidates||[]).map(x=>String(x.objectId)));return u.length===value.length&&u.every(x=>legal.has(String(x)))}
function offeringTimingOverride(card={}){let r=parse(card),m=r.mechanics.find(x=>x.kind==='offering');return!!m&&!r.review.length}
function prepaymentStage(state,p){let em=selectedEmerge(p);if(em&&choice(p,'emerge')===undefined)return'phase107:emerge';let off=mechanic(p,'offering');if(off&&choice(p,'offering')===undefined)return'phase107:offering';return null}
function paymentStage(state,p){for(const k of ['convoke','improvise','delve'])if(mechanic(p,k)&&choice(p,k)===undefined)return'phase107:'+k;return null}
function validateChoice(state,p,key,value){let kind=String(key||'').replace(/^phase107:/,'');if(!SUPPORTED.has(kind))return{ok:false,reason:'phase107-unknown-choice'};let expected=prepaymentStage(state,p)||paymentStage(state,p);if(expected!=='phase107:'+kind)return{ok:false,reason:'phase107-wrong-stage'};
 if(kind==='emerge'){let oid=typeof value==='string'?value:String(value?.objectId||'');if(!permanentCandidates(state,p,'emerge').some(x=>x.objectId===oid))return{ok:false,reason:'phase107-emerge-sacrifice'};return{ok:true,value:oid}}
 if(kind==='offering'){let required=!!p?.castPermission?.phase107OfferingRequired;if(value===false&&!required)return{ok:true,value:false};let oid=typeof value==='string'?value:String(value?.objectId||'');if(!permanentCandidates(state,p,'offering').some(x=>x.objectId===oid))return{ok:false,reason:required?'phase107-offering-required-for-timing':'phase107-offering-sacrifice'};return{ok:true,value:oid}}
 if(kind==='convoke'){let cand=tapCandidates(state,p,'convoke');if(!sameIds(value,cand))return{ok:false,reason:'phase107-convoke-selection'};let u=paymentUsage(state,p,{convoke:value,improvise:choice(p,'improvise')||[],delve:choice(p,'delve')||[]});return u.ok?{ok:true,value:value.slice()}:{ok:false,reason:u.reason}}
 if(kind==='improvise'){let cand=tapCandidates(state,p,'improvise');if(!sameIds(value,cand))return{ok:false,reason:'phase107-improvise-selection'};let u=paymentUsage(state,p,{convoke:choice(p,'convoke')||[],improvise:value,delve:choice(p,'delve')||[]});return u.ok?{ok:true,value:value.slice()}:{ok:false,reason:u.reason}}
 if(kind==='delve'){let cand=delveCandidates(state,p);if(!sameIds(value,cand))return{ok:false,reason:'phase107-delve-selection'};let u=paymentUsage(state,p,{convoke:choice(p,'convoke')||[],improvise:choice(p,'improvise')||[],delve:value});return u.ok?{ok:true,value:value.slice()}:{ok:false,reason:u.reason}}
 return{ok:false,reason:'phase107-choice-unhandled'}
}
function simpleAffinityCount(state,p,m){if(!m||!qualitySupported(m.quality))return{known:false,count:0};let count=0;for(const o of state?.battle||[])if(ctrl(o)===Number(p?.playerId)&&matchesQuality(state,o,m.quality))count+=Number(quantity(o));return{known:true,count}}
function reduceByOffering(generic,symbols,manaCost){let p=parseMana(manaCost);if((p.review||[]).length||(p.symbols||[]).some(s=>!SIMPLE_MANA.has(String(s))))return{ok:false,reason:'phase107-offering-complex-mana-cost'};let g=Math.max(0,Number(generic||0)),out=(symbols||[]).map(String);g=Math.max(0,g-Number(p.generic||0));for(const sym of p.symbols||[]){let i=out.indexOf(String(sym));if(i>=0)out.splice(i,1);else g=Math.max(0,g-1)}return{ok:true,generic:g,symbols:out}}
function adjustment(state,p,base={}){let generic=Math.max(0,Number(base.generic||0)),symbols=(base.symbols||[]).map(String),steps=[],reduction=0;
 for(const m of p?.phase107Costs||[])if(m.kind==='affinity'){let c=simpleAffinityCount(state,p,m);if(!c.known)return{ok:false,reason:'phase107-affinity-scope'};generic=Math.max(0,generic-c.count);reduction+=c.count;steps.push(m.label+' · −'+c.count)}
 let em=selectedEmerge(p),emChoice=choice(p,'emerge');if(em&&emChoice){let rec=permanentCandidates(state,p,'emerge').find(x=>x.objectId===String(emChoice));if(!rec)return{ok:false,reason:'phase107-emerge-state-changed'};generic=Math.max(0,generic-Number(rec.manaValue||0));reduction+=Number(rec.manaValue||0);steps.push('Emerge sacrifice mana value '+rec.manaValue+' · generic −'+rec.manaValue)}
 let off=mechanic(p,'offering'),offChoice=choice(p,'offering');if(off&&typeof offChoice==='string'){let rec=permanentCandidates(state,p,'offering').find(x=>x.objectId===String(offChoice));if(!rec)return{ok:false,reason:'phase107-offering-state-changed'};let r=reduceByOffering(generic,symbols,rec.manaCost);if(!r.ok)return r;generic=r.generic;symbols=r.symbols;steps.push(off.label+' · reduce by '+(rec.manaCost||'{0}'))}
 return{ok:true,generic,symbols,steps,reduction}}
function maximumColoredMatches(creatures=[],required=[]){let slots=[];for(const [color,n] of Object.entries(required))for(let i=0;i<n;i++)slots.push(color);let match=new Array(slots.length).fill(-1),seen;function dfs(ci){for(let s=0;s<slots.length;s++){if(seen[s]||!creatures[ci].colors.includes(slots[s]))continue;seen[s]=true;if(match[s]===-1||dfs(match[s])){match[s]=ci;return true}}return false}let count=0;for(let i=0;i<creatures.length;i++){seen=new Array(slots.length).fill(false);if(dfs(i))count++}return count}
function paymentUsage(state,p,override={}){let calc=root.MTGAdvancedCastingCosts?.calculate?root.MTGAdvancedCastingCosts.calculate(state,p):null;if(!calc)return{ok:false,reason:'phase107-cost-calculator-missing'};let symbols=(calc.symbols||[]).map(String);if(symbols.some(s=>!SIMPLE_MANA.has(s)))return{ok:false,reason:'phase107-complex-payment-symbol'};let generic=Math.max(0,Number(calc.genericFinal||0)),con=override.convoke||[],imp=override.improvise||[],del=override.delve||[],convCand=tapCandidates(state,p,'convoke');if(!sameIds(con,convCand))return{ok:false,reason:'phase107-convoke-state-changed'};let impCand=tapCandidates(state,p,'improvise');if(!sameIds(imp,impCand))return{ok:false,reason:'phase107-improvise-state-changed'};if(!sameIds(del,delveCandidates(state,p)))return{ok:false,reason:'phase107-delve-state-changed'};if(imp.some(x=>con.includes(x)))return{ok:false,reason:'phase107-tap-overlap'};
 let required={W:0,U:0,B:0,R:0,G:0};for(const s of symbols)if(COLOR_MANA.has(s))required[s]++;let selected=con.map(id=>{let c=convCand.find(x=>x.objectId===id);return{objectId:id,colors:c?.colors||[]}}),colored=maximumColoredMatches(selected,required),conGeneric=selected.length-colored;if(conGeneric>generic)return{ok:false,reason:'phase107-convoke-exceeds-payable-cost'};let genericLeft=generic-conGeneric;if(imp.length+del.length>genericLeft)return{ok:false,reason:'phase107-generic-payment-exceeds-cost'};return{ok:true,convokeColored:colored,convokeGeneric:conGeneric,genericLeftAfterAll:genericLeft-imp.length-del.length,improvise:imp.length,delve:del.length}}
function finalizeCosts(state,p,ctx={}){let actions=[],usedTap=ctx.usedTap||new Set(),usedSac=ctx.usedSac||new Set(),calc=ctx.calc||root.MTGAdvancedCastingCosts?.calculate?.(state,p),em=selectedEmerge(p),emChoice=choice(p,'emerge'),off=mechanic(p,'offering'),offChoice=choice(p,'offering');
 for(const [kind,oid] of [['emerge',em&&emChoice?String(emChoice):''],['offering',off&&typeof offChoice==='string'?String(offChoice):'']])if(oid){let legal=permanentCandidates(state,p,kind).some(x=>x.objectId===oid);if(!legal)return{ok:false,reason:'phase107-'+kind+'-state-changed'};if(usedSac.has(oid))return{ok:false,reason:'phase107-sacrifice-overlap'};usedSac.add(oid);actions.push({type:'OBJECT_ZONE_CHANGED',payload:{objectId:oid,toZone:'graveyard',reset:true},reason:'phase107-'+kind})}
 let con=choice(p,'convoke')||[],imp=choice(p,'improvise')||[],del=choice(p,'delve')||[],usage=paymentUsage(state,p,{convoke:con,improvise:imp,delve:del});if(!usage.ok)return usage;for(const oid of [...con,...imp]){if(usedTap.has(String(oid)))return{ok:false,reason:'phase107-tap-overlap'};usedTap.add(String(oid));actions.push({type:'PERMANENT_TAPPED_SET',payload:{objectId:String(oid),tapped:true},reason:'phase107-'+(con.includes(oid)?'convoke':'improvise')})}for(const oid of del)actions.push({type:'OBJECT_ZONE_CHANGED',payload:{objectId:String(oid),toZone:'exile',reset:true},reason:'phase107-delve'});return{ok:true,actions,usage,calculation:calc}}
function planData(state,p){let data={mechanics:clone(p?.phase107Costs||[]),choices:clone(p?.choices?.phase107||{}),selectedEmerge:clone(selectedEmerge(p)),timingOfferingRequired:!!p?.castPermission?.phase107OfferingRequired};let a=adjustment(state,p,{generic:root.MTGAdvancedCastingCosts?.calculate?0:0,symbols:[]});return data}
function compatibilityCandidates(state,p,kind){if(kind==='convoke'||kind==='improvise')return tapCandidates(state,p,kind);if(kind==='delve')return delveCandidates(state,p);return permanentCandidates(state,p,kind)}
function pendingReview(p){let r=[];if(mechanic(p,'convoke')){let costs=[p?.cardPublic?.manaCost||''];for(const c of p?.additionalCosts||[])if(c.kind==='mana')costs.push(c.manaCost);if(p?.kicker?.manaCost)costs.push(p.kicker.manaCost);for(const m of p?.phase106Costs||[]){if(m?.cost?.kind==='mana')costs.push(m.cost.manaCost);for(const md of m?.modes||[])if(md?.cost?.kind==='mana')costs.push(md.cost.manaCost)}if(costs.some(x=>{let pm=parseMana(x);return(pm.symbols||[]).some(s=>!SIMPLE_MANA.has(String(s)))||(pm.review||[]).length}))r.push('Convoke with hybrid, Phyrexian, snow, or other complex mana symbols requires MANUAL / JUDGE REVIEW in Phase 107.')}return r}
function localQA(engine){let c=[],q=(n,v)=>c.push([n,!!v]),state={active:1,phase:'MAIN 1',life:{1:40},battle:[{id:'g',name:'Green Creature',owner:1,controllerId:1,typeLine:'Creature — Elf',colors:['G'],manaCost:'{1}{G}',manaValue:2,q:'1',tapped:false},{id:'w',name:'White Artifact Creature',owner:1,controllerId:1,typeLine:'Artifact Creature — Fox',colors:['W'],manaCost:'{2}{W}',manaValue:3,q:'1',tapped:false},{id:'a',name:'Relic',owner:1,controllerId:1,typeLine:'Artifact',manaCost:'{3}',manaValue:3,q:'1',tapped:false},{id:'snake',name:'Snake',owner:1,controllerId:1,typeLine:'Creature — Snake',colors:['G'],manaCost:'{1}{G}',manaValue:2,q:'1',tapped:false}],zones:{graveyard:[{id:'gy1',name:'Past',owner:1,q:'1'},{id:'gy2',name:'Past 2',owner:1,q:'1'}]},stack:[],events:[],snapshots:[],feed:[]};
 q('all six Phase 107 mechanics parse',Array.from(SUPPORTED).every(k=>parse({typeLine:'Creature',oracleText:k==='affinity'?'Affinity for artifacts':k==='emerge'?'Emerge {5}{G}':k==='offering'?'Snake offering':k[0].toUpperCase()+k.slice(1)}).mechanics.some(m=>m.kind===k)));
 q('Emerge becomes a real alternative cost',parse({typeLine:'Creature',oracleText:'Emerge {5}{G}'}).alternates[0]?.mechanic==='emerge');q('Emerge from quality parses exact sacrifice quality',parse({typeLine:'Creature',oracleText:'Emerge from artifacts {4}{U}'}).mechanics[0]?.quality==='artifacts');q('Offering timing is recognized only for parsed Offering',offeringTimingOverride({oracleText:'Snake offering'}));q('Affinity unsupported semantic quality routes to review',parse({oracleText:'Affinity for historic permanents'}).review.length>0);
 if(root.MTGAdvancedCastingCosts){let cv=root.MTGAdvancedCastingCosts.createPending(state,{playerId:1,name:'Conv',cardPublic:{n:'Conv',manaCost:'{2}{G}',typeLine:'Sorcery',oracleText:'Convoke'}},[{id:1}]);q('Phase 91 delegates Convoke to Phase 107',cv.stage==='phase107:convoke');let colorOnly=root.MTGAdvancedCastingCosts.createPending(state,{playerId:1,name:'Color Conv',cardPublic:{n:'Color Conv',manaCost:'{G}',typeLine:'Sorcery',oracleText:'Convoke'}},[{id:1}]);let bad=validateChoice(state,colorOnly,'phase107:convoke',['w']);q('Convoke rejects a creature that cannot cover the only colored symbol',bad.ok===false);let good=validateChoice(state,cv,'phase107:convoke',['g','w']);q('Convoke accepts a same-color creature plus generic helper',good.ok);cv.choices.phase107.convoke=['g','w'];cv.choices.paymentConfirmed=true;let cf=root.MTGAdvancedCastingCosts.finalize(state,cv);q('Convoke commits authoritative taps without reducing displayed total cost',cf.ok&&root.MTGAdvancedCastingCosts.calculate(state,cv).totalCost==='{2}{G}'&&cf.publicActions.filter(x=>x.type==='PERMANENT_TAPPED_SET').length===2);
 let de=root.MTGAdvancedCastingCosts.createPending(state,{playerId:1,name:'Delve',cardPublic:{n:'Delve',manaCost:'{2}{B}',typeLine:'Sorcery',oracleText:'Delve'}},[{id:1}]);de.choices.phase107.delve=['gy1','gy2'];de.choices.paymentConfirmed=true;q('Delve can pay only generic mana and exiles selected graveyard cards',root.MTGAdvancedCastingCosts.finalize(state,de).publicActions.filter(x=>x.payload?.toZone==='exile').length===2);
 let af=root.MTGAdvancedCastingCosts.createPending(state,{playerId:1,name:'Affinity',cardPublic:{n:'Affinity',manaCost:'{5}{U}',typeLine:'Artifact Creature',oracleText:'Affinity for artifacts'}},[{id:1}]);af.choices.paymentConfirmed=true;q('Affinity dynamically reduces generic cost for controlled matching permanents',root.MTGAdvancedCastingCosts.calculate(state,af).totalCost==='{3}{U}');
 let em=root.MTGAdvancedCastingCosts.createPending(state,{playerId:1,name:'Emerge',cardPublic:{n:'Emerge',manaCost:'{8}',typeLine:'Creature — Eldrazi',oracleText:'Emerge {5}{U}'}},[{id:1}]);let alt=em.alternates.find(x=>x.mechanic==='emerge');em.choices.base=alt.id;q('Emerge requests its sacrifice after alternative selection',root.MTGAdvancedCastingCosts.nextStage(state,em)==='phase107:emerge');em.choices.phase107.emerge='w';em.choices.paymentConfirmed=true;q('Emerge reduces only generic part by sacrificed mana value',root.MTGAdvancedCastingCosts.calculate(state,em).totalCost==='{2}{U}');q('Emerge sacrifice is committed as casting cost',root.MTGAdvancedCastingCosts.finalize(state,em).publicActions.some(x=>x.reason==='phase107-emerge'));
 let of=root.MTGAdvancedCastingCosts.createPending({...state,active:2,phase:'COMBAT'},{playerId:1,name:'Offer',cardPublic:{n:'Offer',manaCost:'{4}{G}{G}',typeLine:'Creature — Spirit',oracleText:'Snake offering'},castPermission:{timingOverride:true,phase107OfferingRequired:true}},[{id:1}]);q('Offering cannot be declined when it supplied instant timing',!validateChoice(state,of,'phase107:offering',false).ok);of.choices.phase107.offering='snake';of.choices.paymentConfirmed=true;q('Offering reduces matching colored mana and generic by sacrificed mana cost',root.MTGAdvancedCastingCosts.calculate(state,of).totalCost==='{3}{G}');q('Offering sacrifice is committed exactly once',root.MTGAdvancedCastingCosts.finalize(state,of).publicActions.filter(x=>x.reason==='phase107-offering').length===1);
 let reconnect=JSON.parse(JSON.stringify(of));q('Phase 107 choices survive serialization/reconnect normalization shape',reconnect.choices.phase107.offering==='snake');
 let im=root.MTGAdvancedCastingCosts.createPending(state,{playerId:1,name:'Improvise',cardPublic:{n:'Improvise',manaCost:'{2}{U}',typeLine:'Sorcery',oracleText:'Improvise'}},[{id:1}]);im.choices.phase107.improvise=['a'];im.choices.paymentConfirmed=true;let imf=root.MTGAdvancedCastingCosts.finalize(state,im);q('Improvise pays only generic mana and commits an artifact tap',imf.ok&&imf.publicActions.some(x=>x.type==='PERMANENT_TAPPED_SET'&&x.payload?.objectId==='a'));
 let overlap=root.MTGAdvancedCastingCosts.createPending(state,{playerId:1,name:'Shared Tap',cardPublic:{n:'Shared Tap',manaCost:'{2}{G}',typeLine:'Sorcery',oracleText:'Convoke\nImprovise'}},[{id:1}]);overlap.choices.phase107.convoke=['w'];let ov=validateChoice(state,overlap,'phase107:improvise',['w']);q('one permanent cannot pay both Convoke and Improvise',ov.ok===false);
 if(root.MTGAdvancedSpellResolution?.castPermission){let op=root.MTGAdvancedSpellResolution.castPermission({...state,active:2,phase:'COMBAT'},1,{n:'Offer Timing',manaCost:'{4}{G}',typeLine:'Creature — Spirit',oracleText:'Snake offering'},{fromZone:'hand'});q('Offering grants its authoritative non-sorcery timing permission',op.hardBlock===false&&op.permission?.phase107OfferingRequired===true)}else q('advanced spell-resolution permission engine is available',false);
 if(engine){let es=engine.normalizeState({active:1,phase:'MAIN 1',life:{1:40,2:40},events:[],snapshots:[],feed:[],stack:[],battle:[],zones:{graveyard:[{id:'rgy',name:'Past',owner:1,q:'1'}]}}),rp=root.MTGAdvancedCastingCosts.createPending(es,{playerId:1,name:'Reducer Delve',cardPublic:{n:'Reducer Delve',manaCost:'{1}{B}',typeLine:'Sorcery',oracleText:'Delve'}},[{id:1},{id:2}]);engine.reduce(es,engine.makeEvent(es,'CASTING_COST_PENDING_SET',{pending:rp},1,{source:'phase107-qa'}));engine.reduce(es,engine.makeEvent(es,'CASTING_COST_CHOICE_APPLIED',{choiceId:rp.id,key:'phase107:delve',value:['rgy']},2,{source:'phase107-qa'}));q('wrong player cannot alter Phase 107 payment choice',es.castingCostPending?.choices?.phase107?.delve===undefined);engine.reduce(es,engine.makeEvent(es,'CASTING_COST_CHOICE_APPLIED',{choiceId:rp.id,key:'phase107:delve',value:['rgy']},1,{source:'phase107-qa'}));q('assigned player can authoritatively choose Phase 107 payment',Array.isArray(es.castingCostPending?.choices?.phase107?.delve)&&es.castingCostPending.choices.phase107.delve[0]==='rgy');let er=engine.normalizeState(JSON.parse(JSON.stringify(es)));q('Phase 107 authoritative payment survives reconnect normalization',er.castingCostPending?.choices?.phase107?.delve?.[0]==='rgy')}else q('authoritative engine is available for Phase 107 QA',false);
 }else q('Phase 91 cost engine is available',false);q('version identifies Phase 107',VERSION.includes('phase107'));return{ok:c.every(x=>x[1]),checks:c}}
return{VERSION,SUPPORTED,parse,mechanic,selectedEmerge,offeringTimingOverride,prepaymentStage,paymentStage,validateChoice,permanentCandidates,tapCandidates,delveCandidates,compatibilityCandidates,adjustment,paymentUsage,finalizeCosts,planData,pendingReview,matchesQuality,manaValueOf,localQA};
});

