
/* Phase 104 — Disturb, Retrace, Jump-start, Aftermath, Rebound + Phase 103 alternate-zone casting state machines. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGAlternateZoneCasting=api})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const VERSION='phase104-graveyard-casting-rebound-1';
const clone=x=>JSON.parse(JSON.stringify(x));
const lc=v=>String(v||'').trim().toLowerCase();
const WORD_NUM={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12};
function blank(){return{version:VERSION,records:{}}}
function normalizeRecord(raw={},id=''){let r=raw&&typeof raw==='object'?raw:{};r.id=String(r.id||id||'');r.kind=lc(r.kind||'');r.playerId=Number(r.playerId||0)||0;r.stableObjectId=String(r.stableObjectId||r.objectId||'');r.objectId=String(r.objectId||r.stableObjectId||'');r.incarnationId=String(r.incarnationId||'');r.zoneChangeId=String(r.zoneChangeId||'');r.permissionId=r.permissionId?String(r.permissionId):null;r.alternativeCost=r.alternativeCost==null?null:String(r.alternativeCost);r.expectedCardName=r.expectedCardName==null?null:String(r.expectedCardName);r.expectedFaceId=r.expectedFaceId==null?null:String(r.expectedFaceId);r.castTransformed=!!r.castTransformed;r.requiredAdditionalCost=r.requiredAdditionalCost&&typeof r.requiredAdditionalCost==='object'?clone(r.requiredAdditionalCost):null;r.reboundResolvedSeq=Number(r.reboundResolvedSeq||0);r.reboundTriggered=!!r.reboundTriggered;r.escapeCount=Math.max(0,Math.trunc(Number(r.escapeCount||0)));r.escapePayment=Array.isArray(r.escapePayment)?r.escapePayment.map(x=>({objectId:String(x.objectId||''),stableObjectId:String(x.stableObjectId||x.objectId||''),incarnationId:String(x.incarnationId||'')})).filter(x=>x.objectId&&x.incarnationId):[];r.escapePaymentCommitted=!!r.escapePaymentCommitted;r.escapePaymentCommittedSeq=Number(r.escapePaymentCommittedSeq||0);r.createdSeq=Number(r.createdSeq||0);r.createdTurn=Number(r.createdTurn||0);r.active=r.active!==false&&!r.invalidated&&!r.consumed&&!r.declined&&!r.triggerCountered;r.invalidated=!!r.invalidated;r.consumed=!!r.consumed;r.declined=!!r.declined;r.triggerCountered=!!r.triggerCountered;r.triggered=!!r.triggered;r.cast=!!r.cast;r.futurePermissionGranted=!!r.futurePermissionGranted;r.version=VERSION;return r}
function normalizeState(state={}){state.alternateZoneCasting=state.alternateZoneCasting&&typeof state.alternateZoneCasting==='object'?state.alternateZoneCasting:blank();state.alternateZoneCasting.version=VERSION;state.alternateZoneCasting.records=state.alternateZoneCasting.records&&typeof state.alternateZoneCasting.records==='object'?state.alternateZoneCasting.records:{};for(const[id,raw]of Object.entries(state.alternateZoneCasting.records)){let r=normalizeRecord(raw,id);if(!r.id){delete state.alternateZoneCasting.records[id];continue}if(id!==r.id){delete state.alternateZoneCasting.records[id];state.alternateZoneCasting.records[r.id]=r}else state.alternateZoneCasting.records[id]=r}return state.alternateZoneCasting}
function manaOnly(v=''){let s=String(v||'').trim();return s&&/^(?:\{[^}]+\})+$/.test(s)?s:null}
function parseFlashbackAll(card={}){let out=[];for(const m of String(card.oracleText||card.oracle_text||'').matchAll(/\bFlashback\s+((?:\{[^}]+\})+)/gi)){let cost=manaOnly(m[1]);if(cost)out.push({cost,index:out.length})}return out}
function parseFlashback(card={},i=0){return parseFlashbackAll(card)[Math.max(0,Math.trunc(Number(i||0)))]||null}
function parseMadnessAll(card={}){let out=[];for(const m of String(card.oracleText||card.oracle_text||'').matchAll(/\bMadness\s+((?:\{[^}]+\})+)/gi)){let cost=manaOnly(m[1]);if(cost)out.push({cost,index:out.length})}return out}
function parseMadness(card={},i=0){return parseMadnessAll(card)[Math.max(0,Math.trunc(Number(i||0)))]||null}
function permanentCardType(card={}){let tl=String(card.typeLine||card.type_line||'');return /(?:^|\W)(artifact|battle|creature|enchantment|land|planeswalker)(?:$|\W)/i.test(tl)}
function parseWarpAll(card={}){if(!permanentCardType(card))return[];let out=[];for(const m of String(card.oracleText||card.oracle_text||'').matchAll(/\bWarp\s+((?:\{[^}]+\})+)/gi)){let cost=manaOnly(m[1]);if(cost)out.push({cost,index:out.length})}return out}
function parseWarp(card={},i=0){return parseWarpAll(card)[Math.max(0,Math.trunc(Number(i||0)))]||null}
function parseEscape(card={}){let text=String(card.oracleText||card.oracle_text||''),m=text.match(/\bEscape\s*[—–-]\s*((?:\{[^}]+\})+)\s*,\s*Exile\s+([A-Za-z0-9]+)\s+other cards?\s+from your graveyard/i);if(!m)return null;let cost=manaOnly(m[1]),raw=lc(m[2]),n=/^\d+$/.test(raw)?Number(raw):WORD_NUM[raw];return cost&&Number.isInteger(n)&&n>=0?{cost,count:n}:null}
function normalizedCard(card={}){return root.MTGDeckEngine?.normalizeCard?root.MTGDeckEngine.normalizeCard(card):clone(card)}
function cardFaces(card={}){let c=normalizedCard(card);return{card:c,faces:Array.isArray(c.faces)?c.faces:[]}}
function faceCastCard(card={},face={},meta={}){let c=normalizedCard(card);return{n:String(face.name||c.n||'Card'),oracleText:String(face.oracleText||''),typeLine:String(face.typeLine||''),keywords:Array.isArray(face.keywords)?face.keywords.slice():[],subtypes:Array.isArray(face.subtypes)?face.subtypes.slice():[],colors:Array.isArray(face.colors)?face.colors.slice():[],manaCost:String(face.manaCost||''),oracleId:c.oracleId||null,layout:String(c.layout||''),faces:Array.isArray(c.faces)?clone(c.faces):[],resolved:c.resolved===true,...meta}}
function keywordPresent(card={},keyword=''){let k=String(keyword||''),text=String(card.oracleText||card.oracle_text||''),keys=Array.isArray(card.keywords)?card.keywords:[];return keys.some(x=>lc(x)===lc(k))||new RegExp('(?:^|\\n|\\b)'+k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?:\\b|$)','i').test(text)}
function parseRetrace(card={}){return keywordPresent(card,'Retrace')?{requiredAdditionalCost:{kind:'discard',cardType:'Land',label:'Discard a land card'}}:null}
function parseJumpStart(card={}){return keywordPresent(card,'Jump-start')||keywordPresent(card,'Jump start')?{requiredAdditionalCost:{kind:'discard',label:'Discard a card'}}:null}
function parseRebound(card={}){let tl=String(card.typeLine||card.type_line||'');return /\b(?:Instant|Sorcery)\b/i.test(tl)&&keywordPresent(card,'Rebound')?{rebound:true}:null}
function parseDisturb(card={}){let {card:c,faces}=cardFaces(card);if(faces.length<2)return null;let front=null,cost=null;for(const f of faces){let m=String(f.oracleText||'').match(/\bDisturb\s+((?:\{[^}]+\})+)/i);if(m&&manaOnly(m[1])){front=f;cost=manaOnly(m[1]);break}}if(!front)return null;let back=faces.find(f=>f!==front);if(!back)return null;let backFaceId=String(back.id||faces.indexOf(back));return{cost,frontFaceId:String(front.id||faces.indexOf(front)),backFaceId,front,back,castCard:faceCastCard(c,back,{phase104FaceId:backFaceId,phase104Mechanic:'disturb'})}}
function parseAftermath(card={}){let {card:c,faces}=cardFaces(card);if(faces.length<2)return null;let face=faces.find(f=>keywordPresent(f,'Aftermath'));if(!face)return null;let faceId=String(face.id||faces.indexOf(face));return{faceId,face,castCard:faceCastCard(c,face,{phase104FaceId:faceId,phase104Mechanic:'aftermath'})}}

function publicObject(card={},playerId=0,id=''){let c=root.MTGDeckEngine?.normalizeCard?root.MTGDeckEngine.normalizeCard(card):clone(card),pc=root.MTGDeckEngine?.publicCardRecord?root.MTGDeckEngine.publicCardRecord(c):clone(c),oid=String(id||('altzone_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)));return{id:oid,stableObjectId:oid,name:String(c.n||c.name||'Card'),owner:Number(playerId),controllerId:Number(playerId),type:root.MTGDeckEngine?.primaryPermanentType?.(c.typeLine)||'Card',typeLine:String(c.typeLine||''),oracleText:String(c.oracleText||''),oracleId:c.oracleId||null,layout:String(c.layout||''),colors:Array.isArray(c.colors)?c.colors.slice():[],sub:Array.isArray(c.subtypes)?c.subtypes.slice():[],q:'1',c:{},token:0,phase100CardPublic:pc,faceDefinitions:clone(c.faces||[])}}
function zoneObject(state={},ref='',zone=''){return root.MTGCastPermissions?.zoneObject?.(state,ref,zone)||null}
function exactSnapshot(o={}){if(root.MTGLKI?.normalizeIdentity)root.MTGLKI.normalizeIdentity(o);return{objectId:String(o.id||''),stableObjectId:String(o.stableObjectId||o.id||''),incarnationId:String(o.incarnationId||'')}}
function makeRecord(state={},kind='',o={},spec={},event=null){normalizeState(state);let x=exactSnapshot(o),id=String(spec.id||('altzone:'+kind+':'+x.incarnationId)),r=normalizeRecord({...spec,id,kind,playerId:Number(spec.playerId??o.owner??o.controllerId??0),...x,zoneChangeId:String(o.zoneChangeId||''),createdSeq:Number(event?.seq||state.meta?.seq||0),createdTurn:Number(spec.createdTurn??state.turn??0)});state.alternateZoneCasting.records[id]=r;return r}
function recordByPermission(state={},permissionId=''){normalizeState(state);return Object.values(state.alternateZoneCasting.records).find(r=>String(r.permissionId||'')===String(permissionId||''))||null}
function recordForObject(state={},ref='',kind=null){normalizeState(state);let objects=[...(state.battle||[]),...(state.zones?.graveyard||[]),...(state.zones?.exile||[])];let o=objects.find(x=>String(x.id)===String(ref)||String(x.stableObjectId)===String(ref)||String(x.incarnationId)===String(ref));if(!o)return null;let x=exactSnapshot(o);return Object.values(state.alternateZoneCasting.records).find(r=>(!kind||r.kind===lc(kind))&&r.stableObjectId===x.stableObjectId&&r.incarnationId===x.incarnationId)||null}
function grantExact(state={},o={},spec={},event=null){return root.MTGCastPermissions?.grant?.(state,o,spec,event)||{ok:false,review:true,reason:'cast-permission-module-missing'}}
function prepareFlashback(state={},spec={},event=null){normalizeState(state);let playerId=Number(spec.playerId||event?.actorId||0),f=zoneObject(state,spec.objectId,'graveyard'),o=f?.object;if(!o)return{ok:false,review:true,reason:'flashback-card-not-in-graveyard'};let card=spec.cardPublic||o.phase100CardPublic||o,parsed=parseFlashback(card,spec.instanceIndex||0);if(!parsed)return{ok:false,review:true,reason:'flashback-definition-unresolved'};let g=grantExact(state,o,{kind:'flashback',playerId,allowedZone:'graveyard',allowedMode:'normal',alternativeCost:parsed.cost,timingPolicy:'normal',source:'flashback'},event);if(!g.ok)return g;let r=makeRecord(state,'flashback',o,{playerId,permissionId:g.record.id,alternativeCost:parsed.cost},event);g.record.phase103RecordId=r.id;return{ok:true,object:o,record:r,permission:g.record,parsed}}
function prepareEscape(state={},spec={},event=null){normalizeState(state);let playerId=Number(spec.playerId||event?.actorId||0),f=zoneObject(state,spec.objectId,'graveyard'),o=f?.object;if(!o)return{ok:false,review:true,reason:'escape-card-not-in-graveyard'};let card=spec.cardPublic||o.phase100CardPublic||o,parsed=parseEscape(card);if(!parsed)return{ok:false,review:true,reason:'escape-definition-unresolved'};let refs=Array.isArray(spec.paymentObjectIds)?spec.paymentObjectIds.map(String):[],pay=[];for(const ref of refs){let pf=zoneObject(state,ref,'graveyard'),po=pf?.object;if(!po||String(po.id)===String(o.id))return{ok:false,review:true,reason:'escape-payment-object-invalid'};pay.push(exactSnapshot(po))}let uniq=new Set(pay.map(x=>x.incarnationId));if(pay.length!==parsed.count||uniq.size!==parsed.count)return{ok:false,review:false,reason:'escape-payment-count-mismatch'};let g=grantExact(state,o,{kind:'escape',playerId,allowedZone:'graveyard',allowedMode:'normal',alternativeCost:parsed.cost,timingPolicy:'normal',source:'escape',escapePayment:clone(pay),escapeCount:parsed.count},event);if(!g.ok)return g;let r=makeRecord(state,'escape',o,{playerId,permissionId:g.record.id,alternativeCost:parsed.cost,escapeCount:parsed.count,escapePayment:pay},event);g.record.phase103RecordId=r.id;g.record.escapePayment=clone(pay);g.record.escapeCount=parsed.count;return{ok:true,object:o,record:r,permission:g.record,parsed}}
function prepareRetrace(state={},spec={},event=null){normalizeState(state);let playerId=Number(spec.playerId||event?.actorId||0),f=zoneObject(state,spec.objectId,'graveyard'),o=f?.object;if(!o)return{ok:false,review:true,reason:'retrace-card-not-in-graveyard'};let card=spec.cardPublic||o.phase100CardPublic||o,parsed=parseRetrace(card);if(!parsed)return{ok:false,review:true,reason:'retrace-definition-unresolved'};let g=grantExact(state,o,{kind:'retrace',playerId,allowedZone:'graveyard',allowedMode:'normal',timingPolicy:'normal',requiredAdditionalCost:clone(parsed.requiredAdditionalCost),source:'retrace'},event);if(!g.ok)return g;let r=makeRecord(state,'retrace',o,{playerId,permissionId:g.record.id,requiredAdditionalCost:clone(parsed.requiredAdditionalCost)},event);g.record.phase103RecordId=r.id;return{ok:true,object:o,record:r,permission:g.record,parsed,castCard:card}}
function prepareJumpStart(state={},spec={},event=null){normalizeState(state);let playerId=Number(spec.playerId||event?.actorId||0),f=zoneObject(state,spec.objectId,'graveyard'),o=f?.object;if(!o)return{ok:false,review:true,reason:'jump-start-card-not-in-graveyard'};let card=spec.cardPublic||o.phase100CardPublic||o,parsed=parseJumpStart(card);if(!parsed)return{ok:false,review:true,reason:'jump-start-definition-unresolved'};let g=grantExact(state,o,{kind:'jump-start',playerId,allowedZone:'graveyard',allowedMode:'normal',timingPolicy:'normal',requiredAdditionalCost:clone(parsed.requiredAdditionalCost),source:'jump-start'},event);if(!g.ok)return g;let r=makeRecord(state,'jump-start',o,{playerId,permissionId:g.record.id,requiredAdditionalCost:clone(parsed.requiredAdditionalCost)},event);g.record.phase103RecordId=r.id;return{ok:true,object:o,record:r,permission:g.record,parsed,castCard:card}}
function prepareAftermath(state={},spec={},event=null){normalizeState(state);let playerId=Number(spec.playerId||event?.actorId||0),f=zoneObject(state,spec.objectId,'graveyard'),o=f?.object;if(!o)return{ok:false,review:true,reason:'aftermath-card-not-in-graveyard'};let rootCard=spec.cardPublic||o.phase100CardPublic||o,parsed=parseAftermath(rootCard);if(!parsed)return{ok:false,review:true,reason:'aftermath-definition-unresolved'};let g=grantExact(state,o,{kind:'aftermath',playerId,allowedZone:'graveyard',allowedMode:'normal',timingPolicy:'normal',expectedCardName:parsed.castCard.n,expectedFaceId:parsed.faceId,faceId:parsed.faceId,source:'aftermath'},event);if(!g.ok)return g;let r=makeRecord(state,'aftermath',o,{playerId,permissionId:g.record.id,expectedCardName:parsed.castCard.n,expectedFaceId:parsed.faceId},event);g.record.phase103RecordId=r.id;return{ok:true,object:o,record:r,permission:g.record,parsed,castCard:parsed.castCard}}
function prepareDisturb(state={},spec={},event=null){normalizeState(state);let playerId=Number(spec.playerId||event?.actorId||0),f=zoneObject(state,spec.objectId,'graveyard'),o=f?.object;if(!o)return{ok:false,review:true,reason:'disturb-card-not-in-graveyard'};let rootCard=spec.cardPublic||o.phase100CardPublic||o,parsed=parseDisturb(rootCard);if(!parsed)return{ok:false,review:true,reason:'disturb-definition-unresolved'};let g=grantExact(state,o,{kind:'disturb',playerId,allowedZone:'graveyard',allowedMode:'normal',alternativeCost:parsed.cost,timingPolicy:'normal',expectedCardName:parsed.castCard.n,expectedFaceId:parsed.backFaceId,faceId:parsed.backFaceId,castTransformed:true,source:'disturb'},event);if(!g.ok)return g;let r=makeRecord(state,'disturb',o,{playerId,permissionId:g.record.id,alternativeCost:parsed.cost,expectedCardName:parsed.castCard.n,expectedFaceId:parsed.backFaceId,castTransformed:true},event);g.record.phase103RecordId=r.id;return{ok:true,object:o,record:r,permission:g.record,parsed,castCard:parsed.castCard}}
function validatePermissionCard(permission={},card={}){let k=lc(permission.kind||'');if(!['disturb','aftermath'].includes(k))return{ok:true};let expected=lc(permission.expectedCardName||''),actual=lc(card.n||card.name||'');if(!expected||!actual||expected!==actual)return{ok:false,review:false,reason:k+'-cast-face-mismatch'};return{ok:true}}
function cardForPermission(o={},permission={}){let k=lc(permission.kind||''),rootCard=o.phase100CardPublic||null;if(!rootCard||!['disturb','aftermath'].includes(k))return null;let parsed=k==='disturb'?parseDisturb(rootCard):parseAftermath(rootCard);return parsed?.castCard||null}

function validateEscapePayment(state={},permission={},sourceRef=''){if(String(permission.kind||'')!=='escape')return{ok:true,actions:[]};let rec=recordByPermission(state,permission.id);if(permission.escapePaymentCommitted===true||rec?.escapePaymentCommitted===true)return{ok:true,actions:[],committed:true};let pay=Array.isArray(permission.escapePayment)?permission.escapePayment:rec?.escapePayment||[],count=Math.max(0,Number(permission.escapeCount??rec?.escapeCount??0));if(pay.length!==count)return{ok:false,review:true,reason:'escape-payment-record-mismatch'};let seen=new Set(),actions=[];for(const x of pay){if(seen.has(x.incarnationId))return{ok:false,review:true,reason:'escape-payment-duplicate'};seen.add(x.incarnationId);let f=zoneObject(state,x.objectId,'graveyard'),o=f?.object;if(!o)return{ok:false,review:false,reason:'escape-payment-card-left-graveyard'};let now=exactSnapshot(o);if(now.incarnationId!==String(x.incarnationId)||now.stableObjectId!==String(x.stableObjectId)||String(o.id)===String(sourceRef))return{ok:false,review:false,reason:'escape-payment-incarnation-changed'};actions.push({type:'OBJECT_ZONE_CHANGED',payload:{objectId:o.id,toZone:'exile',reset:true}})}return{ok:true,actions}}
function castPaymentActions(state={},permissionId='',sourceRef=''){normalizeState(state);let p=state.castPermissions?.records?.[String(permissionId||'')];if(!p)return{ok:true,actions:[]};return validateEscapePayment(state,p,sourceRef)}
function markEscapePaymentCommitted(state={},permissionId='',event=null){normalizeState(state);let pid=String(permissionId||''),p=state.castPermissions?.records?.[pid];if(!p||String(p.kind||'')!=='escape')return{ok:false,review:true,reason:'escape-permission-not-found'};let r=recordByPermission(state,pid);if(!r||r.kind!=='escape')return{ok:false,review:true,reason:'escape-record-not-found'};p.escapePaymentCommitted=true;p.escapePaymentCommittedSeq=Number(event?.seq||state.meta?.seq||0);r.escapePaymentCommitted=true;r.escapePaymentCommittedSeq=p.escapePaymentCommittedSeq;return{ok:true,permission:p,record:r}}
function discardMadness(state={},spec={},event=null){normalizeState(state);let playerId=Number(spec.playerId||event?.actorId||0),card=spec.cardPublic||{},parsed=parseMadness(card,spec.instanceIndex||0);if(!parsed)return{ok:false,review:true,reason:'madness-definition-unresolved'};let o=publicObject(card,playerId,spec.objectId);if(root.MTGLKI?.nextIncarnation)root.MTGLKI.nextIncarnation(o,event,'exile');state.zones??={};state.zones.exile??=[];state.zones.exile.push(o);let r=makeRecord(state,'madness',o,{playerId,alternativeCost:parsed.cost},event);o.phase103Madness={recordId:r.id,discarded:true};return{ok:true,object:o,record:r,parsed,countsAsDiscard:true}}
function madnessCandidates(state={},event={}){let r=event?.phase103Result?.record;if(!r||r.kind!=='madness'||!r.active)return[];return[{item:{id:'stack_madness_'+String(r.id).replace(/[^A-Za-z0-9_-]/g,'_')+'_'+String(event.seq||0),kind:'trigger-group',name:'Madness — cast discarded card',count:'1',controllerId:r.playerId,sourceObjectId:r.objectId,targets:[],effect:{type:'phase103-madness-cast',recordId:r.id,objectId:r.objectId,optional:true},oracleText:'When this card is discarded into exile for madness, you may cast it for its madness cost. If you do not, put it into your graveyard.',triggerEvent:'MADNESS_DISCARD',rulesProfileVersion:VERSION},baseCount:'1',modifiers:[]}]}
function grantMadnessPermission(state={},spec={},event=null){normalizeState(state);let r=state.alternateZoneCasting.records[String(spec.recordId||'')];if(!r||r.kind!=='madness'||!r.active)return{ok:false,review:false,reason:'madness-window-inactive'};let f=zoneObject(state,spec.objectId||r.objectId,'exile'),o=f?.object;if(!o||exactSnapshot(o).incarnationId!==r.incarnationId)return{ok:false,review:false,reason:'madness-card-left-exile'};let g=grantExact(state,o,{kind:'madness',playerId:r.playerId,allowedZone:'exile',allowedMode:'normal',alternativeCost:r.alternativeCost,timingOverride:true,timingPolicy:'normal',source:'madness-trigger'},event);if(!g.ok)return g;r.permissionId=g.record.id;g.record.phase103RecordId=r.id;return{ok:true,record:r,object:o,permission:g.record}}
function internalCastAllowed(state={},playerId=0,objectRef='',permissionId=''){let r=recordByPermission(state,permissionId);if(!r||!['madness','rebound'].includes(r.kind)||!r.active||r.playerId!==Number(playerId))return false;return !!root.MTGCastPermissions?.validateCast?.(state,playerId,objectRef,{permissionId,fromZone:'exile',mode:'normal'})?.ok}
function moveExact(state={},o={},zone='',event=null){let ex=(state.zones?.exile||[]),i=ex.findIndex(x=>String(x.id)===String(o.id)&&String(x.incarnationId||'')===String(o.incarnationId||''));if(i<0)return null;let x=ex.splice(i,1)[0];if(root.MTGLKI?.nextIncarnation)root.MTGLKI.nextIncarnation(x,event,zone);x.tapped=false;x.controllerId=Number(x.owner)||x.controllerId;x.c={};state.zones[zone]??=[];state.zones[zone].push(x);root.MTGCastPermissions?.onZoneChange?.(state,x,event);return x}
function declineMadness(state={},recordId='',event=null){normalizeState(state);let r=state.alternateZoneCasting.records[String(recordId||'')];if(!r||r.kind!=='madness'||!r.active)return{ok:false,ignored:true};let f=zoneObject(state,r.objectId,'exile'),o=f?.object;if(!o)return{ok:false,ignored:true};let moved=moveExact(state,o,'graveyard',event);r.active=false;r.declined=true;r.declinedSeq=Number(event?.seq||state.meta?.seq||0);if(r.permissionId)root.MTGCastPermissions?.revoke?.(state,r.permissionId,event,'madness-declined');return{ok:!!moved,object:moved,record:r}}
function markMadnessCountered(state={},recordId='',event=null){normalizeState(state);let r=state.alternateZoneCasting.records[String(recordId||'')];if(!r||r.kind!=='madness')return{ok:false,ignored:true};r.active=false;r.triggerCountered=true;r.counteredSeq=Number(event?.seq||state.meta?.seq||0);if(r.permissionId)root.MTGCastPermissions?.revoke?.(state,r.permissionId,event,'madness-trigger-countered');return{ok:true,record:r}}
function warpPermission(card={},playerId=0){let p=parseWarp(card);return p?{kind:'phase103-warp-hand',allowFromZone:false,timingOverride:false,withoutManaCost:false,xMustBeZero:false,alternativeCost:p.cost,timingPolicy:'normal',phase103Warp:true,playerId:Number(playerId)}:null}
function commitSyntheticStackItem(state={},item={},event=null){if(item.isSpellCopy||item.phase100CardObject)return{ok:true,ignored:true};if(item.phase103Cast?.kind==='warp'){let parsed=parseWarp(item.publicCard||{});if(!parsed||String(item.phase103Cast.cost||'')!==parsed.cost)return{ok:false,review:true,reason:'warp-stack-definition-mismatch'};let o=publicObject(item.publicCard||{},item.controllerId,'warp_'+String(item.id||Date.now()).replace(/[^A-Za-z0-9_-]/g,'_'));if(root.MTGLKI?.nextIncarnation)root.MTGLKI.nextIncarnation(o,event,'stack');item.phase100CardObject=clone(o);item.phase103Cast={kind:'warp',cost:parsed.cost,castTurn:Number(state.turn||0),initial:true};return{ok:true,tracked:true,object:o}}if(lc(item.fromZone)==='hand'&&parseRebound(item.publicCard||{})){let o=publicObject(item.publicCard||{},item.controllerId,'rebound_'+String(item.id||Date.now()).replace(/[^A-Za-z0-9_-]/g,'_'));if(root.MTGLKI?.nextIncarnation)root.MTGLKI.nextIncarnation(o,event,'stack');item.phase100CardObject=clone(o);item.phase104ReboundOrigin={fromHand:true,castTurn:Number(state.turn||0),playerId:Number(item.controllerId||o.owner)};return{ok:true,tracked:true,rebound:true,object:o}}return{ok:true,ignored:true}}
function decoratePermanentFromStack(item={},o={}){if(item.phase103Cast?.kind==='warp'){o.phase103Warp={kind:'warp',cost:String(item.phase103Cast.cost||''),castTurn:Number(item.phase103Cast.castTurn||0),controllerId:Number(item.controllerId||o.controllerId||o.owner)};return o}if(item.phase103Cast?.kind==='disturb'){let faceId=String(item.phase103Cast.expectedFaceId||item.phase100PermissionRecord?.expectedFaceId||'');if(faceId&&root.MTGCardForms?.applyFace){let r=root.MTGCardForms.applyFace(o,faceId,null,{orientation:faceId});if(r?.ok)o.phase104Disturb={recordId:item.phase103Cast.recordId||null,backFaceId:faceId,enteredBackFaceUp:true}}return o}return o}
function onPermanentAdded(state={},o={},event=null){normalizeState(state);if(!o?.phase103Warp||o.phase103Warp.kind!=='warp')return{ok:true,ignored:true};let r=makeRecord(state,'warp',o,{playerId:Number(o.controllerId||o.owner),alternativeCost:String(o.phase103Warp.cost||''),createdTurn:Number(o.phase103Warp.castTurn||state.turn||0)},event);o.phase103Warp={...o.phase103Warp,recordId:r.id};return{ok:true,record:r,object:o}}
function warpCandidates(state={}){normalizeState(state);let out=[];for(const r of Object.values(state.alternateZoneCasting.records)){if(r.kind!=='warp'||!r.active||r.triggered||r.triggerCountered||r.futurePermissionGranted)continue;let o=(state.battle||[]).find(x=>String(x.stableObjectId||x.id)===r.stableObjectId&&String(x.incarnationId||'')===r.incarnationId);if(!o)continue;out.push({item:{id:'stack_warp_'+String(r.id).replace(/[^A-Za-z0-9_-]/g,'_')+'_'+String(state.meta?.seq||0),kind:'trigger-group',name:'Warp — exile this permanent',count:'1',controllerId:r.playerId,sourceObjectId:o.id,targets:[],effect:{type:'phase103-warp-exile',recordId:r.id,objectId:o.id},oracleText:'At the beginning of the next end step, exile this permanent. Then its owner may cast it from exile on a later turn.',triggerEvent:'END_STEP_BEGIN',rulesProfileVersion:VERSION},baseCount:'1',modifiers:[]})}return out}
function markWarpTriggered(state={},recordId='',event=null){normalizeState(state);let r=state.alternateZoneCasting.records[String(recordId||'')];if(!r||r.kind!=='warp')return{ok:false,ignored:true};r.triggered=true;r.triggeredSeq=Number(event?.seq||state.meta?.seq||0);return{ok:true,record:r}}
function markWarpTriggerCountered(state={},recordId='',event=null){let x=markWarpTriggered(state,recordId,event);if(!x.ok)return x;x.record.active=false;x.record.triggerCountered=true;return x}
function grantWarpFuturePermission(state={},spec={},event=null){normalizeState(state);let r=state.alternateZoneCasting.records[String(spec.recordId||'')];if(!r||r.kind!=='warp')return{ok:false,review:true,reason:'warp-record-missing'};if(!r.triggered||r.triggerCountered||r.leftBattlefield)return{ok:false,review:false,reason:'warp-trigger-no-longer-authorizes-cast'};let f=zoneObject(state,spec.objectId||r.stableObjectId,'exile'),o=f?.object;if(!o||String(o.stableObjectId||o.id)!==r.stableObjectId)return{ok:false,review:false,reason:'warp-card-not-in-exile'};if(r.warpExileIncarnationId&&String(o.incarnationId||'')!==String(r.warpExileIncarnationId))return{ok:false,review:false,reason:'warp-exile-incarnation-mismatch'};let g=grantExact(state,o,{kind:'warp-future',playerId:Number(o.owner||r.playerId),allowedZone:'exile',allowedMode:'normal',notBeforeTurn:Number(state.turn||0)+1,timingPolicy:'normal',source:'warp-delayed-trigger'},event);if(!g.ok)return g;r.active=false;r.futurePermissionGranted=true;r.permissionId=g.record.id;r.exileIncarnationId=String(o.incarnationId||'');g.record.phase103RecordId=r.id;return{ok:true,record:r,object:o,permission:g.record}}
function onCastCommitted(state={},o={},permission={},item=null,event=null){normalizeState(state);let r=recordByPermission(state,permission.id);if(!r)return{ok:true,ignored:true};r.active=false;r.cast=true;r.consumed=true;r.castSeq=Number(event?.seq||state.meta?.seq||0);if(item)item.phase103Cast={kind:r.kind,recordId:r.id,expectedCardName:r.expectedCardName||null,expectedFaceId:r.expectedFaceId||null,castTransformed:!!r.castTransformed};return{ok:true,record:r}}
function stackExitDestination(item={},reason=''){let k=lc(item.phase100PermissionRecord?.kind||item.phase103Cast?.kind||''),why=lc(reason);if(['flashback','jump-start','aftermath'].includes(k))return'exile';if(item.phase104ReboundOrigin?.fromHand&&why==='resolved')return'exile';if(why==='exiled')return'exile';return'graveyard'}
function onTrackedResolved(state={},item={},moved={},event=null){normalizeState(state);if(!item?.phase104ReboundOrigin?.fromHand||lc(moved.zone)!=='exile')return{ok:true,ignored:true};let r=makeRecord(state,'rebound',moved,{playerId:Number(item.phase104ReboundOrigin.playerId||item.controllerId||moved.owner),createdTurn:Number(item.phase104ReboundOrigin.castTurn??state.turn??0),reboundResolvedSeq:Number(event?.seq||state.meta?.seq||0)},event);moved.phase104Rebound={recordId:r.id,waitingForNextUpkeep:true};return{ok:true,record:r,object:moved}}
function reboundCandidates(state={},activePlayerId=0){normalizeState(state);let active=Number(activePlayerId||state.active||0),turn=Number(state.turn||0),out=[];for(const r of Object.values(state.alternateZoneCasting.records)){if(r.kind!=='rebound'||!r.active||r.triggered||r.triggerCountered||r.declined||r.cast||r.playerId!==active||turn<=Number(r.createdTurn||0))continue;let f=zoneObject(state,r.objectId,'exile'),o=f?.object;if(!o||exactSnapshot(o).incarnationId!==r.incarnationId)continue;out.push({item:{id:'stack_rebound_'+String(r.id).replace(/[^A-Za-z0-9_-]/g,'_')+'_'+String(state.meta?.seq||0),kind:'trigger-group',name:'Rebound — cast from exile',count:'1',controllerId:r.playerId,sourceObjectId:o.id,targets:[],effect:{type:'phase104-rebound-cast',recordId:r.id,objectId:o.id,optional:true},oracleText:'At the beginning of your next upkeep, you may cast this card from exile without paying its mana cost.',triggerEvent:'UPKEEP_BEGIN',rulesProfileVersion:VERSION},baseCount:'1',modifiers:[]})}return out}
function markReboundTriggered(state={},recordId='',event=null){normalizeState(state);let r=state.alternateZoneCasting.records[String(recordId||'')];if(!r||r.kind!=='rebound'||!r.active)return{ok:false,ignored:true};r.triggered=true;r.reboundTriggered=true;r.triggeredSeq=Number(event?.seq||state.meta?.seq||0);return{ok:true,record:r}}
function grantReboundPermission(state={},spec={},event=null){normalizeState(state);let r=state.alternateZoneCasting.records[String(spec.recordId||'')];if(!r||r.kind!=='rebound'||!r.active||!r.triggered||r.triggerCountered||r.declined)return{ok:false,review:false,reason:'rebound-window-inactive'};let f=zoneObject(state,spec.objectId||r.objectId,'exile'),o=f?.object;if(!o||exactSnapshot(o).incarnationId!==r.incarnationId)return{ok:false,review:false,reason:'rebound-card-left-exile'};let g=grantExact(state,o,{kind:'rebound',playerId:r.playerId,allowedZone:'exile',allowedMode:'normal',withoutManaCost:true,xMustBeZero:true,timingOverride:true,timingPolicy:'normal',source:'rebound-trigger'},event);if(!g.ok)return g;r.permissionId=g.record.id;g.record.phase103RecordId=r.id;return{ok:true,record:r,object:o,permission:g.record}}
function declineRebound(state={},recordId='',event=null){normalizeState(state);let r=state.alternateZoneCasting.records[String(recordId||'')];if(!r||r.kind!=='rebound'||!r.active)return{ok:false,ignored:true};r.active=false;r.declined=true;r.declinedSeq=Number(event?.seq||state.meta?.seq||0);if(r.permissionId)root.MTGCastPermissions?.revoke?.(state,r.permissionId,event,'rebound-declined');return{ok:true,record:r}}
function markReboundTriggerCountered(state={},recordId='',event=null){normalizeState(state);let r=state.alternateZoneCasting.records[String(recordId||'')];if(!r||r.kind!=='rebound')return{ok:false,ignored:true};r.active=false;r.triggered=true;r.reboundTriggered=true;r.triggerCountered=true;r.counteredSeq=Number(event?.seq||state.meta?.seq||0);if(r.permissionId)root.MTGCastPermissions?.revoke?.(state,r.permissionId,event,'rebound-trigger-countered');return{ok:true,record:r}}

function onZoneChange(state={},o={},event=null){normalizeState(state);let sid=String(o.stableObjectId||o.id||''),inc=String(o.incarnationId||''),invalidated=[];for(const r of Object.values(state.alternateZoneCasting.records)){if(!r.active)continue;if(r.stableObjectId===sid&&r.incarnationId!==inc){if(r.kind==='warp'&&r.triggered){if(String(event?.source||'')==='phase103-warp'){r.warpExileIncarnationId=inc;r.warpExileSeq=Number(event?.seq||state.meta?.seq||0);continue}r.leftBattlefield=true;r.leftSeq=Number(event?.seq||state.meta?.seq||0);continue}r.active=false;r.invalidated=true;r.invalidatedSeq=Number(event?.seq||state.meta?.seq||0);if(r.permissionId)root.MTGCastPermissions?.revoke?.(state,r.permissionId,event,'phase103-object-changed-zone');invalidated.push(r.id)}}return{ok:true,invalidated}}
function statusLabel(state={},o={},zone=''){let z=lc(zone||o.zone||''),r=recordForObject(state,o.id);if(r){if(r.kind==='madness'&&z==='exile')return r.triggerCountered?'MADNESS · TRIGGER COUNTERED':'MADNESS · CAST WINDOW';if(r.kind==='rebound'&&z==='exile')return r.triggerCountered?'REBOUND · TRIGGER COUNTERED':r.triggered?'REBOUND · CAST WINDOW':'REBOUND · NEXT UPKEEP';if(r.kind==='warp'&&z==='battlefield')return'WARPED · NEXT END STEP'}let perms=root.MTGCastPermissions?.exactPermissions?.(state,Number(o.owner||o.controllerId||0),o.id,{fromZone:z})||[];let p=perms.find(x=>['flashback','escape','disturb','retrace','jump-start','aftermath','rebound','warp-future','madness'].includes(x.kind));if(!p)return'';if(p.kind==='flashback')return'FLASHBACK READY';if(p.kind==='escape')return'ESCAPE READY';if(p.kind==='disturb')return'DISTURB READY';if(p.kind==='retrace')return'RETRACE READY';if(p.kind==='jump-start')return'JUMP-START READY';if(p.kind==='aftermath')return'AFTERMATH READY';if(p.kind==='rebound')return'REBOUND · CAST READY';if(p.kind==='warp-future')return Number(state.turn||0)<Number(p.notBeforeTurn||0)?'WARP · CAST NEXT TURN':'WARP · CAST READY';if(p.kind==='madness')return'MADNESS · CAST READY';return''}
function localQA(engine){
 let c=[],q=(n,v)=>c.push([n,!!v]);
 const fb={n:'Think Twice',manaCost:'{1}{U}',typeLine:'Instant',oracleText:'Draw a card.\nFlashback {2}{U}',resolved:true};
 const esc={n:'Escape Test',manaCost:'{2}{B}',typeLine:'Creature — Zombie',oracleText:'Escape—{3}{B}, Exile three other cards from your graveyard.',resolved:true};
 const mad={n:'Fiery Temper',manaCost:'{1}{R}{R}',typeLine:'Instant',oracleText:'Fiery Temper deals 3 damage to any target.\nMadness {R}',resolved:true};
 const warp={n:'Warp Test',manaCost:'{4}{U}',typeLine:'Creature — Alien',oracleText:'Flying\nWarp {1}{U}',resolved:true};
 const retrace={n:"Raven's Crime",manaCost:'{B}',typeLine:'Sorcery',oracleText:'Target player discards a card.\nRetrace',keywords:['Retrace'],resolved:true};
 const jump={n:"Chemister's Insight",manaCost:'{3}{U}',typeLine:'Instant',oracleText:'Draw two cards.\nJump-start',keywords:['Jump-start'],resolved:true};
 const aftermath={n:'Never // Return',layout:'split',faces:[{id:'never',name:'Never',manaCost:'{1}{B}{B}',typeLine:'Sorcery',oracleText:'Destroy target creature or planeswalker.',keywords:[]},{id:'return',name:'Return',manaCost:'{3}{B}',typeLine:'Sorcery',oracleText:'Aftermath\nExile target card from a graveyard. Create a 2/2 black Zombie creature token.',keywords:['Aftermath']}],resolved:true};
 const disturb={n:'Hermit // Geist',layout:'transform',faces:[{id:'front',name:'Malevolent Hermit',manaCost:'{1}{U}',typeLine:'Creature — Human Wizard',oracleText:'Disturb {2}{U}',keywords:['Disturb']},{id:'back',name:'Benevolent Geist',manaCost:'',typeLine:'Creature — Spirit Wizard',oracleText:'Flying',keywords:['Flying']}],resolved:true};
 const rebound={n:'Staggershock',manaCost:'{2}{R}',typeLine:'Instant',oracleText:'Staggershock deals 2 damage to any target.\nRebound',keywords:['Rebound'],resolved:true};
 q('Flashback parser extracts exact alternate mana cost',parseFlashback(fb)?.cost==='{2}{U}');
 q('Escape parser extracts mana plus exact other-card count',parseEscape(esc)?.cost==='{3}{B}'&&parseEscape(esc)?.count===3);
 q('Madness parser extracts alternate mana cost',parseMadness(mad)?.cost==='{R}');
 q('Warp parser extracts alternate mana cost',parseWarp(warp)?.cost==='{1}{U}');q('Warp parser rejects nonpermanent cards',parseWarp({typeLine:'Instant',oracleText:'Warp {1}'})===null);
 q('Retrace parser recognizes graveyard cast with land discard',parseRetrace(retrace)?.requiredAdditionalCost?.cardType==='Land');
 q('Jump-start parser recognizes graveyard cast with card discard',parseJumpStart(jump)?.requiredAdditionalCost?.kind==='discard');
 q('Aftermath parser selects only the Aftermath half',parseAftermath(aftermath)?.castCard?.n==='Return');
 q('Disturb parser selects back face and alternate mana cost',parseDisturb(disturb)?.castCard?.n==='Benevolent Geist'&&parseDisturb(disturb)?.cost==='{2}{U}');
 q('Rebound parser recognizes instant/sorcery only',parseRebound(rebound)?.rebound===true&&!parseRebound({typeLine:'Creature',oracleText:'Rebound'}));
 q('unsupported variable Escape text is not guessed',parseEscape({oracleText:'Escape—{X}, Exile X other cards from your graveyard.'})===null);
 if(!engine)return{ok:false,checks:[...c,['engine supplied',false]]};
 const seed=(id,name)=>({id,stableObjectId:id,name,owner:1,controllerId:1,typeLine:'Card',q:'1',c:{}});
 const base=()=>engine.normalizeState({life:{1:40,2:40},battle:[],stack:[],zones:{exile:[],graveyard:[],hand:[],command:[]},events:[],snapshots:[],feed:[],active:1,priority:1,turn:5,phase:'MAIN 1'});
 let fs=base(),fo=seed('fb','Think Twice');fo.phase100CardPublic=fb;root.MTGLKI?.nextIncarnation?.(fo,{seq:1,id:'seed'},'graveyard');fs.zones.graveyard.push(fo);let fr=prepareFlashback(fs,{playerId:1,objectId:fo.id,cardPublic:fb},{seq:2,id:'fb'});
 q('Flashback binds permission to exact graveyard incarnation',fr.ok&&fr.permission?.kind==='flashback'&&fr.permission.incarnationId===fo.incarnationId);
 q('Flashback bridge keeps normal timing and alternate cost',root.MTGCastPermissions.bridgePermission(fr.permission).alternativeCost==='{2}{U}'&&!root.MTGCastPermissions.bridgePermission(fr.permission).timingOverride);
 let fi={id:'fspell',kind:'spell',controllerId:1,fromZone:'graveyard',zoneObjectId:fo.id,phase100PermissionId:fr.permission.id,publicCard:fb};let fc=root.MTGCastPermissions.commitStackItem(fs,fi,{seq:3,id:'cast'});
 q('Flashback exact card becomes a tracked stack incarnation',fc.ok&&fi.phase100CardObject?.zone==='stack');
 let hx=root.MTGCastPermissions.handleStackExit(fs,fi,'countered',{seq:4,id:'counter'});
 q('Flashback countered spell is exiled instead of graveyard',hx.ok&&hx.destination==='exile'&&fs.zones.exile.some(x=>x.stableObjectId==='fb'));
 let es=base();for(let i=0;i<5;i++){let o=seed('g'+i,'G'+i);root.MTGLKI?.nextIncarnation?.(o,{seq:10+i,id:'g'},'graveyard');es.zones.graveyard.push(o)}let source=es.zones.graveyard[0];source.phase100CardPublic=esc;let er=prepareEscape(es,{playerId:1,objectId:source.id,cardPublic:esc,paymentObjectIds:['g1','g2','g3']},{seq:20,id:'escape'});
 q('Escape permission stores exact distinct payment incarnations',er.ok&&er.record.escapePayment.length===3&&new Set(er.record.escapePayment.map(x=>x.incarnationId)).size===3);
 q('Escape rejects selecting the source as an other-card payment',prepareEscape(es,{playerId:1,objectId:source.id,cardPublic:esc,paymentObjectIds:['g0','g2','g3']},{seq:21,id:'bad'}).ok===false);
 let ep=validateEscapePayment(es,er.permission,source.id);q('Escape revalidates every payment card immediately before cast',ep.ok&&ep.actions.length===3);
 engine.dispatch(es,'OBJECT_ZONE_CHANGED',{objectId:'g2',toZone:'exile'},1,{source:'qa'});q('Escape payment becomes illegal if one selected incarnation moved',validateEscapePayment(es,er.permission,source.id).ok===false);
 let ecs=base();for(let i=0;i<4;i++){let o=seed('ec'+i,'EC'+i);root.MTGLKI?.nextIncarnation?.(o,{seq:60+i,id:'ec'},'graveyard');ecs.zones.graveyard.push(o)}let ecsource=ecs.zones.graveyard[0];ecsource.phase100CardPublic=esc;let ecr=prepareEscape(ecs,{playerId:1,objectId:ecsource.id,cardPublic:esc,paymentObjectIds:['ec1','ec2','ec3']},{seq:65,id:'escape-prepare'}),eca=castPaymentActions(ecs,ecr.permission.id,ecsource.id);for(const a of eca.actions)engine.dispatch(ecs,a.type,a.payload,1,{source:'qa'});let ecm=markEscapePaymentCommitted(ecs,ecr.permission.id,{seq:70,id:'escape-paid'}),eci={id:'escape-stack-qa',kind:'spell',name:'Escape Source',controllerId:1,fromZone:'graveyard',zoneObjectId:ecsource.id,phase100PermissionId:ecr.permission.id,phase100CastMode:'normal',publicCard:esc},ecc=root.MTGCastPermissions.commitStackItem(ecs,eci,{seq:71,id:'escape-stack'});q('Escape payment commit boundary allows source cast after payment cards leave graveyard',ecm.ok&&validateEscapePayment(ecs,ecr.permission,ecsource.id).committed===true&&ecc.ok&&ecc.tracked===true);
 let ms=base(),md=discardMadness(ms,{playerId:1,objectId:'m1',cardPublic:mad},{seq:30,id:'discard'}),mo=ms.zones.exile[0];
 q('Madness discard replaces graveyard move with exact exile object',md.ok&&mo?.name==='Fiery Temper'&&md.countsAsDiscard);
 let mc=madnessCandidates(ms,{phase103Result:md,seq:30});q('Madness creates a separate optional cast trigger',mc.length===1&&mc[0].item.effect.type==='phase103-madness-cast'&&mc[0].item.effect.optional);
 let mg=grantMadnessPermission(ms,{recordId:md.record.id,objectId:mo.id},{seq:31,id:'grant'});q('Madness trigger grants exact temporary exile permission',mg.ok&&mg.permission.timingOverride&&mg.permission.alternativeCost==='{R}');
 q('Madness internal cast bypass is exact-player and exact-permission gated',internalCastAllowed(ms,1,mo.id,mg.permission.id)&&!internalCastAllowed(ms,2,mo.id,mg.permission.id));
 let md2=base(),m2=discardMadness(md2,{playerId:1,objectId:'m2',cardPublic:mad},{seq:32,id:'d2'});declineMadness(md2,m2.record.id,{seq:33,id:'decline'});q('declined Madness moves exact card from exile to graveyard',m2.record.declined&&md2.zones.graveyard.some(x=>x.stableObjectId==='m2'));
 let md3=base(),m3=discardMadness(md3,{playerId:1,objectId:'m3',cardPublic:mad},{seq:34,id:'d3'});markMadnessCountered(md3,m3.record.id,{seq:35,id:'ctr'});q('countered Madness trigger leaves card exiled with no later cast window',m3.record.triggerCountered&&md3.zones.exile.some(x=>x.stableObjectId==='m3')&&!Object.values(md3.castPermissions.records).some(x=>x.active));
 let wp=warpPermission(warp,1);q('Warp hand cast supplies trusted alternative cost without timing override',wp?.alternativeCost==='{1}{U}'&&!wp.timingOverride);
 let ws=base(),wi={id:'wspell',kind:'spell',controllerId:1,publicCard:warp,phase103Cast:{kind:'warp',cost:'{1}{U}'}};let wc=commitSyntheticStackItem(ws,wi,{seq:40,id:'wcast'}),perm=root.MTGCastPermissions.permanentFromStack(wi);root.MTGLKI?.nextIncarnation?.(perm,{seq:41,id:'enter'},'battlefield');ws.battle.push(perm);let wr=onPermanentAdded(ws,perm,{seq:41,id:'enter'});
 q('Warp cast creates tracked physical stack card then battlefield record',wc.ok&&wr.ok&&wr.record.incarnationId===perm.incarnationId);
 let wcs=warpCandidates(ws);q('Warp schedules a distinct next-end-step trigger',wcs.length===1&&wcs[0].item.effect.type==='phase103-warp-exile');
 markWarpTriggered(ws,wr.record.id,{seq:42,id:'trig'});let bi=ws.battle.findIndex(x=>x.id===perm.id),wo=ws.battle.splice(bi,1)[0];let we={seq:43,id:'ex',source:'phase103-warp'};root.MTGLKI?.nextIncarnation?.(wo,we,'exile');ws.zones.exile.push(wo);onZoneChange(ws,wo,we);let wg=grantWarpFuturePermission(ws,{recordId:wr.record.id,objectId:wo.id},{seq:44,id:'grant'});
 q('resolved Warp trigger grants later-turn exact exile permission',wg.ok&&wg.permission.kind==='warp-future'&&wg.permission.notBeforeTurn===6&&wr.record.warpExileIncarnationId===wo.incarnationId);
 q('Warp future permission is blocked during same turn',root.MTGCastPermissions.validateCast(ws,1,wo.id,{permissionId:wg.permission.id,fromZone:'exile'}).reason==='cast-permission-not-yet-live');
 ws.turn=6;q('Warp future permission becomes live on later turn',root.MTGCastPermissions.validateCast(ws,1,wo.id,{permissionId:wg.permission.id,fromZone:'exile'}).ok);
 let wl=base(),wli={id:'wleave',kind:'spell',controllerId:1,publicCard:warp,phase103Cast:{kind:'warp',cost:'{1}{U}'}};commitSyntheticStackItem(wl,wli,{seq:80,id:'wlcast'});let wlp=root.MTGCastPermissions.permanentFromStack(wli);root.MTGLKI?.nextIncarnation?.(wlp,{seq:81,id:'wlenter'},'battlefield');wl.battle.push(wlp);let wlr=onPermanentAdded(wl,wlp,{seq:81,id:'wlenter'});markWarpTriggered(wl,wlr.record.id,{seq:82,id:'wltrigger'});let wlx=wl.battle.pop(),other={seq:83,id:'other-exile',source:'other-effect'};root.MTGLKI?.nextIncarnation?.(wlx,other,'exile');wl.zones.exile.push(wlx);onZoneChange(wl,wlx,other);q('Warp gives no future permission if permanent left battlefield another way',grantWarpFuturePermission(wl,{recordId:wlr.record.id,objectId:wlx.id},{seq:84,id:'badgrant'}).ok===false&&wlr.record.leftBattlefield===true);
 let wb=base(),wbi={id:'wbefore',kind:'spell',controllerId:1,publicCard:warp,phase103Cast:{kind:'warp',cost:'{1}{U}'}};commitSyntheticStackItem(wb,wbi,{seq:85,id:'wbcast'});let wbp=root.MTGCastPermissions.permanentFromStack(wbi);root.MTGLKI?.nextIncarnation?.(wbp,{seq:86,id:'wbenter'},'battlefield');wb.battle.push(wbp);let wbr=onPermanentAdded(wb,wbp,{seq:86,id:'wbenter'}),wbx=wb.battle.pop(),leave={seq:87,id:'leave',source:'other-effect'};root.MTGLKI?.nextIncarnation?.(wbx,leave,'graveyard');wb.zones.graveyard.push(wbx);onZoneChange(wb,wbx,leave);q('Warp schedules no end-step trigger after permanent already left battlefield',wbr.record.invalidated===true&&warpCandidates(wb).length===0);

 let rs=base(),ro=seed('rt','Retrace Card');ro.phase100CardPublic=retrace;root.MTGLKI?.nextIncarnation?.(ro,{seq:90,id:'rtseed'},'graveyard');rs.zones.graveyard.push(ro);let rr=prepareRetrace(rs,{playerId:1,objectId:ro.id,cardPublic:retrace},{seq:91,id:'rtprep'}),rb=root.MTGCastPermissions.bridgePermission(rr.permission),rp=root.MTGAdvancedCastingCosts?.createPending?.(rs,{playerId:1,name:retrace.n,cardPublic:retrace,fromZone:'graveyard',zoneObjectId:ro.id,castPermission:rb},[]);q('Retrace injects a private land-discard confirmation into Phase 91 cost flow',rr.ok&&rb.requiredAdditionalCost?.cardType==='Land'&&rp?.additionalCosts?.some(x=>x.kind==='discard'&&x.requiredCardType==='Land'&&x.privateConfirmation));
 let js=base(),jo=seed('js','Jump Card');jo.phase100CardPublic=jump;root.MTGLKI?.nextIncarnation?.(jo,{seq:92,id:'jsseed'},'graveyard');js.zones.graveyard.push(jo);let jr=prepareJumpStart(js,{playerId:1,objectId:jo.id,cardPublic:jump},{seq:93,id:'jsprep'}),ji={id:'jstack',kind:'spell',controllerId:1,fromZone:'graveyard',zoneObjectId:jo.id,phase100PermissionId:jr.permission.id,publicCard:jump};root.MTGCastPermissions.commitStackItem(js,ji,{seq:94,id:'jcast'});let jx=root.MTGCastPermissions.handleStackExit(js,ji,'countered',{seq:95,id:'jcounter'});q('Jump-start exiles the tracked card whenever it leaves the stack',jx.ok&&jx.destination==='exile'&&js.zones.exile.some(x=>x.stableObjectId==='js'));
 let as=base(),ao=seed('af','Aftermath Card');ao.phase100CardPublic=aftermath;root.MTGLKI?.nextIncarnation?.(ao,{seq:96,id:'afseed'},'graveyard');as.zones.graveyard.push(ao);let ar=prepareAftermath(as,{playerId:1,objectId:ao.id,cardPublic:aftermath},{seq:97,id:'afprep'});q('Aftermath permission exposes only its graveyard half',ar.ok&&ar.castCard.n==='Return'&&cardForPermission(ao,ar.permission)?.n==='Return');q('Aftermath rejects the wrong split-card half at commit preflight',validatePermissionCard(ar.permission,{n:'Never'}).ok===false);
 let ds=base(),do1=seed('ds','Disturb Card');do1.phase100CardPublic=disturb;root.MTGLKI?.nextIncarnation?.(do1,{seq:98,id:'dsseed'},'graveyard');ds.zones.graveyard.push(do1);let dr=prepareDisturb(ds,{playerId:1,objectId:do1.id,cardPublic:disturb},{seq:99,id:'dprep'}),di={id:'dstack',kind:'spell',controllerId:1,fromZone:'graveyard',zoneObjectId:do1.id,phase100PermissionId:dr.permission.id,publicCard:dr.castCard};let dc=root.MTGCastPermissions.commitStackItem(ds,di,{seq:100,id:'dcast'}),dp=root.MTGCastPermissions.permanentFromStack(di);q('Disturb casts the exact back face for its alternate cost',dc.ok&&di.phase103Cast?.kind==='disturb'&&dr.permission.alternativeCost==='{2}{U}');q('resolved Disturb permanent enters back face up through Phase 98 form engine',dp?.name==='Benevolent Geist'&&dp.phase104Disturb?.enteredBackFaceUp===true);
 let rbs=base(),rbi={id:'rbstack',kind:'spell',name:rebound.n,controllerId:1,fromZone:'hand',publicCard:rebound};let rbc=commitSyntheticStackItem(rbs,rbi,{seq:101,id:'rbcast'}),rbm=root.MTGCastPermissions.finishTrackedNonPermanent(rbs,rbi,{seq:102,id:'rbresolve'}),rbr=recordForObject(rbs,rbm.object?.id,'rebound');q('Rebound tracks only an original hand cast and exiles it on resolution',rbc.rebound===true&&rbm.destination==='exile'&&rbr?.kind==='rebound');rbs.turn=6;rbs.active=1;rbs.phase='UPKEEP';let rbcs=reboundCandidates(rbs,1);q('Rebound creates one optional cast trigger at the owner’s next upkeep',rbcs.length===1&&rbcs[0].item.effect.type==='phase104-rebound-cast'&&rbcs[0].item.effect.optional);markReboundTriggered(rbs,rbr.id,{seq:103,id:'rbtrig'});let rbg=grantReboundPermission(rbs,{recordId:rbr.id,objectId:rbm.object.id},{seq:104,id:'rbgrant'});q('Rebound trigger grants exact free-cast permission with X forced to zero',rbg.ok&&rbg.permission.withoutManaCost&&rbg.permission.xMustBeZero&&internalCastAllowed(rbs,1,rbm.object.id,rbg.permission.id));let rb2={id:'rbrecast',kind:'spell',controllerId:1,fromZone:'exile',zoneObjectId:rbm.object.id,phase100PermissionId:rbg.permission.id,publicCard:rebound};root.MTGCastPermissions.commitStackItem(rbs,rb2,{seq:105,id:'rbrecast'});let rb2m=root.MTGCastPermissions.finishTrackedNonPermanent(rbs,rb2,{seq:106,id:'rbrecastresolve'});q('Rebound recast does not rebound again and resolves to graveyard',rb2m.destination==='graveyard'&&rbs.zones.graveyard.some(x=>x.stableObjectId===rbm.object.stableObjectId));let rbd=base(),rbdItem={id:'rbdecline',kind:'spell',controllerId:1,fromZone:'hand',publicCard:rebound};commitSyntheticStackItem(rbd,rbdItem,{seq:107,id:'rbdcast'});let rbdm=root.MTGCastPermissions.finishTrackedNonPermanent(rbd,rbdItem,{seq:108,id:'rbdresolve'}),rbdr=recordForObject(rbd,rbdm.object.id,'rebound');rbd.turn=6;markReboundTriggered(rbd,rbdr.id,{seq:109,id:'rbdtrig'});declineRebound(rbd,rbdr.id,{seq:110,id:'rbddecline'});q('declined Rebound leaves the card in exile with no later permission',rbd.zones.exile.some(x=>x.stableObjectId===rbdm.object.stableObjectId)&&rbdr.declined&&!Object.values(rbd.castPermissions.records).some(x=>x.active));
 let cp=root.MTGAdvancedSpellResolution?.makeStackCopy?root.MTGAdvancedSpellResolution.makeStackCopy(rbi,1):null;q('spell copies inherit neither Phase 103 cast metadata nor Rebound origin',!cp||(!cp.phase103Cast&&!cp.phase104ReboundOrigin));
 let ser=engine.normalizeState(JSON.parse(JSON.stringify(rbs)));q('Phase 104 alternate-zone state survives reconnect normalization',ser.alternateZoneCasting?.version===VERSION&&Object.keys(ser.alternateZoneCasting.records).length>0);
 q('version identifies Phase 104',VERSION.includes('phase104'));
 return{ok:c.every(x=>x[1]),checks:c}
}
return{VERSION,normalizeRecord,normalizeState,parseFlashbackAll,parseFlashback,parseEscape,parseMadnessAll,parseMadness,permanentCardType,parseWarpAll,parseWarp,parseDisturb,parseRetrace,parseJumpStart,parseAftermath,parseRebound,publicObject,recordForObject,recordByPermission,prepareFlashback,prepareEscape,prepareDisturb,prepareRetrace,prepareJumpStart,prepareAftermath,validatePermissionCard,cardForPermission,validateEscapePayment,castPaymentActions,markEscapePaymentCommitted,discardMadness,madnessCandidates,grantMadnessPermission,internalCastAllowed,declineMadness,markMadnessCountered,warpPermission,commitSyntheticStackItem,decoratePermanentFromStack,onPermanentAdded,warpCandidates,markWarpTriggered,markWarpTriggerCountered,grantWarpFuturePermission,onCastCommitted,stackExitDestination,onTrackedResolved,reboundCandidates,markReboundTriggered,grantReboundPermission,declineRebound,markReboundTriggerCountered,onZoneChange,statusLabel,localQA};
});
