
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MTGStateBasedActions=api})(typeof window!=='undefined'?window:globalThis,function(){
 const VERSION='phase85-state-based-derived-2';
 function isIndestructible(o,state=null){if(state&&typeof MTGContinuousEffects!=='undefined')return !!MTGContinuousEffects.derived(state,o).traits.indestructible;return !!o?.combatMeta?.traits?.indestructible}
 function evaluateObject(o,state=null){
   if(!o)return{known:false,action:null,reason:'missing-object'};
   let toughness=null,damage=0n,derived=state&&typeof MTGContinuousEffects!=='undefined'?MTGContinuousEffects.derived(state,o):null;
   try{let tv=derived?derived.toughness:o.combatMeta?.toughness;if(tv!==null&&tv!==undefined&&String(tv).trim()!=='')toughness=BigInt(String(tv))}catch{}
   try{damage=BigInt(String(o.damageMarked||0))}catch{}
   if(toughness===null)return{known:false,action:null,reason:'toughness-unknown'};
   if(toughness<=0n)return{known:true,action:'graveyard',reason:'zero-or-less-toughness',destroy:false,prevented:false};
   const lethalByDamage=(damage>=toughness)||(!!o.deathtouchMarked&&damage>0n);
   if(!lethalByDamage)return{known:true,action:null,reason:'survives',destroy:false,prevented:false};
   if(isIndestructible(o,state))return{known:true,action:null,reason:'indestructible-prevents-destroy',destroy:true,prevented:true};
   return{known:true,action:'graveyard',reason:o.deathtouchMarked?'deathtouch-damage':'marked-damage',destroy:true,prevented:false};
 }
 function plan(state={}){const actions=[],prevented=[],unknown=[];for(const o of (state.battle||[])){if(globalThis.MTGPhasing?.isPhasedOut(o))continue;const r=evaluateObject(o,state);const row={objectId:String(o.id),name:o.name||'Permanent',...r};if(!r.known)unknown.push(row);else if(r.prevented)prevented.push(row);else if(r.action)actions.push(row)}let attachmentPlan=typeof MTGProtectionRules!=='undefined'?MTGProtectionRules.planAttachmentSBAs(state):{actions:[],review:[]};return{actions,prevented,unknown,attachmentActions:attachmentPlan.actions||[],attachmentReview:attachmentPlan.review||[],clearableDamage:(state.battle||[]).filter(o=>!globalThis.MTGPhasing?.isPhasedOut(o)&&(String(o.damageMarked||'0')!=='0'||o.deathtouchMarked)).length}}
 function localQA(engine){let st=engine.normalizeState({battle:[{id:'a',name:'Lethal',owner:1,combatMeta:{toughness:'3',traits:{}},damageMarked:'3'},{id:'b',name:'Indestructible',owner:1,combatMeta:{toughness:'3',traits:{indestructible:true}},damageMarked:'3'},{id:'c',name:'Zero Toughness',owner:1,combatMeta:{toughness:'0',traits:{indestructible:true}},damageMarked:'0'},{id:'d',name:'Unknown',owner:1,damageMarked:'99'}],events:[],snapshots:[],feed:[]});let p=plan(st),checks=[['lethal marked damage schedules graveyard',p.actions.some(x=>x.objectId==='a'&&x.reason==='marked-damage')],['indestructible prevents destroy-based action',p.prevented.some(x=>x.objectId==='b')],['zero toughness ignores indestructible',p.actions.some(x=>x.objectId==='c'&&x.reason==='zero-or-less-toughness')],['unknown toughness remains unautomated',p.unknown.some(x=>x.objectId==='d')]];engine.reduce(st,engine.makeEvent(st,'STATE_BASED_ACTIONS_APPLIED',{objectIds:p.actions.map(x=>x.objectId)},1,{source:'qa'}));checks.push(['safe state-based actions move only proven objects',st.zones.graveyard.some(x=>x.id==='a')&&st.zones.graveyard.some(x=>x.id==='c')&&st.battle.some(x=>x.id==='b')&&st.battle.some(x=>x.id==='d')]);engine.reduce(st,engine.makeEvent(st,'END_STEP_DAMAGE_CLEANUP',{},1,{source:'qa'}));checks.push(['end-step cleanup clears marked damage',st.battle.every(x=>String(x.damageMarked||'0')==='0'&&!x.deathtouchMarked)]);let ce=engine.normalizeState({battle:[{id:'t',name:'Temp Survivor',owner:1,controllerId:1,typeLine:'Creature',combatMeta:{power:'1',toughness:'0',traits:{}}}],continuousEffects:[{id:'boost',kind:'pt-mod',layer:'7c',scope:{objectId:'t'},powerDelta:'1',toughnessDelta:'1',duration:'until-end-of-turn',sourceController:1,automation:'exact'}],events:[],snapshots:[],feed:[]});checks.push(['continuous effect can keep creature above zero toughness',plan(ce).actions.length===0]);if(typeof MTGContinuousEffects!=='undefined')MTGContinuousEffects.expireTemporary(ce);checks.push(['SBA sees derived toughness after EOT expiration',plan(ce).actions.some(x=>x.objectId==='t'&&x.reason==='zero-or-less-toughness')]);return{ok:checks.every(x=>x[1]),checks,state:st,plan:p}}
 return{VERSION,isIndestructible,evaluateObject,plan,localQA}
});

