
/* Phase 71 — presentation-only battlefield immersion. Never mutates authoritative state. */
(function(){
  'use strict';
  const VERSION='phase71-battlefield-immersion-1';
  let commanderBaseline=null,entranceTimer=null;
  function e(v){return typeof esc==='function'?esc(String(v??'')):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function player(id){return (players||[]).find(p=>Number(p.id)===Number(id))||{id:Number(id),name:'Player '+id}}
  function object(id){return (st?.battle||[]).find(o=>String(o.id)===String(id))}
  function labelTarget(t){if(!t)return'Unknown';if(t.kind==='player')return player(t.playerId).name||('Player '+t.playerId);if(t.kind==='object')return object(t.objectId)?.name||'Permanent';return String(t.kind||'Target')}
  function activeAvatar(p){try{return avatarMarkup(p?.avatarId||MTGAvatars.DEFAULT_ID,{compact:true})}catch{return''}}
  function targetFlows(){let out=[];for(const [setId,set] of Object.entries(st?.targeting?.sets||{})){let source=set?.sourceObjectId?object(set.sourceObjectId)?.name:(set?.sourcePlayerId?player(set.sourcePlayerId).name:'Targeting');for(const t of set?.targets||[])out.push({kind:'target',source:source||setId,target:labelTarget(t)})}return out.slice(0,8)}
  function combatFlows(){let out=[];for(const a of st?.combat?.attackers||[]){let o=object(a.objectId);out.push({kind:'combat',source:o?.name||'Attacker',target:labelTarget(a.defender)})}for(const b of st?.combat?.blockers||[]){let blocker=object(b.blockerObjectId),attacker=object(b.attackerObjectId);out.push({kind:'block',source:blocker?.name||'Blocker',target:attacker?.name||'Attacker'})}return out.slice(0,10)}
  function flowHtml(x){let word=x.kind==='combat'?'ATTACK':x.kind==='block'?'BLOCK':'TARGET';return '<div class="bfFlow '+e(x.kind)+'" aria-label="'+e(x.source+' '+word+' '+x.target)+'"><span class="bfFlowSource">'+e(x.source)+'</span><span class="bfFlowArrow" title="'+word+'"></span><span class="bfFlowTarget">'+e(x.target)+'</span></div>'}
  function render(){let m=document.getElementById('battlefieldAtmosphere');if(!m||!window.st&&typeof st==='undefined')return;let ap=player(st.active),stackN=(st.stack||[]).length,combat=!!st.combat?.active||String(st.phase||'').toLowerCase().includes('combat'),flows=[...combatFlows(),...targetFlows()];m.classList.toggle('stackTense',stackN>0);m.classList.toggle('combatTense',combat);let chips=[];chips.push('<span class="bfStateChip '+(Number(st.active)===Number(me)?'hot':'')+'">ACTIVE · '+e(ap.name||('P'+st.active))+'</span>');if(st.priority)chips.push('<span class="bfStateChip hot">PRIORITY · '+e(player(st.priority).name||('P'+st.priority))+'</span>');if(st.mon)chips.push('<span class="bfStateChip hot">MONARCH · '+e(player(st.mon).name||('P'+st.mon))+'</span>');if(st.ini)chips.push('<span class="bfStateChip hot">INITIATIVE · '+e(player(st.ini).name||('P'+st.ini))+'</span>');if(st.combatSteps?.active)chips.push('<span class="bfStateChip hot">DAMAGE · '+e(String(st.combatSteps.current||'STEP').replace(/_/g,' ').toUpperCase())+'</span>');m.innerHTML='<div class="bfImmersionTop"><div class="bfActiveAvatar">'+activeAvatar(ap)+'</div><div><div class="bfActiveName">'+e(ap.name||('Player '+st.active))+'</div><div class="bfPhaseLine">TURN '+e(st.turn||1)+' · '+e(String(st.phase||'').toUpperCase())+(combat?' · COMBAT ACTIVE':'')+'</div></div><div class="bfStateCount"><b>'+stackN+'</b><span>ON STACK</span></div></div><div class="bfSharedStrip">'+chips.join('')+'</div><div class="bfFlowPanel"><div class="bfFlowTitle">LIVE TABLE DIRECTIONS</div>'+(flows.length?flows.map(flowHtml).join(''):'<div class="bfFlowEmpty">Targets and combat directions will appear here when they matter.</div>')+'</div>'}
  function commanderIds(){return new Set((st?.battle||[]).filter(o=>o?.isCommander||o?.commanderId).map(o=>String(o.id)))}
  function commanderEntrances(){let now=commanderIds();if(commanderBaseline===null){commanderBaseline=now;return}for(const id of now){if(commanderBaseline.has(id))continue;let o=object(id),box=document.getElementById('bfCommanderEntrance');if(!o||!box)continue;box.innerHTML='<small>COMMANDER ENTERS THE BATTLEFIELD</small><b>'+e(o.name||'Commander')+'</b><span>'+e(player(o.controllerId??o.owner).name||'Player')+'</span>';box.classList.remove('on');void box.offsetWidth;box.classList.add('on');clearTimeout(entranceTimer);entranceTimer=setTimeout(()=>box.classList.remove('on'),2400)}commanderBaseline=now}
  function qa(){let fake={active:2,turn:4,phase:'COMBAT',stack:[{}],mon:3,ini:null,combat:{active:true,attackers:[{objectId:'a',defender:{kind:'player',playerId:3}}],blockers:[]},targeting:{sets:{manual:{sourcePlayerId:2,targets:[{kind:'player',playerId:4}]}}}};let checks=[['module version',VERSION.includes('phase71')],['battlefield atmosphere mount',!!document.getElementById('battlefieldAtmosphere')],['commander entrance mount',!!document.getElementById('bfCommanderEntrance')],['combat flow source supported',Array.isArray(fake.combat.attackers)],['target flow source supported',!!fake.targeting.sets.manual],['presentation module does not expose mutation command',typeof window.MTGPhase71Command==='undefined']];return{ok:checks.every(x=>x[1]),checks}}
  window.MTGBattlefieldImmersion={VERSION,render,qa};
  if(typeof sync==='function'){const oldSync=sync;sync=function(){let r=oldSync.apply(this,arguments);try{render();commanderEntrances()}catch(err){console.warn('Phase71 immersion render',err)}return r}}
  if(typeof setPlayerHudPage==='function'){const oldPage=setPlayerHudPage;setPlayerHudPage=function(){let r=oldPage.apply(this,arguments);try{render()}catch{}return r}}
  document.addEventListener('DOMContentLoaded',()=>{try{render();commanderEntrances()}catch{}});
})();
