
/* Phase 105 — Evoke, Dash, Blitz, Cleave & Overload. Canonical Phase 91 alternate-cost choices + stack/permanent lifecycle semantics. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGAlternativeCastingModes=api})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const VERSION='phase105-hand-alternate-casting-modes-1';
const clone=x=>x==null?x:JSON.parse(JSON.stringify(x));
const SUPPORTED=new Set(['evoke','dash','blitz','cleave','overload']);
const lc=x=>String(x||'').toLowerCase();
function normalizeCard(c={}){return root.MTGDeckEngine?.normalizeCard?root.MTGDeckEngine.normalizeCard(c):{...c,n:String(c.n||c.name||'Unknown Card'),manaCost:String(c.manaCost||c.mana_cost||''),oracleText:String(c.oracleText||c.oracle_text||''),typeLine:String(c.typeLine||c.type_line||'')}}
function parseModes(card={}){let c=normalizeCard(card),out=root.MTGAdvancedCastingCosts?.parseAlternates?root.MTGAdvancedCastingCosts.parseAlternates(c.oracleText||''):[],seen=new Set(),modes=[];for(const a of out||[]){let k=lc(a.mechanic);if(!SUPPORTED.has(k))continue;let key=k+'|'+String(a.manaCost||'');if(seen.has(key))continue;seen.add(key);modes.push({id:String(a.id||key),kind:k,label:String(a.label||k),cost:String(a.manaCost||''),textChange:a.textChange||null})}return modes}
function selectedMode(p={}){let base=p?.alternate||null;if(base?.mechanic&&SUPPORTED.has(lc(base.mechanic)))return{kind:lc(base.mechanic),cost:String(base.manaCost||''),label:String(base.label||base.mechanic),textChange:base.textChange||null};let id=String(p?.choices?.base||'');if(!id||id==='normal')return null;let a=(p?.alternates||[]).find(x=>String(x.id)===id),k=lc(a?.mechanic);return a&&SUPPORTED.has(k)?{kind:k,cost:String(a.manaCost||''),label:String(a.label||k),textChange:a.textChange||null}:null}
function transformOracle(text='',kind=''){let t=String(text||''),k=lc(kind);if(k==='cleave')return t.replace(/\[([^\]]*)\]/g,'').replace(/[ 	]+([,.;:])/g,'$1').replace(/[ 	]{2,}/g,' ').trim();if(k==='overload')return t.replace(/\btarget\b/gi,m=>m[0]===m[0].toUpperCase()?'EACH':m[0][0]===m[0][0].toUpperCase()?'Each':'each');return t}
function stackCard(card={},mode=null){let c=normalizeCard(card);if(!mode||!SUPPORTED.has(lc(mode.kind)))return clone(c);let out=clone(c),k=lc(mode.kind);if(k==='cleave'||k==='overload'){out.oracleText=transformOracle(c.oracleText,k);out.oracle_text=out.oracleText;out.phase105TextChange=k==='cleave'?'cleave-brackets-removed':'overload-target-to-each'}return out}
function targetChangingModes(card={}){return parseModes(card).filter(x=>x.kind==='cleave'||x.kind==='overload')}
function allowsTargetChangingAlternative(card={}){return targetChangingModes(card).length>0}
function metadata(mode={},state={},controllerId=0){let k=lc(mode.kind);if(!SUPPORTED.has(k))return null;return{kind:k,cost:String(mode.cost||''),label:String(mode.label||k),textChange:mode.textChange||null,castTurn:Number(state?.turn||0),castControllerId:Number(controllerId||0),paidAlternative:true,rulesProfileVersion:VERSION}}
function decoratePermanentFromStack(item={},o={}){let m=item?.phase105Cast;if(!m||!SUPPORTED.has(lc(m.kind)))return o;let k=lc(m.kind);if(!['evoke','dash','blitz'].includes(k))return o;let inc=String(o.incarnationId||''),castControllerId=Number(m.castControllerId||item.controllerId||o.controllerId||o.owner||0);o.phase105Cast={kind:k,cost:String(m.cost||''),active:true,incarnationId:inc,castTurn:Number(m.castTurn||0),castControllerId,grantedHaste:k==='dash'||k==='blitz',evokePending:k==='evoke',endStepPending:k==='dash'||k==='blitz',blitzDrawPending:k==='blitz',triggerQueued:false,endStepQueued:false,rulesProfileVersion:VERSION};return o}
function exactPermanent(state={},objectId='',incarnationId=''){return (state.battle||[]).find(o=>String(o.id)===String(objectId||'')&&(!incarnationId||String(o.incarnationId||'')===String(incarnationId)))||null}
function onPermanentAdded(state={},o={},event=null){let m=o?.phase105Cast;if(!m?.active)return{ok:true,ignored:true};m.incarnationId=String(o.incarnationId||m.incarnationId||'');return{ok:true,kind:m.kind,objectId:String(o.id),incarnationId:m.incarnationId}}
function permanentCandidates(state={},event={}){let src=event?.payload?.object||null,o=src?exactPermanent(state,src.id,src.incarnationId):null,m=o?.phase105Cast;if(!m?.active||m.kind!=='evoke'||!m.evokePending||m.triggerQueued)return[];return[{item:{id:'stack_phase105_evoke_'+String(o.id).replace(/[^A-Za-z0-9_-]/g,'_')+'_'+String(event.seq||0),kind:'trigger-group',name:'Evoke — sacrifice this permanent',count:'1',controllerId:Number(m.castControllerId||o.controllerId||o.owner),sourceObjectId:o.id,targets:[],effect:{type:'phase105-evoke-sacrifice',objectId:o.id,incarnationId:String(o.incarnationId||'')},oracleText:'When this permanent enters, if its evoke cost was paid, its controller sacrifices it.',triggerEvent:'PERMANENT_ENTERED',rulesProfileVersion:VERSION},baseCount:'1',modifiers:[]}]
}
function endStepCandidates(state={}){let out=[];for(const o of state.battle||[]){let m=o?.phase105Cast;if(!m?.active||!m.endStepPending||m.endStepQueued||!['dash','blitz'].includes(m.kind))continue;let dash=m.kind==='dash';out.push({item:{id:'stack_phase105_'+m.kind+'_'+String(o.id).replace(/[^A-Za-z0-9_-]/g,'_')+'_'+String(state.meta?.seq||0),kind:'trigger-group',name:(dash?'Dash — return this permanent':'Blitz — sacrifice this permanent'),count:'1',controllerId:Number(m.castControllerId||o.controllerId||o.owner),sourceObjectId:o.id,targets:[],effect:{type:dash?'phase105-dash-return':'phase105-blitz-sacrifice',objectId:o.id,incarnationId:String(o.incarnationId||'')},oracleText:dash?'At the beginning of the next end step, return this permanent to its owner’s hand.':'At the beginning of the next end step, sacrifice this permanent.',triggerEvent:'END_STEP_BEGIN',rulesProfileVersion:VERSION},baseCount:'1',modifiers:[]})}return out}
function markTriggerQueued(state={},spec={},event=null){let o=exactPermanent(state,spec.objectId,spec.incarnationId),m=o?.phase105Cast;if(!m?.active)return{ok:false,ignored:true,reason:'phase105-permanent-not-active'};let kind=lc(spec.kind||m.kind);if(kind==='evoke'){m.triggerQueued=true;m.evokePending=false}else if(kind==='dash'||kind==='blitz'){m.endStepQueued=true;m.endStepPending=false}else return{ok:false,ignored:true,reason:'phase105-trigger-kind'};m.queuedSeq=Number(event?.seq||state.meta?.seq||0);return{ok:true,object:o,kind}}
function onZoneChange(state={},o={},ctx={}){let from=lc(ctx.fromZone),to=lc(ctx.toZone),m=o?.phase105Cast;if(!m?.active||from!=='battlefield'||to==='battlefield')return{ok:true,ignored:true};let result={ok:true,kind:m.kind,objectId:String(o.id),incarnationId:String(o.incarnationId||''),fromZone:from,toZone:to,controllerId:Number(o.controllerId||m.castControllerId||o.owner),castControllerId:Number(m.castControllerId||o.controllerId||o.owner),name:String(o.name||'Permanent'),blitzDied:m.kind==='blitz'&&to==='graveyard'&&!!m.blitzDrawPending};m.active=false;m.evokePending=false;m.endStepPending=false;m.grantedHaste=false;m.leftBattlefield=true;m.leftTo=to;m.leftSeq=Number(ctx.seq||state.meta?.seq||0);return result}
function blitzDeathCandidates(state={},event={}){let r=event?.phase105ZoneResult;if(!r?.blitzDied)return[];return[{item:{id:'stack_phase105_blitz_draw_'+String(r.objectId).replace(/[^A-Za-z0-9_-]/g,'_')+'_'+String(event.seq||0),kind:'trigger-group',name:'Blitz — draw a card',count:'1',controllerId:Number(r.controllerId||r.castControllerId||0),sourceObjectId:String(r.objectId||''),targets:[],effect:{type:'phase105-blitz-draw',playerId:Number(r.controllerId||r.castControllerId||0)},oracleText:'When this permanent is put into a graveyard from the battlefield, draw a card.',triggerEvent:'PERMANENT_LEFT',rulesProfileVersion:VERSION},baseCount:'1',modifiers:[]}]
}
function localQA(engine){let c=[],q=(n,v)=>c.push([n,!!v]);let evoke={n:'Shriekmaw',manaCost:'{4}{B}',typeLine:'Creature — Elemental',oracleText:'Fear\nEvoke {1}{B}',resolved:true},dash={n:'Dash Test',manaCost:'{3}{R}',typeLine:'Creature — Warrior',oracleText:'Dash {1}{R}',resolved:true},blitz={n:'Blitz Test',manaCost:'{3}{B}',typeLine:'Creature — Rogue',oracleText:'Blitz {2}{B}',resolved:true},cleave={n:'Cleave Test',manaCost:'{2}{U}',typeLine:'Instant',oracleText:'Cleave {4}{U}\nReturn target [nonland] permanent to its owner’s hand.',resolved:true},over={n:'Overload Test',manaCost:'{1}{U}',typeLine:'Sorcery',oracleText:'Overload {6}{U}\nReturn target nonland permanent you don’t control to its owner’s hand.',resolved:true};
 q('Phase 91 exposes Evoke as canonical alternative cost',parseModes(evoke)[0]?.kind==='evoke'&&parseModes(evoke)[0]?.cost==='{1}{B}');q('Dash and Blitz costs are canonical modes',parseModes(dash)[0]?.kind==='dash'&&parseModes(blitz)[0]?.kind==='blitz');q('Cleave removes only square-bracketed rules text',!stackCard(cleave,{kind:'cleave'}).oracleText.includes('[nonland]')&&/Return target permanent/.test(stackCard(cleave,{kind:'cleave'}).oracleText));q('Overload performs the CR target-to-each text change',/Return each nonland permanent/.test(stackCard(over,{kind:'overload'}).oracleText));
 let p={alternates:[{id:'a',mechanic:'blitz',manaCost:'{2}{B}',label:'Blitz {2}{B}'}],choices:{base:'a'}};q('selected casting mode is preserved independently of mana calculation',selectedMode(p)?.kind==='blitz');if(root.MTGAdvancedCastingCosts?.createPending){let malformed=root.MTGAdvancedCastingCosts.createPending({battle:[],zones:{graveyard:[],exile:[],hand:[],command:[]},life:{1:40}},{playerId:1,name:'Malformed Evoke',cardPublic:{n:'Malformed Evoke',manaCost:'{2}{B}',typeLine:'Creature',oracleText:'Evoke — Sacrifice a creature',resolved:true}},[{id:1}]);q('unparsed Phase 105 keyword costs fall back to Manual/Judge Review',malformed.stage==='review'&&malformed.reviewReasons.some(x=>/Evoke cost could not be represented exactly/.test(x)))}else q('unparsed Phase 105 keyword costs fall back to Manual/Judge Review',false);if(!engine)return{ok:false,checks:[...c,['engine supplied',false]]};let base=()=>engine.normalizeState({life:{1:40,2:40},battle:[],stack:[],zones:{exile:[],graveyard:[],hand:[],command:[]},events:[],snapshots:[],feed:[],active:1,priority:1,turn:5,phase:'MAIN 1'});
 let es=base(),eo={id:'ev1',name:'Shriekmaw',owner:1,controllerId:1,type:'Creature',typeLine:evoke.typeLine,oracleText:evoke.oracleText,incarnationId:'ev1@battle',phase105Cast:{kind:'evoke',active:true,incarnationId:'ev1@battle',castControllerId:1,evokePending:true}};es.battle.push(eo);let ec=permanentCandidates(es,{seq:1,payload:{object:eo}});q('Evoke creates one mandatory ETB sacrifice trigger',ec.length===1&&ec[0].item.effect.type==='phase105-evoke-sacrifice');let em=markTriggerQueued(es,{objectId:'ev1',incarnationId:'ev1@battle',kind:'evoke'},{seq:2});q('Evoke trigger queue is one-shot',em.ok&&permanentCandidates(es,{seq:3,payload:{object:eo}}).length===0);
 let ds=base(),do1={id:'d1',name:'Dasher',owner:1,controllerId:1,type:'Creature',typeLine:'Creature',incarnationId:'d1@battle'};decoratePermanentFromStack({controllerId:1,phase105Cast:metadata({kind:'dash',cost:'{1}{R}'},ds,1)},do1);ds.battle.push(do1);q('Dash permanent carries haste and one next-end-step return',do1.phase105Cast.grantedHaste&&endStepCandidates(ds)[0]?.item.effect.type==='phase105-dash-return');markTriggerQueued(ds,{objectId:'d1',incarnationId:'d1@battle',kind:'dash'},{seq:4});q('Dash delayed trigger does not repeat after it has triggered',endStepCandidates(ds).length===0);
 let bs=base(),bo={id:'b1',name:'Blitzer',owner:1,controllerId:1,type:'Creature',typeLine:'Creature',incarnationId:'b1@battle'};decoratePermanentFromStack({controllerId:1,phase105Cast:metadata({kind:'blitz',cost:'{2}{B}'},bs,1)},bo);bs.battle.push(bo);let zr=onZoneChange(bs,bo,{seq:5,fromZone:'battlefield',toZone:'graveyard'});let bc=blitzDeathCandidates(bs,{seq:5,phase105ZoneResult:zr});q('Blitz battlefield-to-graveyard movement creates its draw trigger',zr.blitzDied&&bc.length===1&&bc[0].item.effect.type==='phase105-blitz-draw');q('Blitz metadata is inactive after leaving battlefield',bo.phase105Cast.active===false&&!bo.phase105Cast.grantedHaste);
 let cp=root.MTGAdvancedSpellResolution?.makeStackCopy?root.MTGAdvancedSpellResolution.makeStackCopy({id:'copyme',kind:'spell',name:'Dasher',controllerId:1,publicCard:dash,phase105Cast:metadata({kind:'dash',cost:'{1}{R}'},ds,1)},1):null;q('spell copies preserve Phase 105 casting-mode choices',!cp||cp.phase105Cast?.kind==='dash');q('Dash haste is exposed through the existing combat-rules layer',root.MTGCombatRules?.stats?.(do1,ds)?.traits?.haste===true);
 let ars=base(),aro={id:'ar1',name:'Reducer Evoke',owner:1,controllerId:1,type:'Creature',typeLine:'Creature',incarnationId:'ar1@battle',phase105Cast:{kind:'evoke',active:true,incarnationId:'ar1@battle',castControllerId:1,evokePending:true}};let ape=engine.dispatch(ars,'PERMANENT_ADDED',{object:aro},1,{source:'phase105-qa'}),arp=ars.battle.find(x=>x.id==='ar1');q('authoritative PERMANENT_ADDED preserves Phase 105 lifecycle metadata',ape.phase105PermanentResult?.ok&&arp?.phase105Cast?.evokePending===true);let aqe=engine.dispatch(ars,'ALT_MODE_TRIGGER_QUEUED',{objectId:'ar1',incarnationId:arp?.incarnationId,kind:'evoke'},1,{source:'phase105-qa'});q('authoritative trigger-queued reducer commits Evoke one-shot state',aqe.phase105Result?.ok&&arp?.phase105Cast?.triggerQueued===true&&!arp?.phase105Cast?.evokePending);
 let azs=base(),azo={id:'az1',name:'Reducer Blitz',owner:1,controllerId:1,type:'Creature',typeLine:'Creature',incarnationId:'az1@battle'};decoratePermanentFromStack({controllerId:1,phase105Cast:metadata({kind:'blitz',cost:'{2}{B}'},azs,1)},azo);engine.dispatch(azs,'PERMANENT_ADDED',{object:azo},1,{source:'phase105-qa'});let aze=engine.dispatch(azs,'OBJECT_ZONE_CHANGED',{objectId:'az1',toZone:'graveyard'},1,{source:'phase105-qa'});q('authoritative zone-change reducer exposes Blitz death trigger context',aze.phase105ZoneResult?.blitzDied===true&&azs.zones.graveyard.some(x=>x.id==='az1'));
 let ser=engine.normalizeState(JSON.parse(JSON.stringify(ds)));q('Phase 105 permanent metadata survives reconnect normalization',ser.battle[0]?.phase105Cast?.kind==='dash'&&ser.battle[0]?.phase105Cast?.endStepQueued===true);q('version identifies Phase 105',VERSION.includes('phase105'));return{ok:c.every(x=>x[1]),checks:c}}
return{VERSION,SUPPORTED,parseModes,selectedMode,transformOracle,stackCard,targetChangingModes,allowsTargetChangingAlternative,metadata,decoratePermanentFromStack,onPermanentAdded,permanentCandidates,endStepCandidates,markTriggerQueued,onZoneChange,blitzDeathCandidates,exactPermanent,localQA};
});
