
/* Phase 85 — replacement/prevention foundation. Supported automatic effects are deliberately commutative or singular. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGReplacementEffects=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const VERSION='phase85-replacement-effects-1';const clone=x=>JSON.parse(JSON.stringify(x));const ctrl=o=>Number(o?.controllerId??o?.owner??0)||0;
function bi(v,f=0n){try{return BigInt(String(v??f).replace(/,/g,''))}catch{return f}}
function normalizeEffect(e={}){let kinds=['token-multiplier','counter-multiplier','life-gain-multiplier','damage-prevent-fixed','damage-prevent-shield','manual'],kind=kinds.includes(String(e.kind))?String(e.kind):'manual';return{id:String(e.id||e.effectId||''),kind,event:String(e.event||''),scope:e.scope&&typeof e.scope==='object'?clone(e.scope):{},multiplier:bi(e.multiplier,1n).toString(),amount:bi(e.amount).toString(),remaining:bi(e.remaining??e.amount).toString(),duration:String(e.duration||'source'),sourceObjectId:e.sourceObjectId?String(e.sourceObjectId):null,sourceController:Number(e.sourceController||0)||0,sourceCopies:bi(e.sourceCopies,1n).toString(),timestamp:Number(e.timestamp||0),consumable:!!e.consumable,automation:e.automation==='exact'?'exact':'manual',oracleText:String(e.oracleText||'')}}
function staticEffects(state={}){let out=[];for(const source of state.battle||[]){if(globalThis.MTGPhasing?.isPhasedOut(source))continue;for(const raw of source.replacementEffects||[]){let e=normalizeEffect({...raw,sourceObjectId:source.id,sourceController:ctrl(source),sourceCopies:String(source.q??'1'),timestamp:Number(raw.timestamp??source.order??0)});e.id='static:'+String(source.id)+':repl:'+String(raw.id||out.length);out.push(e)}}return out}
function temporaryEffects(state={}){return (Array.isArray(state.replacementEffects)?state.replacementEffects:[]).map(normalizeEffect)}
function active(state={}){return [...staticEffects(state),...temporaryEffects(state)].sort((a,b)=>a.timestamp-b.timestamp||a.id.localeCompare(b.id))}
function scopeMatches(e={},ctx={}){let s=e.scope||{},sc=Number(e.sourceController||0),affected=Number(ctx.affectedPlayerId||0);if(s.self&&ctx.object&&e.sourceObjectId&&String(e.sourceObjectId)!==String(ctx.object.id||''))return false;if(s.controller==='you'&&sc&&affected!==sc)return false;if(s.controller==='opponent'&&sc&&affected===sc)return false;if(s.playerId&&Number(s.playerId)!==affected)return false;if(s.sourceObjectId){let eventSource=ctx.sourceObjectId||(ctx.kind==='enter'?ctx.object?.id:null);if(String(s.sourceObjectId)!==String(eventSource||''))return false;}if(s.targetObjectId&&String(s.targetObjectId)!==String(ctx.targetObjectId||''))return false;return true}
function safeList(state,kind,ctx){let all=active(state).filter(e=>e.kind===kind&&scopeMatches(e,ctx));return{auto:all.filter(e=>e.automation==='exact'),manual:all.filter(e=>e.automation!=='exact')}}
function applyMultiplierFamily(state,kind,ctx,field){let original=bi(ctx[field]),value=original,{auto,manual}=safeList(state,kind,ctx),applied=[],review=manual.slice();for(const e of auto){let m=bi(e.multiplier,1n),copies=bi(e.sourceCopies,1n);if(m<0n)m=1n;if(copies<1n)copies=1n;if(copies>4096n){review.push({...e,reason:'cohort-exponent-too-large'});continue}let factor=m**copies;value*=factor;applied.push({effectId:e.id,multiplier:m.toString(),copies:copies.toString(),factor:factor.toString()})}if(review.length)return{value:original.toString(),applied:[],reviewRequired:true,reviewEffects:review.map(e=>e.id),blocked:true};return{value:value.toString(),applied,reviewRequired:false,reviewEffects:[]}}
function applyToken(state={},ctx={}){return applyMultiplierFamily(state,'token-multiplier',ctx,'quantity')}
function applyCounter(state={},ctx={}){return applyMultiplierFamily(state,'counter-multiplier',ctx,'amount')}
function applyLifeGain(state={},ctx={}){return applyMultiplierFamily(state,'life-gain-multiplier',ctx,'amount')}
function applyDamage(state={},ctx={}){let original=bi(ctx.amount),value=original,applied=[],consume=[],manual=[];for(const e of active(state)){if(!scopeMatches(e,ctx))continue;if(e.automation!=='exact'){manual.push(e);continue}if(e.kind==='damage-prevent-fixed'){let take=bi(e.amount);if(take>value)take=value;if(take>0n){value-=take;applied.push({effectId:e.id,prevented:take.toString()})}}else if(e.kind==='damage-prevent-shield'){let cap=bi(e.remaining);let take=cap<value?cap:value;if(take>0n){value-=take;applied.push({effectId:e.id,prevented:take.toString()});consume.push({effectId:e.id,amount:take.toString()})}}}if(manual.length)return{value:original.toString(),applied:[],consume:[],reviewRequired:true,reviewEffects:manual.map(e=>e.id),blocked:true};return{value:value.toString(),applied,consume,reviewRequired:false,reviewEffects:[]}}
function consume(state={},uses=[]){if(!Array.isArray(state.replacementEffects)||!uses.length)return 0;let n=0;for(const u of uses){let want=String(u.effectId||'').replace(/^state:repl:/,''),e=state.replacementEffects.find(x=>String(x.id||x.effectId)===want||('state:repl:'+String(x.id||x.effectId))===String(u.effectId));if(!e)continue;let remain=bi(e.remaining??e.amount)-bi(u.amount);e.remaining=(remain>0n?remain:0n).toString();if(remain<=0n)e.consumed=true;n++}state.replacementEffects=state.replacementEffects.filter(e=>!e.consumed);return n}
function expiresAtCleanup(e={}){let d=String(e.duration||'').toLowerCase();return d==='until-end-of-turn'||d==='this-turn'}
function expireTemporary(state={}){let before=(state.replacementEffects||[]).length;state.replacementEffects=(state.replacementEffects||[]).filter(e=>!expiresAtCleanup(e));return before-state.replacementEffects.length}
function summary(state={}){let effects=active(state);return{count:effects.length,static:staticEffects(state).length,temporary:temporaryEffects(state).length,manual:effects.filter(e=>e.automation!=='exact').length}}
function localQA(){let checks=[],q=(n,v)=>checks.push([n,!!v]),doubler={id:'d',owner:1,controllerId:1,replacementEffects:[{id:'tok2',kind:'token-multiplier',scope:{controller:'you'},multiplier:'2',automation:'exact'}]},enemyDoubler={id:'e',owner:2,controllerId:2,replacementEffects:[{id:'life2',kind:'life-gain-multiplier',scope:{controller:'you'},multiplier:'2',automation:'exact'}]},st={battle:[doubler,enemyDoubler],replacementEffects:[{id:'shield',kind:'damage-prevent-shield',scope:{playerId:1},remaining:'3',duration:'until-end-of-turn',sourceController:1,automation:'exact'}]};q('token replacement uses affected controller',applyToken(st,{affectedPlayerId:1,quantity:'4'}).value==='8');q('opponent token creation does not use your doubler',applyToken(st,{affectedPlayerId:2,quantity:'4'}).value==='4');q('life multiplier belongs to its controller',applyLifeGain(st,{affectedPlayerId:2,amount:'3'}).value==='6');let dmg=applyDamage(st,{affectedPlayerId:1,amount:'5'});q('prevention shield reduces damage',dmg.value==='2'&&dmg.consume[0]?.amount==='3');consume(st,dmg.consume);q('consumed prevention shield is removed',st.replacementEffects.length===0);q('pure multipliers compose exactly',applyToken({battle:[doubler,{id:'d2',owner:1,controllerId:1,replacementEffects:[{id:'tok3',kind:'token-multiplier',scope:{controller:'you'},multiplier:'3',automation:'exact'}]}]},{affectedPlayerId:1,quantity:'2'}).value==='12');q('replacement source cohort counts each copy',applyToken({battle:[{...doubler,q:'3'}]},{affectedPlayerId:1,quantity:'1'}).value==='8');q('oversized replacement cohort becomes manual review',applyToken({battle:[{...doubler,q:'5000'}]},{affectedPlayerId:1,quantity:'1'}).reviewRequired===true);let counterState={battle:[{id:'cm',owner:1,controllerId:1,replacementEffects:[{id:'ctr2',kind:'counter-multiplier',scope:{controller:'you'},multiplier:'2',automation:'exact'}]}]};q('permanent counter multiplier is exact',applyCounter(counterState,{affectedPlayerId:1,targetObjectId:'x',amount:'3'}).value==='6');q('version identifies Phase 85',VERSION.includes('phase85'));return{ok:checks.every(x=>x[1]),checks}}
return{VERSION,bi,normalizeEffect,staticEffects,temporaryEffects,active,scopeMatches,applyToken,applyCounter,applyLifeGain,applyDamage,consume,expiresAtCleanup,expireTemporary,summary,localQA};
});
