
/* Battle Chronicle — authoritative color-weighted historical battle naming. */
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MTGBattleChronicle=api})(typeof window!=='undefined'?window:globalThis,function(){
 'use strict';
 const VERSION='battle-chronicle-color-weighted-1',ORDER=['W','U','B','R','G','C'];
 const BANK={
  W:{roots:['Dawn','Ivory','Silver','Sun','Lion','Highcrest','Goldward','Bright','Sacred','Crownwatch','Whitecliff','Dawnfall'],suffixes:['Bastion','Gate','Keep','Hold','Crest','Watch','Citadel','March','Vale','Ridge']},
  U:{roots:['Moon','Mist','Storm','Tide','Deepwater','Greywater','Sapphire','Veil','Starfall','Frost','Moonfall','Stormwatch'],suffixes:['Reach','Crossing','Harbor','Watch','Spire','Pass','Ford','Crest','Vale','Ridge']},
  B:{roots:['Hollow','Grave','Dread','Night','Raven','Obsidian','Blackwater','Gloom','Mourn','Ravenfall','Darkwater','Shadow'],suffixes:['Throne','Moor','March','Hollow','Reach','Keep','Vale','Gate','Spire','Crossing']},
  R:{roots:['Ember','Ashen','Cinder','Crimson','Flame','Thunder','Blood','Ashfall','Scarlet','Emberfall','Redwater','Firewatch'],suffixes:['Ridge','Pass','Gate','Crown','Reach','Spire','March','Keep','Crossing','Hold']},
  G:{roots:['Briar','Thorn','Verdant','Oak','Pine','Wolf','Stag','Blackthorn','Wildwood','Elder','Thornwood','Greythorn'],suffixes:['Vale','Hollow','Reach','Pass','Watch','Moor','Grove','Ridge','Crossing','Keep']},
  C:{roots:['Iron','Stone','Steel','Bronze','Pale','Dust','Granite','Oldstone','Ironfall','Grey','Silent','Cold'],suffixes:['Reach','Spire','Gate','March','Crossing','Keep','Ridge','Hollow','Pass','Watch']}
 };
 const NEUTRAL={roots:['Iron','Stone','Grey','Old','Kingsward','Queensfall','North','West','East','South','Highland','Lowland','Blackstone','Whitewater','Coldwater','Redford','Ashford','Ironford'],suffixes:['Ford','Crossing','Vale','Reach','Ridge','Pass','Gate','Keep','Hold','March','Watch','Moor','Bastion','Crest']};
 const RARE={roots:['Sundered','Shattered','Broken','Starfall','Moonfall','Ironfall','Ravenfall','Goldfall','Silent','Forgotten','Ancient','Forsaken','Lastlight','Stormfall'],suffixes:['Crown','Spire','Throne','Citadel','Sanctum','Gate','March','Keep','Reach','Pass']};
 function normalizeIdentity(v){let a=Array.isArray(v)?v:[];return[...new Set(a.map(x=>String(x||'').trim().toUpperCase()).filter(x=>'WUBRG'.includes(x)))]}
 function colorCounts(players=[]){let c={W:0,U:0,B:0,R:0,G:0,C:0};for(const p of players||[]){let ids=normalizeIdentity(p?.deckColorIdentity||p?.colorIdentity);if(!ids.length)c.C++;else ids.forEach(x=>c[x]++)}return c}
 function randomUnit(rng){if(typeof rng==='function'){let n=Number(rng());return Number.isFinite(n)?Math.max(0,Math.min(.999999999,n)):0}try{if(globalThis.crypto?.getRandomValues){let a=new Uint32Array(1);globalThis.crypto.getRandomValues(a);return a[0]/4294967296}}catch{}return Math.random()}
 function pick(a,rng){return a[Math.min(a.length-1,Math.floor(randomUnit(rng)*a.length))]}
 function weightedColor(counts,rng,exclude=null){let rows=ORDER.filter(k=>k!==exclude&&Number(counts?.[k]||0)>0).map(k=>[k,Number(counts[k])]);if(!rows.length)return null;let total=rows.reduce((n,x)=>n+x[1],0),r=randomUnit(rng)*total;for(const [k,w] of rows){r-=w;if(r<0)return k}return rows.at(-1)[0]}
 function cleanPlace(root,suffix){let a=String(root||'').replace(/^the\s+/i,'').trim(),b=String(suffix||'').replace(/^the\s+/i,'').trim();if(!a)a='Iron';if(!b)b='Reach';if(a.toLowerCase()===b.toLowerCase()||a.toLowerCase().endsWith(b.toLowerCase()))b='Reach';return(a+' '+b).replace(/\s+/g,' ').trim()}
 function influence(players=[]){let counts=colorCounts(players),colored=ORDER.slice(0,5).reduce((n,k)=>n+counts[k],0),total=colored+counts.C;return{counts,colored,total,dominant:weightedColor(counts,()=>0)||'C'}}
 function generate(players=[],opts={}){let rng=opts.rng,counts=colorCounts(players),colored=ORDER.slice(0,5).reduce((n,k)=>n+counts[k],0),mode=randomUnit(rng),root,suffix;if(colored>0&&mode<.80){let primary=weightedColor({...counts,C:0},rng)||'C',secondary=randomUnit(rng)<.42?(weightedColor({...counts,C:0},rng)||primary):primary;root=pick(BANK[primary].roots,rng);suffix=pick(BANK[secondary].suffixes,rng)}else if(mode<.95){root=pick(NEUTRAL.roots,rng);suffix=pick(NEUTRAL.suffixes,rng)}else{root=pick(RARE.roots,rng);suffix=pick(RARE.suffixes,rng)}let place=cleanPlace(root,suffix);return'The Battle of '+place}
 function localQA(){let checks=[],q=(n,v)=>checks.push([n,!!v]),c=colorCounts([{deckColorIdentity:['G']},{deckColorIdentity:['G','W']},{deckColorIdentity:['R','G']}]),seq=[.10,.78,.22,.31,.65],i=0,name=generate([{deckColorIdentity:['G']},{deckColorIdentity:['G','W']},{deckColorIdentity:['R','G']}],{rng:()=>seq[(i++)%seq.length]});q('repeated deck colors add repeated naming weight',c.G===3&&c.W===1&&c.R===1);q('battle name uses fixed historical opener',/^The Battle of [A-Z]/.test(name));q('battle name never adds a second the',!/^The Battle of the\b/i.test(name));q('generated title has a proper-name body',name.split(/\s+/).length>=5);q('colorless decks remain nameable',/^The Battle of /.test(generate([{deckColorIdentity:[]}],{rng:()=>.2})));q('version identifies Battle Chronicle',VERSION.includes('battle-chronicle'));return{ok:checks.every(x=>x[1]),checks,version:VERSION,sample:name}}
 return{VERSION,BANK,NEUTRAL,RARE,normalizeIdentity,colorCounts,influence,generate,localQA};
});
