
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGLegality=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='phase67-legality-1';
const FORMATS={commander:{label:'Commander',min:100,max:100,copies:1},standard:{label:'Standard',min:60,copies:4},pioneer:{label:'Pioneer',min:60,copies:4},modern:{label:'Modern',min:60,copies:4},legacy:{label:'Legacy',min:60,copies:4},vintage:{label:'Vintage',min:60,copies:4},pauper:{label:'Pauper',min:60,copies:4},brawl:{label:'Brawl',min:60,max:60,copies:1}};
const BASIC=/\bBasic Land\b/i;
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}
function normName(v){return String(v||'').trim().toLowerCase()}
function specialCopyRule(c){let t=String(c.oracleText||c.oracle_text||'');return /deck can have (?:any number|up to|a card named)/i.test(t)||/deck may have (?:any number|up to)/i.test(t)}
function commanderEligible(c){let t=String(c.typeLine||c.type_line||''),o=String(c.oracleText||c.oracle_text||'');return /Legendary.*Creature/i.test(t)||/can be your commander/i.test(o)}
function legalState(card,format){if(!card||card.resolved!==true)return'unverified';let s=card.legalities?.[format];return ['legal','not_legal','banned','restricted'].includes(s)?s:'unverified'}
function colorSubset(card,commander){let allowed=new Set(commander?.colorIdentity||[]);return (card?.colorIdentity||[]).every(x=>allowed.has(x))}
function combinedIdentity(a,b){return [...new Set([...(a?.colorIdentity||[]),...(b?.colorIdentity||[])])]}
function pairCompatibility(a,b){if(!a||!b)return{ok:true,known:true};let ao=String(a.oracleText||''),bo=String(b.oracleText||''),at=String(a.typeLine||''),bt=String(b.typeLine||'');if(/choose a background/i.test(ao)&&/Legendary Enchantment.*Background/i.test(bt))return{ok:true,known:true};if(/choose a background/i.test(bo)&&/Legendary Enchantment.*Background/i.test(at))return{ok:true,known:true};if(/friends forever/i.test(ao)&&/friends forever/i.test(bo))return{ok:true,known:true};if(/doctor's companion/i.test(ao)&&/\bDoctor\b/i.test(bt))return{ok:true,known:true};if(/doctor's companion/i.test(bo)&&/\bDoctor\b/i.test(at))return{ok:true,known:true};let aw=ao.match(/partner with ([^\n.]+)/i),bw=bo.match(/partner with ([^\n.]+)/i);if(aw||bw){let ok=(aw&&normName(aw[1])===normName(b.n))||(bw&&normName(bw[1])===normName(a.n));return{ok:!!ok,known:true}}if(/(^|\n)Partner(\n|$)/i.test(ao)&&/(^|\n)Partner(\n|$)/i.test(bo))return{ok:true,known:true};return{ok:false,known:false}}
function validate(cards=[],opts={}){let format=String(opts.format||'commander').toLowerCase(),cfg=FORMATS[format]||{label:format,min:60,copies:4},commanderName=opts.commander||null,partnerName=opts.partner||null,issues=[],counts={legal:0,illegal:0,warning:0,unverified:0},total=cards.reduce((s,c)=>s+n(c.q,1),0),commander=cards.find(c=>normName(c.n)===normName(commanderName)),partner=cards.find(c=>normName(c.n)===normName(partnerName));
for(const c of cards){let qty=Math.max(1,n(c.q,1)),state=legalState(c,format);if(state==='legal'){counts.legal+=qty}else if(state==='restricted'){counts.warning+=qty;issues.push({severity:'warning',card:c.n,reason:'Restricted in '+cfg.label+'. Confirm deck-copy limits for this format.'})}else if(state==='banned'||state==='not_legal'){counts.illegal+=qty;issues.push({severity:'illegal',card:c.n,reason:state==='banned'?'Banned in '+cfg.label+'.':'Not legal in '+cfg.label+'.'})}else{counts.unverified+=qty;issues.push({severity:'unverified',card:c.n,reason:'Current legality could not be verified. The deck is not marked illegal for this card.'})}}
if(cfg.min&&total<cfg.min)issues.push({severity:'illegal',card:'Deck construction',reason:'Deck has '+total+' cards; '+cfg.label+' requires at least '+cfg.min+'.'});if(cfg.max&&total>cfg.max)issues.push({severity:'illegal',card:'Deck construction',reason:'Deck has '+total+' cards; '+cfg.label+' uses '+cfg.max+' cards.'});
if(format==='commander'){if(!commanderName)issues.push({severity:'unverified',card:'Commander',reason:'Choose a commander to finish Commander deck-construction checks.'});else if(!commander)issues.push({severity:'unverified',card:'Commander',reason:'Selected commander was not resolved in this imported list.'});else{if(commander.resolved===true&&!commanderEligible(commander))issues.push({severity:'illegal',card:commander.n,reason:'Selected card is not verified as commander-eligible.'});if(partnerName&&!partner)issues.push({severity:'unverified',card:'Co-commander',reason:'Selected co-commander was not resolved in this imported list.'});if(partner&&partner.resolved===true){let background=/Legendary Enchantment.*Background/i.test(partner.typeLine||'')&&/choose a background/i.test(commander.oracleText||'');if(!commanderEligible(partner)&&!background)issues.push({severity:'illegal',card:partner.n,reason:'Selected co-commander is not verified as commander-eligible.'});let pair=pairCompatibility(commander,partner);if(!pair.ok)issues.push({severity:pair.known?'illegal':'unverified',card:commander.n+' + '+partner.n,reason:pair.known?'These two cards do not satisfy their recognized co-commander pairing text.':'Co-commander pairing could not be proven automatically; the deck is not rejected for this pairing.'})}let allowed=new Set(combinedIdentity(commander,partner));for(const c of cards)if(c.resolved===true&&!(c.colorIdentity||[]).every(x=>allowed.has(x)))issues.push({severity:'illegal',card:c.n,reason:'Color identity is outside the combined commander color identity.'});}
let by=new Map();for(const c of cards){let k=normName(c.n);by.set(k,(by.get(k)||0)+Math.max(1,n(c.q,1)))}for(const [k,q] of by){let c=cards.find(x=>normName(x.n)===k);if(q>(cfg.copies||4)&&!BASIC.test(c?.typeLine||'')&&!specialCopyRule(c)){issues.push({severity:'illegal',card:c?.n||k,reason:'Contains '+q+' copies; '+cfg.label+' normally allows '+(cfg.copies||4)+'.'})}}}
if(format==='brawl'&&commander&&commander.resolved===true&&!commanderEligible(commander))issues.push({severity:'illegal',card:commander.n,reason:'Selected Brawl commander is not verified as commander-eligible.'});
let hasIllegal=issues.some(x=>x.severity==='illegal'),hasUnverified=issues.some(x=>x.severity==='unverified'),hasWarning=issues.some(x=>x.severity==='warning'),status=hasIllegal?'illegal':hasUnverified?'unverified':hasWarning?'warning':'legal';return{version:VERSION,format,label:cfg.label,total,status,counts,issues,checkedAt:new Date().toISOString(),readOnly:true,source:'Current Scryfall card legality + local deck-construction checks'} }
function localQA(){let cmd={n:'Leader',q:1,typeLine:'Legendary Creature — Elf',colorIdentity:['G'],resolved:true,legalities:{commander:'legal'}},forest={n:'Forest',q:40,typeLine:'Basic Land — Forest',colorIdentity:['G'],resolved:true,legalities:{commander:'legal'}},spell={n:'Green Spell',q:59,typeLine:'Sorcery',colorIdentity:['G'],resolved:true,legalities:{commander:'legal'},oracleText:'A deck can have any number of cards named Green Spell.'},ok=validate([cmd,forest,spell],{format:'commander',commander:'Leader'}),bad=validate([{...cmd,legalities:{commander:'banned'}},forest,spell],{format:'commander',commander:'Leader'}),unknown=validate([{...cmd,resolved:false,legalities:{}},{...forest,q:99}],{format:'commander',commander:'Leader'});let checks=[['legal commander deck can pass',ok.status==='legal'],['banned card fails',bad.status==='illegal'],['unresolved is not falsely illegal',unknown.status==='unverified'],['validator is read only',ok.readOnly===true],['version phase67',VERSION.includes('phase67')]];return{ok:checks.every(x=>x[1]),checks}}
return{VERSION,FORMATS,validate,legalState,commanderEligible,colorSubset,combinedIdentity,pairCompatibility,localQA};
});

