
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGResourceRail=api})(typeof self!=='undefined'?self:this,function(){
'use strict';
const VERSION='phase60-smart-resource-rail-1';
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}
function maxCommander(state={},playerId){let max=0,source=null;for(const [k,v] of Object.entries(state.cmd?.[playerId]||{})){let x=Math.max(0,n(v));if(x>max){max=x;source=k}}return{value:max,source}}
function summary(state={},playerId,{tax=null}={}){const id=Number(playerId),cmd=maxCommander(state,id);return{playerId:id,poison:Math.max(0,n(state.poison?.[id])),tax:tax==null?Math.max(0,n(state.tax?.[id])):Math.max(0,n(tax)),casts:Math.max(0,n(state.cmdCasts?.[id])),energy:Math.max(0,n(state.energy?.[id])),experience:Math.max(0,n(state.exp?.[id])),commanderDamage:cmd.value,commanderSource:cmd.source,monarch:state.mon==null?null:Number(state.mon),initiative:state.ini==null?null:Number(state.ini)}}
function primary(s={}){const out=[{key:'poison',label:'Poison',value:n(s.poison),editable:true},{key:'commanderDamage',label:'Cmd Max',value:n(s.commanderDamage),editable:false},{key:'tax',label:'Tax',value:n(s.tax),editable:false}];if(n(s.energy)>0)out.push({key:'energy',label:'Energy',value:n(s.energy),editable:true});if(n(s.experience)>0)out.push({key:'exp',label:'Experience',value:n(s.experience),editable:true});if(n(s.casts)>0&&out.length<5)out.push({key:'cmdCasts',label:'Casts',value:n(s.casts),editable:true});return out.slice(0,5)}
function shared(s={}){return[{key:'monarch',label:'Monarch',holder:s.monarch},{key:'initiative',label:'Initiative',holder:s.initiative}]}
function allResources(s={}){return[{key:'poison',label:'Poison',value:n(s.poison),editable:true},{key:'tax',label:'Commander Tax',value:n(s.tax),editable:false,automatic:true},{key:'cmdCasts',label:'Commander Casts',value:n(s.casts),editable:true},{key:'energy',label:'Energy',value:n(s.energy),editable:true},{key:'exp',label:'Experience',value:n(s.experience),editable:true},{key:'commanderDamage',label:'Max Commander Damage',value:n(s.commanderDamage),editable:false}]}
function localQA(){const st={poison:{1:0},tax:{1:4},cmdCasts:{1:2},energy:{1:0},exp:{1:0},cmd:{1:{a:8,b:18}},mon:2,ini:1},s=summary(st,1,{tax:6}),checks=[];checks.push(['tax override is respected',s.tax===6]);checks.push(['commander damage uses largest single source',s.commanderDamage===18]);checks.push(['commander damage sources do not combine',s.commanderDamage!==26]);checks.push(['primary rail always includes poison',primary(s).some(x=>x.key==='poison')]);checks.push(['primary rail always includes commander damage',primary(s).some(x=>x.key==='commanderDamage')]);checks.push(['primary rail always includes tax',primary(s).some(x=>x.key==='tax')]);checks.push(['zero energy is hidden from primary rail',!primary(s).some(x=>x.key==='energy')]);checks.push(['nonzero energy becomes visible',primary({...s,energy:3}).some(x=>x.key==='energy')]);checks.push(['shared rail reports Monarch holder',shared(s).find(x=>x.key==='monarch').holder===2]);checks.push(['shared rail reports Initiative holder',shared(s).find(x=>x.key==='initiative').holder===1]);checks.push(['automatic tax is not presented as direct editable value',allResources(s).find(x=>x.key==='tax').editable===false]);checks.push(['all resource drawer keeps zero resources available',allResources(s).some(x=>x.key==='energy')]);return{ok:checks.every(x=>x[1]),checks}}
return{VERSION,maxCommander,summary,primary,shared,allResources,localQA};
});

