
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MTGCombatDamageEffects=api})(typeof window!=='undefined'?window:globalThis,function(){
 const VERSION='phase49-combat-damage-effects-1';
 const norm=v=>{try{let n=BigInt(String(v??0).replace(/,/g,''));return n<0n?'0':n.toString()}catch{return'0'}};
 function normalize(state={}){state.combat??={};state.combat.damageEffects=Array.isArray(state.combat.damageEffects)?state.combat.damageEffects:[];return state.combat.damageEffects}
 function targetKey(t){return t?.kind==='player'?'p:'+Number(t.playerId):t?.kind==='object'?'o:'+String(t.objectId||''):''}
 function scopeMatches(effect,a){const s=effect?.scope||{};if(s.sourceObjectId&&String(s.sourceObjectId)!==String(a?.sourceObjectId))return false;if(s.target&&targetKey(s.target)!==targetKey(a?.target))return false;return true}
 function validTarget(state,t){if(t?.kind==='player')return Number(t.playerId)>0;if(t?.kind==='object')return !!String(t.objectId||'')&&(state.battle||[]).some(o=>String(o.id)===String(t.objectId));return false}
 function normalizeEffect(e={}){let kind=String(e.kind||'prevent');if(!['prevent','redirect'].includes(kind))kind='prevent';return{effectId:String(e.effectId||''),kind,scope:e.scope&&typeof e.scope==='object'?JSON.parse(JSON.stringify(e.scope)):{},remainingAmount:kind==='prevent'?norm(e.remainingAmount??e.amount??0):'0',toTarget:kind==='redirect'&&e.toTarget?JSON.parse(JSON.stringify(e.toTarget)):null,oneShot:e.oneShot!==false,used:!!e.used,order:Number(e.order||0)}}
 function preview(state,a){const effects=normalize(state).map(normalizeEffect).sort((x,y)=>x.order-y.order);let amount=BigInt(norm(a?.amount)),target=a?.target?JSON.parse(JSON.stringify(a.target)):null,prevented=0n,applied=[];for(const e of effects){if(e.used||!scopeMatches(e,a))continue;if(e.kind==='redirect'&&validTarget(state,e.toTarget)){target=JSON.parse(JSON.stringify(e.toTarget));applied.push({effectId:e.effectId,kind:e.kind,amount:'0',toTarget:target});continue}if(e.kind==='prevent'){let cap=BigInt(norm(e.remainingAmount)),take=cap<amount?cap:amount;if(take>0n){amount-=take;prevented+=take;applied.push({effectId:e.effectId,kind:e.kind,amount:take.toString()})}}}return{assignmentId:String(a?.assignmentId||''),originalAmount:norm(a?.amount),effectiveAmount:amount.toString(),prevented:prevented.toString(),originalTarget:a?.target||null,finalTarget:target,appliedEffects:applied}}
 function summary(state){const effects=normalize(state).map(normalizeEffect);return{count:effects.length,prevent:effects.filter(e=>e.kind==='prevent'&&!e.used).length,redirect:effects.filter(e=>e.kind==='redirect'&&!e.used).length,effects}}
 function localQA(engine){let st=engine.normalizeState({life:{1:40,2:40,3:40},battle:[{id:'a',name:'QA Attacker',owner:1,controllerId:1,typeLine:'Creature',combatMeta:{power:'7',toughness:'7',traits:{}}}],combat:{active:true,attackers:[{objectId:'a',defender:{kind:'player',playerId:2},blocked:false}],blockers:[],damageAssignments:[],damageResolved:false},events:[],snapshots:[],feed:[]});const emit=(type,payload,actor=1)=>engine.reduce(st,engine.makeEvent(st,type,payload,actor,{source:'qa'}));emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'qa',sourceObjectId:'a',target:{kind:'player',playerId:2},amount:'7'});emit('COMBAT_DAMAGE_EFFECT_ADDED',{effectId:'shield',kind:'prevent',amount:'3',scope:{target:{kind:'player',playerId:2}},oneShot:true,order:1});let p=preview(st,st.combat.damageAssignments[0]),checks=[['prevention preview reduces exact damage',p.effectiveAmount==='4'&&p.prevented==='3']];emit('COMBAT_DAMAGE_RESOLVED',{});checks.push(['prevention changes resolved player damage',Number(st.life[2])===36],['one-shot prevention is consumed',st.combat.damageEffects.find(e=>e.effectId==='shield')?.used===true]);emit('COMBAT_DAMAGE_CLEARED',{});emit('COMBAT_OBJECT_STATS_SET',{objectId:'a',power:'5',toughness:'7'});emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'qa2',sourceObjectId:'a',target:{kind:'player',playerId:2},amount:'5'});emit('COMBAT_DAMAGE_EFFECT_ADDED',{effectId:'redirect',kind:'redirect',toTarget:{kind:'player',playerId:3},scope:{sourceObjectId:'a'},oneShot:true,order:1});p=preview(st,st.combat.damageAssignments[0]);checks.push(['redirect preview changes target',p.finalTarget?.playerId===3]);emit('COMBAT_DAMAGE_RESOLVED',{});checks.push(['redirect applies damage to replacement target',Number(st.life[3])===35&&Number(st.life[2])===36]);emit('COMBAT_DAMAGE_EFFECTS_CLEARED',{});checks.push(['effects clear authoritatively',summary(st).count===0]);return{ok:checks.every(x=>x[1]),checks,state:st}}
 return{VERSION,norm,normalize,targetKey,scopeMatches,validTarget,normalizeEffect,preview,summary,localQA}
});

