
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MTGAttachments=api})(typeof window!=='undefined'?window:globalThis,function(){
 const VERSION='phase40-attachments-1';
 function clone(x){return JSON.parse(JSON.stringify(x))}
 function normalize(state={}){state.attachments??={};state.attachments.links??={};const links={};for(const [source,target] of Object.entries(state.attachments.links||{})){const s=String(source||''),t=String(target||'');if(s&&t&&s!==t)links[s]=t}state.attachments.links=links;if(!state.attachments.pendingAuraSba||typeof state.attachments.pendingAuraSba!=='object'||Array.isArray(state.attachments.pendingAuraSba))state.attachments.pendingAuraSba={};return state.attachments}
 function targetOf(state,sourceId){normalize(state);return state.attachments.links[String(sourceId||'')]||null}
 function childrenOf(state,targetId){normalize(state);const id=String(targetId||'');return Object.entries(state.attachments.links).filter(([,t])=>t===id).map(([s])=>s)}
 function isAttached(state,sourceId){return !!targetOf(state,sourceId)}
 function wouldCycle(state,sourceId,targetId){normalize(state);let s=String(sourceId||''),cur=String(targetId||''),seen=new Set();if(!s||!cur||s===cur)return true;while(cur){if(cur===s)return true;if(seen.has(cur))return true;seen.add(cur);cur=state.attachments.links[cur]||''}return false}
 function canAttach(state,sourceId,targetId){const s=String(sourceId||''),t=String(targetId||'');if(!s||!t||s===t)return false;const battle=state.battle||[],source=battle.find(o=>String(o.id)===s),target=battle.find(o=>String(o.id)===t);if(!source||!target||globalThis.MTGPhasing?.isPhasedOut(source)||globalThis.MTGPhasing?.isPhasedOut(target))return false;if(globalThis.MTGProtectionRules&&!globalThis.MTGProtectionRules.attachmentLegality(state,source,target).legal)return false;return !wouldCycle(state,s,t)}
 function attachIntent(sourceObjectId,targetObjectId){return{type:'OBJECT_ATTACHED',payload:{sourceObjectId:String(sourceObjectId),targetObjectId:String(targetObjectId)}}}
 function detachIntent(sourceObjectId){return{type:'OBJECT_DETACHED',payload:{sourceObjectId:String(sourceObjectId)}}}
 function summary(state,objectId){normalize(state);const id=String(objectId||''),target=targetOf(state,id),children=childrenOf(state,id),battle=state.battle||[],name=x=>battle.find(o=>String(o.id)===String(x))?.name||String(x);return{objectId:id,targetObjectId:target,targetName:target?name(target):null,attachedObjectIds:children,attachedNames:children.map(name)}}
 function localQA(engine){let st=engine.normalizeState({battle:[{id:'a',name:'QA Aura',owner:1,controllerId:1,typeLine:'Enchantment — Aura'},{id:'b',name:'QA Creature',owner:1,controllerId:1,typeLine:'Creature'},{id:'c',name:'QA Equipment',owner:1,controllerId:1,typeLine:'Artifact — Equipment'}],attachments:{links:{}},events:[],snapshots:[],feed:[]});const emit=(type,payload)=>engine.reduce(st,engine.makeEvent(st,type,payload,1,{source:'qa'}));emit('OBJECT_ATTACHED',{sourceObjectId:'a',targetObjectId:'b'});emit('OBJECT_ATTACHED',{sourceObjectId:'c',targetObjectId:'b'});let checks=[['first attachment tracked',targetOf(st,'a')==='b'],['multiple children supported',childrenOf(st,'b').length===2],['cycle prevented',!canAttach(st,'b','a')]];emit('OBJECT_DETACHED',{sourceObjectId:'a'});checks.push(['detach removes link',!targetOf(st,'a')]);emit('OBJECT_ATTACHED',{sourceObjectId:'a',targetObjectId:'b'});emit('OBJECT_ZONE_CHANGED',{objectId:'b',toZone:'graveyard'});checks.push(['target zone change detaches children',!targetOf(st,'a')&&!targetOf(st,'c')]);checks.push(['target zone change records surviving Aura for SBA',!!st.attachments.pendingAuraSba?.a]);checks.push(['target zone change does not queue Equipment for Aura SBA',!st.attachments.pendingAuraSba?.c]);let auraPlan=globalThis.MTGStateBasedActions?.plan?globalThis.MTGStateBasedActions.plan(st):{attachmentActions:[]};checks.push(['unattached Aura is scheduled by existing SBA planner',auraPlan.attachmentActions.some(x=>x.kind==='aura-graveyard'&&x.sourceObjectId==='a')]);if(globalThis.MTGStateBasedActions){emit('STATE_BASED_ACTIONS_APPLIED',{objectIds:[]});checks.push(['unattached Aura moves to owner graveyard while Equipment survives',st.zones.graveyard.some(x=>x.id==='a')&&st.battle.some(x=>x.id==='c')])}return{ok:checks.every(x=>x[1]),checks,state:st}}
 return{VERSION,normalize,targetOf,childrenOf,isAttached,wouldCycle,canAttach,attachIntent,detachIntent,summary,localQA}
});

