
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGBattlefieldBoard=api})(typeof self!=='undefined'?self:this,function(){
'use strict';
const VERSION='phase66-public-board-library-1';
const controllerId=o=>Number(o?.controllerId??o?.owner??0);
const isLand=o=>String(o?.type||o?.typeLine||'').toLowerCase().includes('land');
const isCommander=o=>!!(o?.isCommander||o?.commanderId);
const nonneg=v=>Math.max(0,Math.floor(Number(v)||0));
function zoneForPlayer(state={},zone,playerId){const id=Number(playerId);return (state.zones?.[zone]||[]).filter(o=>Number(o.owner??o.controllerId??0)===id)}
function battlefieldForPlayer(state={},playerId){const id=Number(playerId);return (state.battle||[]).filter(o=>controllerId(o)===id)}
function commanderCount(player={}){const n=nonneg(player.commanderCount||0);if(n)return n;if(Array.isArray(player.commanders)&&player.commanders.length)return player.commanders.length;return player.commander?1:0}
function deckSize(player={}){const n=nonneg(player.deckSize||player.deckCount||0);return n||100}
function openingHandSize({mulligans=0,multiplayer=true,startingHand=7}={}){const m=nonneg(mulligans),bottom=multiplayer?Math.max(0,m-1):m;return Math.max(0,nonneg(startingHand)-bottom)}
function openingLibraryCount(player={},setup={}){const total=deckSize(player),commanders=nonneg(setup.commanderCount??commanderCount(player)),hand=openingHandSize(setup);return Math.max(0,total-commanders-hand)}
function libraryRecord(state={},playerId){const raw=state.libraryCounts?.[Number(playerId)]??state.libraryCounts?.[String(playerId)]??null;if(raw==null)return null;if(typeof raw==='number')return{value:nonneg(raw),exact:true,confirmed:true,source:'tracked'};return{value:nonneg(raw.value),exact:raw.exact!==false,confirmed:raw.confirmed!==false,source:String(raw.source||'tracked'),mulligans:nonneg(raw.mulligans),openingHand:raw.openingHand==null?null:nonneg(raw.openingHand),deckSize:raw.deckSize==null?null:nonneg(raw.deckSize),commanderCount:raw.commanderCount==null?null:nonneg(raw.commanderCount),draws:nonneg(raw.draws),manualAdjustments:nonneg(raw.manualAdjustments)}}
function libraryEstimate(state={},player={},ctx={}){const id=Number(player.id),tracked=libraryRecord(state,id);if(tracked)return tracked;const total=deckSize(player),cmds=commanderCount(player),knownDeck=Number(player.deckSize||player.deckCount||0)>0,hand=7;let value=Math.max(0,total-cmds-hand);return{value,exact:false,confirmed:false,source:knownDeck?'opening-estimate':'commander-default',deckSize:total,commanderCount:cmds,openingHand:hand,mulligans:0,draws:0,manualAdjustments:0}}
function summarize(state={},player={},opts={}){const id=Number(player.id),battle=battlefieldForPlayer(state,id),battlefieldCommanders=battle.filter(isCommander),lands=battle.filter(o=>isLand(o)&&!isCommander(o)),nonlands=battle.filter(o=>!isLand(o)&&!isCommander(o)),command=zoneForPlayer(state,'command',id),graveyard=zoneForPlayer(state,'graveyard',id),exile=zoneForPlayer(state,'exile',id);const library=libraryEstimate(state,player,{battle,graveyard,exile,command,...opts});return{playerId:id,name:String(player.name||('Player '+id)),commander:String(player.commander||battlefieldCommanders[0]?.name||command.find(isCommander)?.name||'Commander'),battlefield:nonlands,battlefieldCommanders,lands,totalLands:lands.length,tappedLands:lands.filter(x=>x.tapped).length,untappedLands:lands.filter(x=>!x.tapped).length,command,graveyard,exile,library};}
function spatialCards(players=[],viewerId,layoutFn){const active=players.filter(p=>p&&p.connected!==false);if(typeof layoutFn==='function')return layoutFn(active,viewerId);return active.map(p=>({...p,spatialSlot:Number(p.id)===Number(viewerId)?'you':'flat'}));}
function localQA(){const st={battle:[{id:'l1',owner:1,controllerId:1,type:'Land',tapped:true},{id:'l2',owner:1,type:'Basic Land',tapped:false},{id:'c1',owner:1,type:'Creature',name:'Bear'},{id:'fieldcmd',owner:1,type:'Creature',name:'Field Leader',isCommander:true,tapped:false},{id:'x',owner:2,type:'Land'}],zones:{command:[{id:'cmd',owner:1,name:'Leader',isCommander:true}],graveyard:[{id:'g',owner:1,name:'Gone'}],exile:[{id:'e',owner:1,name:'Exiled'}]},libraryCounts:{1:{value:71,exact:true,confirmed:true,mulligans:1,openingHand:7,deckSize:100,commanderCount:1,draws:20}}};const s=summarize(st,{id:1,name:'One',commander:'Leader',deckSize:100,commanderCount:1}),checks=[];checks.push(['lands separated from battlefield',s.battlefield.length===1&&s.lands.length===2]);checks.push(['only battlefield commander is in commander presentation list',s.battlefieldCommanders.length===1&&!s.battlefield.some(x=>x.id==='fieldcmd')]);checks.push(['command-zone commander is not a battlefield commander',!s.battlefieldCommanders.some(x=>x.id==='cmd')]);checks.push(['tapped land count',s.tappedLands===1]);checks.push(['untapped land count',s.untappedLands===1]);checks.push(['tracked library count exact',s.library.value===71&&s.library.exact&&s.library.confirmed]);checks.push(['one-commander keep seven starts library at 92',openingLibraryCount({deckSize:100,commanderCount:1},{mulligans:0,multiplayer:true,commanderCount:1})===92]);checks.push(['first multiplayer mulligan is free',openingLibraryCount({deckSize:100,commanderCount:1},{mulligans:1,multiplayer:true,commanderCount:1})===92]);checks.push(['second multiplayer mulligan keeps six',openingLibraryCount({deckSize:100,commanderCount:1},{mulligans:2,multiplayer:true,commanderCount:1})===93]);checks.push(['two commanders leave 91 after opening seven',openingLibraryCount({deckSize:100,commanderCount:2},{mulligans:0,multiplayer:true,commanderCount:2})===91]);checks.push(['unconfirmed deck gets estimate instead of fake exact',summarize({...st,libraryCounts:{}},{id:1,deckSize:100,commanderCount:1}).library.exact===false]);checks.push(['opponent battlefield excluded',!s.lands.some(x=>x.id==='x')]);checks.push(['graveyard filtered by owner',s.graveyard.length===1]);checks.push(['exile filtered by owner',s.exile.length===1]);checks.push(['module version identifies Phase 66',VERSION.includes('phase66')]);return{ok:checks.every(x=>x[1]),checks}}
return{VERSION,isLand,isCommander,zoneForPlayer,battlefieldForPlayer,summarize,libraryEstimate,libraryRecord,deckSize,commanderCount,openingHandSize,openingLibraryCount,spatialCards,localQA};
});
