
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGPlayerAlerts=api})(typeof self!=='undefined'?self:this,function(){
'use strict';
const VERSION='phase57-critical-player-awareness-1';
function n(v,d=0){v=Number(v);return Number.isFinite(v)?v:d}
function incomingCommanderDamage(state={},playerId){const ledger=state.cmd?.[playerId]||{};let max=0,source=null;for(const [k,v] of Object.entries(ledger)){const amount=Math.max(0,n(v));if(amount>max){max=amount;source=k}}return{max,source,remaining:Math.max(0,21-max)}}
function poisonBand(poison){poison=Math.max(0,n(poison));if(poison>=10)return'fallen';if(poison>=9)return'critical';if(poison>=8)return'danger';if(poison>=5)return'visible';if(poison>=1)return'subtle';return'none'}
function lifeBand(life){life=n(life,40);if(life<=0)return'fallen';if(life<=3)return'last-stand';if(life<=10)return'low';return'normal'}
function commanderBand(amount){amount=Math.max(0,n(amount));if(amount>=21)return'fallen';if(amount>=20)return'last-stand';if(amount>=18)return'critical';if(amount>=11)return'warning';return'subtle'}
function evaluate(state={},playerId){const life=n(state.life?.[playerId],40),poison=Math.max(0,n(state.poison?.[playerId])),cmd=incomingCommanderDamage(state,playerId),fallen=!!state.fallen?.[playerId];const reasons=[];if(life>0&&life<=3)reasons.push({kind:'life',label:'LOW LIFE',value:life,severity:'critical'});if(poison===9)reasons.push({kind:'poison',label:'9 POISON',value:poison,severity:'critical'});if(cmd.max===20)reasons.push({kind:'commander',label:'20 COMMANDER DAMAGE',value:cmd.max,source:cmd.source,severity:'critical'});const lastStand=!fallen&&reasons.length>0;return{playerId:Number(playerId),life,poison,fallen,lifeBand:lifeBand(life),poisonBand:poisonBand(poison),commanderDamage:cmd.max,commanderSource:cmd.source,commanderRemaining:cmd.remaining,commanderBand:commanderBand(cmd.max),lastStand,reasons,critical:lastStand||poison>=8||cmd.max>=18||life<=10}}
function transition(previous,current){if(!current)return[];const out=[];if(current.lastStand&&!previous?.lastStand)out.push({id:'last-stand',title:'LAST STAND',detail:current.reasons.map(x=>x.label).join(' · '),severity:'critical'});if(current.poisonBand==='danger'&&previous?.poisonBand!=='danger'&&previous?.poisonBand!=='critical'&&previous?.poisonBand!=='fallen')out.push({id:'poison-danger',title:'POISON DANGER',detail:'Two poison counters from defeat.',severity:'warning'});if(current.commanderBand==='critical'&&!['critical','last-stand','fallen'].includes(previous?.commanderBand))out.push({id:'commander-critical',title:'COMMANDER DAMAGE CRITICAL',detail:current.commanderRemaining+' damage from one commander remains.',severity:'warning'});if(current.lifeBand==='low'&&previous?.lifeBand==='normal')out.push({id:'low-life',title:'LIFE TOTAL CRITICAL',detail:current.life+' life remaining.',severity:'warning'});if(previous?.lastStand&&!current.lastStand&&!current.fallen&&current.life>3&&current.poison<9&&current.commanderDamage<20)out.push({id:'recovered',title:'SECOND WIND',detail:'You moved out of immediate loss range.',severity:'recovery'});return out}
function publicSummary(status){if(!status)return null;return{lifeBand:status.lifeBand,poisonBand:status.poisonBand,commanderBand:status.commanderBand,fallen:status.fallen}}
function localQA(){const base={life:{1:40},poison:{1:0},cmd:{1:{}},fallen:{1:false}};const checks=[];checks.push(['healthy player is normal',evaluate(base,1).lifeBand==='normal']);checks.push(['three life is last stand',evaluate({...base,life:{1:3}},1).lastStand]);checks.push(['nine poison is last stand',evaluate({...base,poison:{1:9}},1).lastStand]);checks.push(['twenty commander is last stand',evaluate({...base,cmd:{1:{cmd_a:20}}},1).lastStand]);checks.push(['commander sources remain separate',incomingCommanderDamage({...base,cmd:{1:{a:14,b:20}}},1).source==='b']);checks.push(['eight poison is danger not last stand',evaluate({...base,poison:{1:8}},1).poisonBand==='danger'&&!evaluate({...base,poison:{1:8}},1).lastStand]);checks.push(['commander 18 is critical',evaluate({...base,cmd:{1:{a:18}}},1).commanderBand==='critical']);checks.push(['last stand transition fires once',transition(evaluate(base,1),evaluate({...base,life:{1:2}},1)).some(x=>x.id==='last-stand')]);checks.push(['same last stand does not repeat',!transition(evaluate({...base,life:{1:2}},1),evaluate({...base,life:{1:1}},1)).some(x=>x.id==='last-stand')]);checks.push(['recovery can be detected',transition(evaluate({...base,life:{1:2}},1),evaluate({...base,life:{1:12}},1)).some(x=>x.id==='recovered')]);checks.push(['public summary omits commander source',!('commanderSource' in publicSummary(evaluate({...base,cmd:{1:{secret:18}}},1)))]);checks.push(['fallen state is preserved',evaluate({...base,fallen:{1:true}},1).fallen]);return{ok:checks.every(x=>x[1]),checks}}
return{VERSION,incomingCommanderDamage,poisonBand,lifeBand,commanderBand,evaluate,transition,publicSummary,localQA};
});

