
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MTGCombatDamage=api})(typeof window!=='undefined'?window:globalThis,function(){
 const VERSION='phase42-combat-damage-foundation-1';
 function normAmount(v){try{let n=BigInt(String(v??0).replace(/,/g,''));return n<0n?'0':n.toString()}catch{return'0'}}
 function normalize(state={}){state.combat??={};state.combat.damageAssignments=Array.isArray(state.combat.damageAssignments)?state.combat.damageAssignments:[];state.combat.damageResolved=!!state.combat.damageResolved;return state.combat}
 function keyTarget(t){return t?.kind==='player'?'p:'+Number(t.playerId):t?.kind==='object'?'o:'+String(t.objectId||''):''}
 function validTarget(state,t){if(!t)return false;if(t.kind==='player')return Number(t.playerId)>0;if(t.kind==='object')return !!String(t.objectId||'')&&(state.battle||[]).some(o=>String(o.id)===String(t.objectId)&&!globalThis.MTGPhasing?.isPhasedOut(o));return false}
 function assignmentsFor(state,sourceObjectId){normalize(state);return state.combat.damageAssignments.filter(a=>String(a.sourceObjectId)===String(sourceObjectId))}
 function totalAssigned(state,sourceObjectId){return assignmentsFor(state,sourceObjectId).reduce((n,a)=>n+BigInt(normAmount(a.amount)),0n).toString()}
 function damageMarked(object){return normAmount(object?.damageMarked||0)}
 function assignmentIntent(sourceObjectId,target,amount,assignmentId){return{type:'COMBAT_DAMAGE_ASSIGNED',payload:{assignmentId:assignmentId||null,sourceObjectId:String(sourceObjectId),target:{...target},amount:normAmount(amount)}}}
 function resolveIntent(){return{type:'COMBAT_DAMAGE_RESOLVED',payload:{}}}
 function summary(state){normalize(state);return{assignments:state.combat.damageAssignments.slice(),resolved:state.combat.damageResolved,total:state.combat.damageAssignments.reduce((n,a)=>n+BigInt(normAmount(a.amount)),0n).toString()}}
 function localQA(engine){let st=engine.normalizeState({life:{1:40,2:40},battle:[{id:'a',name:'QA Attacker',owner:1,controllerId:1,typeLine:'Creature',combatMeta:{power:'5',toughness:'5',traits:{trample:true}}},{id:'b',name:'QA Blocker',owner:2,controllerId:2,typeLine:'Creature',combatMeta:{power:'3',toughness:'3',traits:{}}}],combat:{active:true,attackers:[{objectId:'a',defender:{kind:'player',playerId:2},blocked:true}],blockers:[{blockerObjectId:'b',attackerObjectId:'a'}]},events:[],snapshots:[],feed:[]});const emit=(type,payload,actor=1)=>engine.reduce(st,engine.makeEvent(st,type,payload,actor,{source:'qa'}));emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'qa1b',sourceObjectId:'a',target:{kind:'object',objectId:'b'},amount:'3'});emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'qa1p',sourceObjectId:'a',target:{kind:'player',playerId:2},amount:'2'});emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'qa2',sourceObjectId:'b',target:{kind:'object',objectId:'a'},amount:'3'},2);let checks=[['three legal assignments tracked',st.combat.damageAssignments.length===3],['exact assignment total preserved',summary(st).total==='8'],['unresolved before resolution',st.combat.damageResolved===false]];emit('COMBAT_DAMAGE_RESOLVED',{});checks.push(['trample combat damage changes player life',Number(st.life[2])===38],['permanent combat damage is marked',damageMarked(st.battle.find(o=>o.id==='a'))==='3'],['batch resolves once',st.combat.damageResolved===true]);emit('COMBAT_DAMAGE_RESOLVED',{});checks.push(['repeat resolution is idempotent',Number(st.life[2])===38&&damageMarked(st.battle.find(o=>o.id==='a'))==='3']);emit('COMBAT_DAMAGE_CLEARED',{});checks.push(['damage assignments clear',!st.combat.damageAssignments.length&&!st.combat.damageResolved]);emit('COMBAT_DAMAGE_ASSIGNED',{assignmentId:'qa3',sourceObjectId:'a',target:{kind:'object',objectId:'b'},amount:'2'});emit('OBJECT_ZONE_CHANGED',{objectId:'b',toZone:'graveyard'});checks.push(['zone change removes stale damage target',!st.combat.damageAssignments.length]);return{ok:checks.every(x=>x[1]),checks,state:st}}
 return{VERSION,normAmount,normalize,keyTarget,validTarget,assignmentsFor,totalAssigned,damageMarked,assignmentIntent,resolveIntent,summary,localQA}
});

