
/* Phase 87 — conservative layer/timestamp/dependency engine. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGLayerEngine=api})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const VERSION='phase87-layer-dependency-engine-1';
const SAFE_TRAITS=['deathtouch','trample','vigilance','firstStrike','doubleStrike','flying','reach','menace','lifelink','indestructible'];
const clone=x=>JSON.parse(JSON.stringify(x));const lc=v=>String(v||'').trim().toLowerCase();const ctrl=o=>Number(o?.controllerId??o?.owner??0)||0;
function bi(v,f=0n){try{return BigInt(String(v??f).replace(/,/g,''))}catch{return f}}
function typesOf(o={}){let line=String(o.typeLine||o.type||''),front=line.split(/[—-]/)[0]||'';return [...new Set(front.trim().split(/\s+/).filter(Boolean))]}
function subsOf(o={}){if(Array.isArray(o.sub))return o.sub.slice();if(Array.isArray(o.subtypes))return o.subtypes.slice();let line=String(o.typeLine||'').split(/[—-]/);return line.length>1?line.slice(1).join('-').trim().split(/\s+/).filter(Boolean):[]}
function colorsOf(o={}){return Array.isArray(o.colors)?o.colors.slice():[]}
function normalize(e={},source=null,index=0){let kind=String(e.kind||'manual'),layer=String(e.layer||({
 'copy-public':'1a','control-set':'2','type-set':'4','type-add':'4','subtype-add':'4','color-set':'5','color-add':'5','keyword-grant':'6','keyword-remove':'6','ability-remove-all':'6','pt-set':'7b','pt-mod':'7c','pt-switch':'7d'
}[kind]||'manual'));return{...clone(e),id:(source?.id?('static:'+String(source.id)+':layer:'+String(e.id||e.effectId||('layerfx_'+index))):('state:layer:'+String(e.id||e.effectId||('layerfx_'+index)))),rawEffectId:String(e.id||e.effectId||('layerfx_'+index)),kind,layer,scope:e.scope&&typeof e.scope==='object'?clone(e.scope):{},sourceObjectId:e.sourceObjectId?String(e.sourceObjectId):(source?.id?String(source.id):null),sourceController:Number(e.sourceController??(source?ctrl(source):0))||0,sourceCopies:bi(e.sourceCopies??source?.q??1n,1n).toString(),timestamp:Number(e.timestamp??source?.order??index??0),automation:e.automation==='exact'?'exact':'manual',traits:Array.isArray(e.traits)?e.traits.map(String):[],types:Array.isArray(e.types)?e.types.map(String):[],subtypes:Array.isArray(e.subtypes)?e.subtypes.map(String):[],colors:Array.isArray(e.colors)?e.colors.map(String):[]}}
function gather(state={}){let out=[],i=0,seen=new Set();for(const source of state.battle||[]){if(globalThis.MTGPhasing?.isPhasedOut(source))continue;for(const raw of source.continuousEffects||[]){let e=normalize(raw,source,i++),base=e.id;e.rawId=base;e.id='static:'+String(source.id||'source')+':cont:'+base;if(seen.has(e.id))e.id=e.id+':'+i;seen.add(e.id);out.push(e)}}for(const raw of state.continuousEffects||[]){let e=normalize(raw,null,i++);if(seen.has(e.id))e.id='state:cont:'+e.id;seen.add(e.id);out.push(e)}return out}
function rank(layer){return{'1a':10,'1b':11,'2':20,'3':30,'4':40,'5':50,'6':60,'7a':70,'7b':71,'7c':72,'7d':73}[String(layer)]??999}
function charBase(o={}){let v=root.MTGCardForms?.characteristics?root.MTGCardForms.characteristics(o):o,m=v.combatMeta||{},p=m.power??v.power,t=m.toughness??v.toughness;return{id:String(v.id||o.id||''),name:String(v.name||''),owner:Number(v.owner||o.owner||0),controllerId:ctrl(v),typeLine:String(v.typeLine||v.type||''),types:typesOf(v),subtypes:subsOf(v),colors:colorsOf(v),traits:{...(m.traits||{})},power:p==null||String(p).trim()===''?null:bi(p).toString(),toughness:t==null||String(t).trim()===''?null:bi(t).toString(),abilitiesRemoved:false}}
function has(arr,v){v=lc(v);return !v||(arr||[]).some(x=>lc(x)===v)}
function scopeReads(e={}){let s=e.scope||{},x=[];if(s.controller)x.push('controller');if(s.type)x.push('type');if(s.subtype)x.push('subtype');if(s.color)x.push('color');if(s.trait)x.push('trait');return x}
function changes(e={}){switch(e.kind){case'copy-public':return['controller','type','subtype','color','trait','power','toughness'];case'control-set':return['controller'];case'type-set':case'type-add':return['type'];case'subtype-add':return['subtype'];case'color-set':case'color-add':return['color'];case'keyword-grant':case'keyword-remove':case'ability-remove-all':return['trait'];case'pt-set':case'pt-mod':case'pt-switch':return['power','toughness'];default:return[]}}
function applies(e={},ch={},target={}){let s=e.scope||{},sc=Number(e.sourceController||0);if(s.objectId&&String(s.objectId)!==String(target.id||ch.id))return false;if(s.another&&e.sourceObjectId&&String(e.sourceObjectId)===String(target.id||ch.id))return false;if(s.controller==='you'&&sc&&Number(ch.controllerId)!==sc)return false;if(s.controller==='opponent'&&sc&&Number(ch.controllerId)===sc)return false;if(s.type&&!has(ch.types,s.type))return false;if(s.subtype&&!has(ch.subtypes,s.subtype))return false;if(s.color&&!has(ch.colors,s.color))return false;if(s.token===true&&!target.token)return false;if(s.token===false&&target.token)return false;if(s.trait&&!ch.traits?.[s.trait])return false;return true}
function depends(a={},b={}){if(rank(a.layer)!==rank(b.layer))return false;let reads=new Set(scopeReads(a)),writes=new Set(changes(b));for(const k of reads)if(writes.has(k))return true;return false}
function dependencyOrder(effects=[]){let left=effects.slice(),out=[],edges=[],loop=false;while(left.length){let ready=left.filter(a=>!left.some(b=>a!==b&&depends(a,b)));if(!ready.length){loop=true;ready=[left.slice().sort((a,b)=>a.timestamp-b.timestamp||a.id.localeCompare(b.id))[0]]}ready.sort((a,b)=>a.timestamp-b.timestamp||a.id.localeCompare(b.id));let pick=ready[0];for(const b of left)if(b!==pick&&depends(b,pick))edges.push([pick.id,b.id]);out.push(pick);left=left.filter(x=>x!==pick)}return{order:out,edges,loop}}
function applyOne(state,ch,target,e,review,trace){if(e.automation!=='exact'){review.push(e.id);return}if(!applies(e,ch,target))return;let copies=bi(e.sourceCopies,1n);if(copies<1n)copies=1n;switch(e.kind){
 case'copy-public':{let src=(state.battle||[]).find(x=>String(x.id)===String(e.copyFromObjectId||e.fromObjectId||''));if(!src){review.push(e.id);return}let c=charBase(src);ch.name=c.name;ch.typeLine=c.typeLine;ch.types=c.types;ch.subtypes=c.subtypes;ch.colors=c.colors;ch.traits={...c.traits};ch.power=c.power;ch.toughness=c.toughness;break}
 case'control-set':{let id=Number(e.controllerId||e.newControllerId||0);if(!id){review.push(e.id);return}ch.controllerId=id;break}
 case'type-set':if(!e.types.length){review.push(e.id);return}else ch.types=[...new Set(e.types)];break;
 case'type-add':ch.types=[...new Set([...ch.types,...e.types])];break;
 case'subtype-add':ch.subtypes=[...new Set([...ch.subtypes,...e.subtypes])];break;
 case'color-set':ch.colors=[...new Set(e.colors)];break;
 case'color-add':ch.colors=[...new Set([...ch.colors,...e.colors])];break;
 case'keyword-grant':for(const k of e.traits.filter(x=>SAFE_TRAITS.includes(x)))ch.traits[k]=true;break;
 case'keyword-remove':for(const k of e.traits.filter(x=>SAFE_TRAITS.includes(x)))ch.traits[k]=false;break;
 case'ability-remove-all':review.push(e.id);return;
 case'pt-set':if(e.power==null||e.toughness==null){review.push(e.id);return}else{ch.power=bi(e.power).toString();ch.toughness=bi(e.toughness).toString()}break;
 case'pt-mod':if(ch.power!==null)ch.power=(bi(ch.power)+bi(e.powerDelta)*copies).toString();if(ch.toughness!==null)ch.toughness=(bi(ch.toughness)+bi(e.toughnessDelta)*copies).toString();break;
 case'pt-switch':{let x=ch.power;ch.power=ch.toughness;ch.toughness=x;break}
 default:review.push(e.id);return
 }trace.push({id:e.id,layer:e.layer,kind:e.kind})}
function derived(state={},target={}){let ch=charBase(target),review=[],trace=[],deps=[],loops=[];if(globalThis.MTGPhasing?.isPhasedOut(target))return{...ch,damageMarked:String(target.damageMarked??'0'),deathtouchMarked:!!target.deathtouchMarked,appliedEffects:[],layerTrace:[],dependencies:[],reviewRequired:false,reviewEffects:[],phasedOut:true};let all=gather(state),plus=bi(target.c?.['+1/+1']||0),minus=bi(target.c?.['-1/-1']||0),hasPublicPTCounters=(plus!==0n||minus!==0n),ranks=[...new Set([...all.map(e=>rank(e.layer)),...(hasPublicPTCounters?[72]:[])])].sort((a,b)=>a-b);for(const r of ranks){let group=all.filter(e=>rank(e.layer)===r),ord=dependencyOrder(group);deps.push(...ord.edges);if(ord.loop)loops.push(String(r));for(const e of ord.order)applyOne(state,ch,target,e,review,trace);if(r===72&&hasPublicPTCounters&&ch.power!==null&&ch.toughness!==null){let delta=plus-minus;ch.power=(bi(ch.power)+delta).toString();ch.toughness=(bi(ch.toughness)+delta).toString();trace.push({id:'public-counters:'+String(target.id||''),layer:'7c',kind:'pt-counters'})}}if(loops.length)review.push(...loops.map(x=>'dependency-loop:'+x));return{...ch,damageMarked:String(target.damageMarked??'0'),deathtouchMarked:!!target.deathtouchMarked,appliedEffects:trace.map(x=>x.id),layerTrace:trace,dependencies:deps,reviewRequired:review.length>0,reviewEffects:[...new Set(review)]}}
function summary(state={}){let a=gather(state);return{count:a.length,layers:[...new Set(a.map(x=>x.layer))],manual:a.filter(x=>x.automation!=='exact').length}}
function localQA(){let c=[],q=(n,v)=>c.push([n,!!v]);let target={id:'t',owner:1,controllerId:1,typeLine:'Artifact',sub:[],colors:[],combatMeta:{power:'2',toughness:'3',traits:{}},c:{'+1/+1':'1'}};let st={battle:[target],continuousEffects:[
{id:'makeCreature',kind:'type-add',layer:'4',scope:{objectId:'t'},types:['Creature'],timestamp:5,automation:'exact'},
{id:'zombieIfCreature',kind:'subtype-add',layer:'4',scope:{objectId:'t',type:'Creature'},subtypes:['Zombie'],timestamp:1,automation:'exact'},
{id:'setPT',kind:'pt-set',layer:'7b',scope:{objectId:'t'},power:'1',toughness:'4',timestamp:1,automation:'exact'},
{id:'buff',kind:'pt-mod',layer:'7c',scope:{objectId:'t'},powerDelta:'2',toughnessDelta:'0',timestamp:2,automation:'exact'},
{id:'switch',kind:'pt-switch',layer:'7d',scope:{objectId:'t'},timestamp:3,automation:'exact'}]};let d=derived(st,target);q('layer order applies type before PT',d.types.includes('Creature')&&d.power==='5'&&d.toughness==='4');q('dependency overrides timestamp inside layer',d.subtypes.includes('Zombie')&&d.dependencies.some(x=>x[0]==='state:layer:makeCreature'&&x[1]==='state:layer:zombieIfCreature'));q('public +1/+1 counter participates in 7c before 7d switch',d.power==='5'&&d.toughness==='4'&&d.layerTrace.findIndex(x=>x.kind==='pt-counters')<d.layerTrace.findIndex(x=>x.kind==='pt-switch'));let ctrlState={battle:[target,{id:'lord',owner:1,controllerId:1,continuousEffects:[{id:'anthem',kind:'pt-mod',layer:'7c',scope:{controller:'you',type:'Creature'},powerDelta:'1',toughnessDelta:'1',automation:'exact'}]}],continuousEffects:[{id:'steal',kind:'control-set',layer:'2',scope:{objectId:'t'},controllerId:2,timestamp:9,automation:'exact'},{id:'creature',kind:'type-add',layer:'4',scope:{objectId:'t'},types:['Creature'],automation:'exact'}]};let dc=derived(ctrlState,target);q('layer-2 control change alters later controller-scoped anthem',dc.controllerId===2&&dc.power==='3');let kw={battle:[target],continuousEffects:[{id:'fly',kind:'keyword-grant',layer:'6',scope:{objectId:'t'},traits:['flying'],timestamp:1,automation:'exact'},{id:'nofly',kind:'keyword-remove',layer:'6',scope:{objectId:'t'},traits:['flying'],timestamp:2,automation:'exact'}]};q('timestamp resolves add/remove ability in same layer',derived(kw,target).traits.flying===false);q('version identifies Phase 87',VERSION.includes('phase87'));return{ok:c.every(x=>x[1]),checks:c}}
const api={VERSION,SAFE_TRAITS,normalize,gather,rank,charBase,applies,depends,dependencyOrder,derived,summary,localQA};
if(root.MTGContinuousEffects){root.MTGContinuousEffects.derived=derived;root.MTGContinuousEffects.layerSummary=summary;root.MTGContinuousEffects.ADVANCED_VERSION=VERSION}
return api;
});
