
/* Phase 108 — authoritative multiplayer synchronization hardening.
   Monotonic authority revisions, rollback-safe snapshots, lobby ordering, command receipts,
   deterministic resync, and connection-generation guards. */
(function(root,factory){const api=factory(root);if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MTGAuthoritativeSync=api})(typeof window!=='undefined'?window:globalThis,function(root){
 'use strict';
 const VERSION='phase108-authoritative-multiplayer-sync-1',SCHEMA=1;
 const clone=x=>JSON.parse(JSON.stringify(x));
 const finite=v=>Number.isFinite(Number(v));
 const stateRevision=s=>Math.max(0,Math.trunc(Number(s?.meta?.authorityRevision||0)||0));
 const stateEpoch=s=>Math.max(0,Math.trunc(Number(s?.meta?.authorityEpoch||0)||0));
 function nextRevision(current=0){return Math.max(0,Math.trunc(Number(current)||0))+1}
 function contentProjection(state={}){let x=clone(state||{});x.meta={...(x.meta||{})};delete x.meta.authorityRevision;delete x.meta.authorityEpoch;delete x.meta.authoritySnapshotHash;return x}
 function contentHash(state={}){if(root.MTGStateVerify?.hash)return root.MTGStateVerify.hash(contentProjection(state));let s=JSON.stringify(contentProjection(state));let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
 function stampStateMessage(message,{revision=0,epoch=0,reason=null}={}){
   let m={...(message||{})};if(!m.st||typeof m.st!=='object')return m;
   let r=Math.max(0,Math.trunc(Number(revision)||0)),e=Math.max(0,Math.trunc(Number(epoch)||0)),hash=contentHash(m.st);
   m.syncRevision=r;m.syncEpoch=e;m.stateHash=hash;if(reason)m.syncReason=String(reason);
   m.st={...m.st,meta:{...(m.st.meta||{}),authorityRevision:r,authorityEpoch:e,authoritySnapshotHash:hash}};
   return m;
 }
 function stampPlayersMessage(message,{revision=0}={}){let m={...(message||{})};m.lobbyRevision=Math.max(0,Math.trunc(Number(revision)||0));return m}
 function inspectSnapshot(localState={},message={},opts={}){
   const incoming=message?.st||{},incomingRevision=Math.max(0,Math.trunc(Number(message?.syncRevision||incoming?.meta?.authorityRevision||0)||0)),localRevision=stateRevision(localState),incomingEpoch=Math.max(0,Math.trunc(Number(message?.syncEpoch||incoming?.meta?.authorityEpoch||opts?.packet?.epoch||0)||0)),localEpoch=stateEpoch(localState),incomingHash=String(message?.stateHash||incoming?.meta?.authoritySnapshotHash||contentHash(incoming)),localHash=String(localState?.meta?.authoritySnapshotHash||contentHash(localState));
   if(!incomingRevision)return{accept:true,legacy:true,reason:'legacy-no-authority-revision',incomingRevision,localRevision,incomingEpoch,localEpoch,incomingHash,localHash};
   if(localEpoch&&incomingEpoch&&incomingEpoch<localEpoch)return{accept:false,reason:'stale-authority-epoch',incomingRevision,localRevision,incomingEpoch,localEpoch,incomingHash,localHash};
   if(incomingRevision<localRevision)return{accept:false,reason:'stale-authority-revision',incomingRevision,localRevision,incomingEpoch,localEpoch,incomingHash,localHash};
   if(incomingRevision===localRevision){
     if(incomingHash===localHash)return{accept:true,idempotent:true,reason:'idempotent-authority-snapshot',incomingRevision,localRevision,incomingEpoch,localEpoch,incomingHash,localHash};
     return{accept:false,reason:'authority-revision-conflict',incomingRevision,localRevision,incomingEpoch,localEpoch,incomingHash,localHash};
   }
   return{accept:true,reason:'newer-authority-revision',incomingRevision,localRevision,incomingEpoch,localEpoch,incomingHash,localHash};
 }
 function acceptLobbyRevision(incoming,lastApplied=0){let i=Math.max(0,Math.trunc(Number(incoming)||0)),l=Math.max(0,Math.trunc(Number(lastApplied)||0));if(!i)return{accept:true,legacy:true,next:l};if(i<l)return{accept:false,reason:'stale-lobby-revision',next:l};return{accept:true,idempotent:i===l,next:Math.max(i,l)}}
 function commandResult({requestId,accepted=true,reason=null,revision=0,stateHash=null,duplicate=false}={}){return{t:'command_result',requestId:String(requestId||''),accepted:!!accepted,reason:reason==null?null:String(reason),duplicate:!!duplicate,authorityRevision:Math.max(0,Math.trunc(Number(revision)||0)),stateHash:stateHash||null}}
 function resyncRequest(state={},reason='client-resync'){let fp=root.MTGStateVerify?.fingerprint?.(state)||{seq:0,hash:null};return{t:'resync_request',requestId:'resync_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,9),reason:String(reason),clientRevision:stateRevision(state),clientEpoch:stateEpoch(state),clientSeq:Number(fp.seq||0),clientHash:fp.hash||null}}
 function connectionGuard(){let current=0;return{next(){return++current},isCurrent(g){return Number(g)===Number(current)},current(){return current},invalidate(){return++current}}}
 function localQA(){let c=[],q=(n,v)=>c.push([n,!!v]),base={meta:{authorityRevision:7,authorityEpoch:2},events:[{seq:10}],life:{1:40}},newer={meta:{},events:[{seq:11}],life:{1:39}},rollback={meta:{},events:[{seq:4}],life:{1:40}};let sm=stampStateMessage({t:'state',st:newer},{revision:8,epoch:2});q('state snapshots receive monotonic authority revision',sm.syncRevision===8&&sm.st.meta.authorityRevision===8);q('snapshot hash excludes transport revision metadata',sm.stateHash===contentHash(sm.st));q('newer authority revision is accepted',inspectSnapshot(base,sm).accept);let rb=stampStateMessage({t:'state',st:rollback},{revision:9,epoch:2});q('newer authority revision permits intentional event-sequence rollback',inspectSnapshot(base,rb).accept&&Number(rb.st.events[0].seq)===4);let stale=stampStateMessage({t:'state',st:newer},{revision:6,epoch:2});q('older authority revision is rejected even when event seq is newer',!inspectSnapshot(base,stale).accept);let idem=stampStateMessage({t:'state',st:base},{revision:7,epoch:2});q('same revision and same content is idempotent',inspectSnapshot(base,idem).accept&&inspectSnapshot(base,idem).idempotent);let conflict=stampStateMessage({t:'state',st:{...base,life:{1:12}}},{revision:7,epoch:2});q('same revision with different content is rejected',inspectSnapshot(base,conflict).reason==='authority-revision-conflict');let oldEpoch=stampStateMessage({t:'state',st:newer},{revision:10,epoch:1});q('stale host epoch is rejected',inspectSnapshot(base,oldEpoch).reason==='stale-authority-epoch');q('legacy snapshot remains readable during migration',inspectSnapshot(base,{t:'state',st:newer}).legacy===true);q('lobby revisions reject out-of-order roster packets',!acceptLobbyRevision(4,5).accept);q('lobby revisions accept newer roster packets',acceptLobbyRevision(6,5).next===6);let cr=commandResult({requestId:'r1',accepted:false,reason:'invalid',revision:9});q('command result correlates request and authority revision',cr.requestId==='r1'&&!cr.accepted&&cr.authorityRevision===9);let rr=resyncRequest(base,'conflict');q('resync request carries client authority revision and fingerprint',rr.clientRevision===7&&rr.clientSeq===10&&!!rr.requestId);let g=connectionGuard(),a=g.next(),b=g.next();q('connection generation invalidates superseded client connection',!g.isCurrent(a)&&g.isCurrent(b));
 if(root.MTGProtocolPolicy){q('strict protocol accepts Phase 108 resync requests',root.MTGProtocolPolicy.validateLegacy(rr).ok&&root.MTGProtocolPolicy.wireType(rr)==='ACTION_REQUEST');q('strict protocol accepts correlated command results',root.MTGProtocolPolicy.validateLegacy(cr).ok&&root.MTGProtocolPolicy.wireType(cr)==='HOST_CONTROL')}else{q('strict protocol accepts Phase 108 resync requests',false);q('strict protocol accepts correlated command results',false)}
 if(root.MTGTransportGateway&&root.MTGProtocol&&root.MTGRoomSession&&root.MTGStateVerify){let desc=root.MTGRoomSession.createDescriptor({room:'p108qa',sessionId:'room:p108qa',hostPlayerId:'host',hostPeerId:'hostpeer',participants:[{playerId:'host',peerId:'hostpeer',seat:1,seatToken:'h'}],epoch:2}),gw=root.MTGTransportGateway.createSession({protocol:root.MTGProtocol,policy:root.MTGProtocolPolicy,verifier:root.MTGStateVerify,room:'p108qa',sessionId:'room:p108qa',clientId:'client',isHost:false,descriptor:desc,roomSession:root.MTGRoomSession}),packet=root.MTGTransportGateway.wrap(rb,{protocol:root.MTGProtocol,policy:root.MTGProtocolPolicy,room:'p108qa',sessionId:'room:p108qa',clientId:'host',isHost:true,descriptor:desc,seq:4,stateHash:rb.stateHash}),gr=gw.decode(packet,{localState:base});q('transport gateway accepts newer-revision authoritative rollback',gr.accept&&gr.decision?.incomingRevision===9);let stalePacket=root.MTGTransportGateway.wrap(stale,{protocol:root.MTGProtocol,policy:root.MTGProtocolPolicy,room:'p108qa',sessionId:'room:p108qa',clientId:'host',isHost:true,descriptor:desc,seq:11,stateHash:stale.stateHash}),gs=gw.decode(stalePacket,{localState:base});q('transport gateway rejects older authority revision before app handler',!gs.accept&&gs.decision?.reason==='stale-authority-revision')}else{q('transport gateway accepts newer-revision authoritative rollback',false);q('transport gateway rejects older authority revision before app handler',false)}
 q('version identifies Phase 108',VERSION.includes('phase108'));return{ok:c.every(x=>x[1]),checks:c}}
 return{VERSION,SCHEMA,stateRevision,stateEpoch,nextRevision,contentProjection,contentHash,stampStateMessage,stampPlayersMessage,inspectSnapshot,acceptLobbyRevision,commandResult,resyncRequest,connectionGuard,localQA};
});
