
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGTriggerOrdering=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const VERSION='phase83-apnap-trigger-order-1',clone=x=>JSON.parse(JSON.stringify(x));
function apnap(players=[],activeId,fallen={}){let full=(players||[]).map(p=>Number(p?.id)).filter(Boolean);if(!full.length)return[];let i=full.indexOf(Number(activeId));if(i<0)i=0;let ring=full.slice(i).concat(full.slice(0,i));return ring.filter(id=>!fallen?.[id])}
function plan(candidates=[],players=[],activeId,fallen={},opts={}){let order=apnap(players,activeId,fallen),by=new Map();for(const c of candidates||[]){let id=Number(c?.item?.controllerId??c?.controllerId);if(!id)continue;if(!by.has(id))by.set(id,[]);by.get(id).push(clone(c))}for(const id of by.keys())if(!order.includes(id))order.push(id);let groups=order.filter(id=>by.has(id)).map(id=>{let cs=by.get(id),ids=cs.map(x=>String(x.item.id));return{controllerId:id,candidates:cs,itemIds:ids,needsChoice:ids.length>1,topFirst:ids.length===1?ids.slice():null}});return{id:String(opts.id||('trigorder_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8))),reason:String(opts.reason||'simultaneous-triggers'),activeId:Number(activeId),apnapOrder:order,groups,deferredUntil:opts.deferredUntil||null,createdAt:Date.now(),version:VERSION}}
function groupFor(batch={},pid){return(batch.groups||[]).find(g=>Number(g.controllerId)===Number(pid))||null}
function validateChoice(batch={},pid,topFirst=[]){let g=groupFor(batch,pid);if(!g||!g.needsChoice)return{ok:false,reason:'no-choice-required'};let want=new Set((g.itemIds||[]).map(String)),got=(topFirst||[]).map(String);if(got.length!==want.size||new Set(got).size!==got.length||got.some(x=>!want.has(x)))return{ok:false,reason:'invalid-trigger-order'};return{ok:true,topFirst:got}}
function stackOrder(batch={}){let out=[];for(const g of batch.groups||[]){let ids=Array.isArray(g.topFirst)?g.topFirst:g.itemIds||[],m=new Map((g.candidates||[]).map(c=>[String(c.item.id),c]));for(const id of ids.slice().reverse()){let c=m.get(String(id));if(c)out.push(clone(c))}}return out}
function unresolvedPlayers(batch={}){return(batch.groups||[]).filter(g=>g.needsChoice&&!Array.isArray(g.topFirst)).map(g=>Number(g.controllerId))}
function mergeCandidates(batch={},incoming=[]){return(batch.groups||[]).flatMap(g=>g.candidates||[]).concat(incoming||[])}
function localQA(){let ps=[{id:1},{id:2},{id:3}],mk=(id,n)=>({item:{id:n,controllerId:id,name:n},baseCount:'1',modifiers:[]}),c=[],q=(n,v)=>c.push([n,!!v]),b=plan([mk(2,'b'),mk(1,'a1'),mk(1,'a2'),mk(3,'c')],ps,1,{});q('APNAP groups active player first',b.groups.map(g=>g.controllerId).join(',')==='1,2,3');q('multiple same-controller triggers require choice',unresolvedPlayers(b).join(',')==='1');let v=validateChoice(b,1,['a2','a1']);q('valid player order accepted',v.ok);b.groups[0].topFirst=v.topFirst;let o=stackOrder(b).map(x=>x.item.id);q('active triggers placed first on stack',o.slice(0,2).join(',')==='a1,a2');q('chosen top trigger is above sibling',o.indexOf('a2')>o.indexOf('a1'));q('last nonactive group ends on top',o.at(-1)==='c');q('foreign id rejected',!validateChoice(plan([mk(1,'x'),mk(1,'y')],ps,1,{}),1,['x','z']).ok);let d=plan([mk(1,'untap')],ps,1,{}, {deferredUntil:'UPKEEP'}),merged=mergeCandidates(d,[mk(1,'upkeep')]),replanned=plan(merged,ps,1,{}, {reason:'upkeep-merge'});q('deferred untap candidate survives upkeep merge',merged.map(x=>x.item.id).join(',')==='untap,upkeep');q('merged same-player untap and upkeep triggers require player ordering',unresolvedPlayers(replanned).join(',')==='1');let offline=plan([mk(2,'off')],[{id:1},{id:2,connected:false},{id:3}],1,{});q('offline player remains in APNAP order',offline.apnapOrder.join(',')==='1,2,3'&&offline.groups[0].controllerId===2);q('fallen active anchor preserves APNAP clockwise successor',apnap([{id:1},{id:2},{id:3},{id:4}],3,{3:{}}).join(',')==='4,1,2');q('version identifies Phase 83',VERSION.includes('phase83'));return{ok:c.every(x=>x[1]),checks:c}}
return{VERSION,apnap,plan,groupFor,validateChoice,stackOrder,unresolvedPlayers,mergeCandidates,localQA};
});
