
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MTGCombatValidation=api})(typeof window!=='undefined'?window:globalThis,function(){
 const VERSION='phase94-combat-damage-validation-2';
 function bi(v){try{return BigInt(String(v??0).replace(/,/g,''))}catch{return 0n}}
 function sourceIds(state,step){const ids=[];for(const a of state.combat?.damageAssignments||[]){if(step&&String(a.flags?.step||'')!==String(step))continue;const id=String(a.sourceObjectId||'');if(id&&!ids.includes(id))ids.push(id)}return ids}
 function assignmentIssues(state,sourceId,step,assist){if(typeof MTGAdvancedCombatDamage!=='undefined'){let a=MTGAdvancedCombatDamage.sourceAudit(state,sourceId,step);return[...(a.reasons||[]).map(code=>({severity:'error',code,sourceObjectId:String(sourceId),message:'Combat assignment is not resolution-legal: '+code+'.'})),...(a.reviewReasons||[]).map(code=>({severity:'info',code,sourceObjectId:String(sourceId),message:'Known characteristics are incomplete; manual verification required: '+code+'.'}))]}const g=assist.guide(state,sourceId,step),issues=[];if(!g.known)return[{severity:'info',code:g.reason||'unknown',sourceObjectId:String(sourceId),message:'Known characteristics are incomplete; manual verification required.'}];if(g.overAssigned)issues.push({severity:'error',code:'over-assigned',sourceObjectId:String(sourceId),message:'Assigned combat damage exceeds known source power.'});return issues;}
 function validate(state,opts={}){const assist=opts.assist||(typeof MTGCombatAssignment!=='undefined'?MTGCombatAssignment:null),step=opts.step||null;if(typeof MTGAdvancedCombatDamage!=='undefined'){let a=MTGAdvancedCombatDamage.auditAssignments(state,step),issues=[];for(const src of a.sources||[])issues.push(...assignmentIssues(state,src.sourceObjectId,step,assist));const errors=issues.filter(i=>i.severity==='error').length,unknown=issues.filter(i=>i.severity==='info').length;return{ok:errors===0,blocking:errors>0,issues,unknown,errors,sources:(a.sources||[]).map(x=>x.sourceObjectId),step,audit:a}}if(!assist)return{ok:false,blocking:true,issues:[{severity:'error',code:'assist-unavailable',message:'Combat assignment assistant unavailable.'}],unknown:0,errors:1,sources:[]};const ids=sourceIds(state,step),issues=[];for(const id of ids)issues.push(...assignmentIssues(state,id,step,assist));const errors=issues.filter(i=>i.severity==='error').length,unknown=issues.filter(i=>i.severity==='info').length;return{ok:errors===0,blocking:errors>0,issues,unknown,errors,sources:ids,step};}
 function resolutionGuard(state,opts={}){const r=validate(state,opts);if(r.blocking)return{ok:false,reason:'assignment-validation-failed',validation:r};return{ok:true,reason:r.unknown?'manual-verification-required':'validated',validation:r};}
 function summary(state,opts={}){const r=validate(state,opts);return{ok:r.ok,errors:r.errors,unknown:r.unknown,sources:r.sources.length,step:r.step,status:r.errors?'BLOCKED':r.unknown?'REVIEW':'READY'};}
 function localQA(engine,assist){let st=engine.normalizeState({life:{1:40,2:40},battle:[{id:'a',name:'Attacker',owner:1,controllerId:1,typeLine:'Creature',combatMeta:{power:'6',toughness:'6',traits:{trample:true}}},{id:'b',name:'Blocker',owner:2,controllerId:2,typeLine:'Creature',combatMeta:{power:'2',toughness:'4',traits:{}}}],combat:{active:true,attackers:[{objectId:'a',defender:{kind:'player',playerId:2},blocked:true}],blockers:[{blockerObjectId:'b',attackerObjectId:'a'}]},events:[],snapshots:[],feed:[]});const checks=[];
   engine.reduce(st,engine.makeEvent(st,'COMBAT_DAMAGE_ASSIGNED',{assignmentId:'bp',sourceObjectId:'a',target:{kind:'player',playerId:2},amount:'2'},1));let r=validate(st,{assist});checks.push(['incomplete trample assignment blocks resolution until all damage is assigned',!r.ok&&r.issues.some(i=>String(i.code).includes('assignment-total'))]);
   engine.reduce(st,engine.makeEvent(st,'COMBAT_DAMAGE_ASSIGNED',{assignmentId:'bb',sourceObjectId:'a',target:{kind:'object',objectId:'b'},amount:'4'},1));r=validate(st,{assist});checks.push(['post-Foundations entry order is irrelevant once final trample assignment is legal',r.ok]);
   engine.reduce(st,engine.makeEvent(st,'COMBAT_DAMAGE_ASSIGNED',{assignmentId:'bp',sourceObjectId:'a',target:{kind:'player',playerId:2},amount:'3'},1));checks.push(['authoritative reducer rejects known power overassignment',st.combat.damageAssignments.find(a=>a.assignmentId==='bp')?.amount==='2']);
   r=resolutionGuard(st,{assist});checks.push(['valid exact assignment is resolution ready',r.ok&&r.reason==='validated']);
   let unknown=engine.normalizeState({life:{1:40,2:40},battle:[{id:'u',name:'Unknown',owner:1,controllerId:1,typeLine:'Creature',combatMeta:{power:null,toughness:'3',traits:{}}}],combat:{active:true,attackers:[{objectId:'u',defender:{kind:'player',playerId:2},blocked:false}],damageAssignments:[{assignmentId:'u1',sourceObjectId:'u',target:{kind:'player',playerId:2},amount:'2'}]},events:[],snapshots:[],feed:[]});let ur=resolutionGuard(unknown,{assist});checks.push(['unknown power warns but does not fabricate an error',ur.ok&&ur.reason==='manual-verification-required'&&ur.validation.unknown>=1]);
   return{ok:checks.every(x=>x[1]),checks,validation:r};
 }
 return{VERSION,bi,sourceIds,assignmentIssues,validate,resolutionGuard,summary,localQA};
});

