
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGQuickActionContext=api})(typeof self!=='undefined'?self:this,function(){
'use strict';
const VERSION='phase59-battlefield-quick-action-context-1';
function q(v){try{return BigInt(String(v??'0').replace(/,/g,''))}catch{return 0n}}
function ownedObjects(state={},playerId){const id=Number(playerId);return (state.battle||[]).filter(o=>Number(o.controllerId??o.owner)===id)}
function tokenPresets(state={},playerId){return ownedObjects(state,playerId).filter(o=>o.token||q(o.q)>1n).map(o=>({objectId:String(o.id),name:String(o.name||'Token'),quantity:q(o.q||1)})).sort((a,b)=>a.quantity===b.quantity?a.name.localeCompare(b.name):(a.quantity>b.quantity?-1:1))}
function counterPresets(state={},playerId){const out=[];for(const o of ownedObjects(state,playerId)){for(const [counter,amount] of Object.entries(o.counters||{})){if(q(amount)<=0n)continue;out.push({objectId:String(o.id),objectName:String(o.name||'Permanent'),counter:String(counter),amount:q(amount)})}}return out.sort((a,b)=>a.counter.localeCompare(b.counter)||a.objectName.localeCompare(b.objectName))}
function recentCounterName(state={},playerId){const id=Number(playerId);for(const e of (state.events||[]).slice().reverse()){const p=e.payload||{};if(e.type==='PERMANENT_COUNTER_CHANGED'&&String(p.counter||'')&&ownedObjects(state,id).some(o=>String(o.id)===String(p.objectId)))return String(p.counter);if(e.type==='COUNTER_CHANGED'&&Number(p.playerId)===id&&String(p.counter||p.k||''))return String(p.counter||p.k)}return null}
function enrich(items=[],state={},playerId){const tokens=tokenPresets(state,playerId),counters=counterPresets(state,playerId),recentCounter=recentCounterName(state,playerId);return (items||[]).map(item=>{let x={...item};if(item.kind==='tokens'&&tokens[0]){x.label='Increase '+tokens[0].name+' Cohort';x.preset={type:'token-cohort',...tokens[0]};x.reasons=[...(x.reasons||[]),'matching token cohort is already tracked']}if(item.kind==='counter'&&counters[0]){let c=recentCounter?counters.find(z=>z.counter===recentCounter)||counters[0]:counters[0];x.label='Add '+c.counter+' to '+c.objectName;x.preset={type:'permanent-counter',...c};x.reasons=[...(x.reasons||[]),'matching counter is already tracked']}return x})}
function publicSummary(items=[]){return (items||[]).map(x=>({id:x.id,kind:x.kind,label:x.id==='tokens'?'Token Action':x.id==='counter'?'Counter Action':x.label}))}
function localQA(){const st={battle:[{id:'rabbits',name:'Rabbit',owner:1,controllerId:1,token:1,q:'4096',counters:{}},{id:'angel',name:'Angel',owner:1,controllerId:1,q:'1',counters:{'+1/+1':'4'}},{id:'enemy',name:'Enemy',owner:2,controllerId:2,token:1,q:'9999',counters:{poison:'9'}}],events:[{type:'PERMANENT_COUNTER_CHANGED',payload:{objectId:'angel',counter:'+1/+1',delta:'1'}}]};const base=[{id:'tokens',kind:'tokens',label:'Create Tokens',reasons:[]},{id:'counter',kind:'counter',label:'Add Counter',reasons:[]}],en=enrich(base,st,1),checks=[];checks.push(['owned objects exclude opponents',ownedObjects(st,1).every(o=>o.owner===1)]);checks.push(['largest own token cohort is detected',tokenPresets(st,1)[0].name==='Rabbit']);checks.push(['opponent token cohort is ignored',!tokenPresets(st,1).some(x=>x.name==='Enemy')]);checks.push(['tracked permanent counter is detected',counterPresets(st,1)[0].counter==='+1/+1']);checks.push(['opponent counters are ignored',!counterPresets(st,1).some(x=>x.counter==='poison')]);checks.push(['recent counter name is recovered',recentCounterName(st,1)==='+1/+1']);checks.push(['token suggestion becomes cohort shortcut',en[0].preset.type==='token-cohort']);checks.push(['token shortcut keeps object identity',en[0].preset.objectId==='rabbits']);checks.push(['counter suggestion becomes permanent shortcut',en[1].preset.type==='permanent-counter']);checks.push(['counter shortcut keeps permanent identity',en[1].preset.objectId==='angel']);checks.push(['public summary strips presets',!('preset' in publicSummary(en)[0])]);checks.push(['public summary does not expose token name',publicSummary(en)[0].label==='Token Action']);return{ok:checks.every(x=>x[1]),checks}}
return{VERSION,ownedObjects,tokenPresets,counterPresets,recentCounterName,enrich,publicSummary,localQA};
});

