
/* Phase 94 — advanced combat damage assignment, strike-step identity, simultaneous damage metadata, and SBA fixed-point support. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGAdvancedCombatDamage=api})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const VERSION='phase94-advanced-combat-sba-1';
const clone=x=>JSON.parse(JSON.stringify(x));
const bi=v=>{try{return BigInt(String(v??0).replace(/,/g,''))}catch{return 0n}};
const ctrl=o=>Number(o?.controllerId??o?.owner??0)||0;
function object(state,id){return(state?.battle||[]).find(o=>String(o.id)===String(id)&&!root.MTGPhasing?.isPhasedOut(o))||null}
function traits(state,o){if(!o)return{};return typeof root.MTGContinuousEffects!=='undefined'?root.MTGContinuousEffects.derived(state,o).traits:(o.combatMeta?.traits||{})}
function stats(state,o){if(!o)return{power:null,toughness:null,traits:{}};if(typeof root.MTGCombatRules!=='undefined')return root.MTGCombatRules.stats(o,state);let t=traits(state,o);return{power:o.combatMeta?.power??null,toughness:o.combatMeta?.toughness??null,traits:t,damageMarked:String(o.damageMarked||0)}}
function attackerRecord(state,id){return(state?.combat?.attackers||[]).find(a=>String(a.objectId)===String(id))||null}
function blockerRecordsForAttacker(state,id){return(state?.combat?.blockers||[]).filter(b=>String(b.attackerObjectId)===String(id))}
function blockerRecord(state,id){return(state?.combat?.blockers||[]).find(b=>String(b.blockerObjectId)===String(id))||null}
function participantIds(state){const out=new Set();for(const a of state?.combat?.attackers||[])out.add(String(a.objectId));for(const b of state?.combat?.blockers||[])out.add(String(b.blockerObjectId));return[...out]}
function firstSnapshot(state){let sources={};for(const id of participantIds(state)){let o=object(state,id),tr=traits(state,o);sources[id]={hadFirstStrike:!!tr.firstStrike,hadDoubleStrike:!!tr.doubleStrike,hadFirstOrDouble:!!tr.firstStrike||!!tr.doubleStrike};}return{captured:true,sources}}
function normalizeSnapshot(x){let out=x&&typeof x==='object'?clone(x):{captured:false,sources:{}};out.captured=!!out.captured;out.sources=out.sources&&typeof out.sources==='object'?out.sources:{};for(const [id,v] of Object.entries(out.sources)){out.sources[id]={hadFirstStrike:!!v?.hadFirstStrike,hadDoubleStrike:!!v?.hadDoubleStrike,hadFirstOrDouble:!!(v?.hadFirstOrDouble||v?.hadFirstStrike||v?.hadDoubleStrike)}}return out}
function stepEligible(state,sourceOrId,step){let o=typeof sourceOrId==='object'?sourceOrId:object(state,sourceOrId);if(!o)return false;let id=String(o.id),cs=state?.combatSteps||{},tr=traits(state,o);if(step==='first'){let snap=normalizeSnapshot(cs.firstSnapshot),r=snap.sources[id];return r?!!r.hadFirstOrDouble:(!!tr.firstStrike||!!tr.doubleStrike)}if(step==='normal'){if(!cs.firstStepRequired)return true;if(tr.doubleStrike)return true;let snap=normalizeSnapshot(cs.firstSnapshot),r=snap.sources[id];if(!r)return true;return !r.hadFirstOrDouble}return false}
function sourcePower(state,sourceOrId){let o=typeof sourceOrId==='object'?sourceOrId:object(state,sourceOrId),v=stats(state,o).power;if(v===null||v===undefined||String(v).trim()==='')return null;let n=bi(v);return n>0n?n:0n}
function marked(o){return bi(o?.damageMarked||0)}
function lethalNeed(state,source,target){let st=stats(state,target),t=st.toughness;if(t===null||t===undefined||String(t).trim()==='')return null;let need=bi(t)-marked(target);if(need<0n)need=0n;if(traits(state,source).deathtouch&&need>0n)need=1n;return need}
function targetKey(t){return t?.kind==='player'?'p:'+Number(t.playerId):t?.kind==='object'?'o:'+String(t.objectId||''):''}
function sameTarget(a,b){return targetKey(a)===targetKey(b)}
function wasBlocked(state,attackerId){let rec=attackerRecord(state,attackerId);return !!(rec?.blocked||blockerRecordsForAttacker(state,attackerId).length)}
function legalTargets(state,sourceId){let sid=String(sourceId),a=attackerRecord(state,sid),br=blockerRecord(state,sid),src=object(state,sid);if(!src)return{known:false,reason:'source-missing',targets:[]};if(a){let blocks=blockerRecordsForAttacker(state,sid).map(b=>object(state,b.blockerObjectId)).filter(Boolean),blocked=wasBlocked(state,sid),trample=!!traits(state,src).trample,targets=blocks.map(o=>({kind:'object',objectId:String(o.id)})),def=clone(a.defender),defenderAvailable=def?.kind==='player'?!!Number(def.playerId)&&!state.fallen?.[Number(def.playerId)]:def?.kind==='object'?(()=>{let o=object(state,def.objectId),dp=Number(def.defendingPlayerId||0);return !!o&&/\bPlaneswalker\b/i.test(String(o.typeLine||o.type||''))&&(!dp||Number(o.controllerId??o.owner)===dp)})():false;if((!blocked||trample)&&defenderAvailable)targets.push(def);return{known:true,role:'attacker',blocked,trample,blocks,defender:def,defenderAvailable,targets}}
 if(br){let atk=object(state,br.attackerObjectId),ar=attackerRecord(state,br.attackerObjectId);return atk&&ar?{known:true,role:'blocker',blocked:false,trample:false,blocks:[],defender:null,targets:[{kind:'object',objectId:String(atk.id)}]}:{known:true,role:'blocker',blocked:false,trample:false,blocks:[],defender:null,attackerMissing:true,targets:[]}}
 return{known:false,reason:'source-not-in-combat',targets:[]}}
function assignmentsFor(state,sourceId,step=null,assignments=null){let list=assignments||state?.combat?.damageAssignments||[];return list.filter(a=>String(a.sourceObjectId)===String(sourceId)&&(!step||String(a.flags?.step||'')===String(step)))}
function validateIncremental(state,sourceId,target,amount,step=null,assignmentId=null){let src=object(state,sourceId);if(!src)return{ok:false,reason:'source-missing'};if(state?.combatSteps?.active&&!stepEligible(state,src,step||state.combatSteps.current))return{ok:false,reason:'source-not-eligible'};let rel=legalTargets(state,sourceId);if(!rel.known)return{ok:false,reason:rel.reason};if(!rel.targets.some(t=>sameTarget(t,target)))return{ok:false,reason:'illegal-combat-damage-target'};let power=sourcePower(state,src);if(power===null)return{ok:true,review:true,reason:'power-unknown'};let total=bi(amount);for(const a of assignmentsFor(state,sourceId,step)){if(assignmentId&&String(a.assignmentId)===String(assignmentId))continue;total+=bi(a.amount)}if(total>power)return{ok:false,reason:'exceeds-known-power',power:power.toString(),prospective:total.toString()};return{ok:true,review:false,reason:'known-incrementally-legal',power:power.toString(),prospective:total.toString()}}
function sourceAudit(state,sourceId,step=null,assignments=null){let src=object(state,sourceId),rel=legalTargets(state,sourceId),rows=assignmentsFor(state,sourceId,step,assignments),reasons=[],review=[];if(!src)return{ok:false,review:false,sourceObjectId:String(sourceId),reasons:['source-missing'],reviewReasons:[]};if(state?.combatSteps?.active&&!stepEligible(state,src,step||state.combatSteps.current))reasons.push('source-not-eligible');if(!rel.known)reasons.push(rel.reason||'combat-relation-unknown');let power=sourcePower(state,src);if(power===null)review.push('power-unknown');let total=rows.reduce((n,a)=>n+bi(a.amount),0n);for(const a of rows)if(!rel.targets.some(t=>sameTarget(t,a.target)))reasons.push('illegal-target:'+targetKey(a.target));if(power!==null&&total>power)reasons.push('over-assigned');let canDeal=rel.known&&rel.targets.length>0&&power!==null&&power>0n;if(power!==null&&canDeal&&total!==power)reasons.push('assignment-total-must-equal-power');if(power!==null&&!canDeal&&total!==0n)reasons.push('source-has-no-legal-recipient');if(rel.role==='attacker'&&rel.defender?.kind==='object'&&rows.some(a=>sameTarget(a.target,rel.defender)))review.push('attacked-object-damage-model-unsupported');if(rel.role==='attacker'&&rel.blocked){let defAmount=rows.filter(a=>sameTarget(a.target,rel.defender)).reduce((n,a)=>n+bi(a.amount),0n);if(defAmount>0n&&!rel.trample)reasons.push('blocked-attacker-without-trample-cannot-hit-defender');if(defAmount>0n&&rel.trample){let need=0n;for(const b of rel.blocks){let x=lethalNeed(state,src,b);if(x===null){review.push('blocker-toughness-unknown:'+String(b.id));continue}need+=x}let toBlocks=rows.filter(a=>a.target?.kind==='object'&&rel.blocks.some(b=>String(b.id)===String(a.target.objectId))).reduce((n,a)=>n+bi(a.amount),0n);if(!review.length&&toBlocks<need)reasons.push('trample-lethal-not-assigned-to-all-blockers')}}return{ok:reasons.length===0&&review.length===0,review:review.length>0,sourceObjectId:String(sourceId),power:power===null?null:power.toString(),total:total.toString(),reasons:[...new Set(reasons)],reviewReasons:[...new Set(review)]}}
function auditAssignments(state,step=null,assignments=null){let list=(assignments||state?.combat?.damageAssignments||[]).filter(a=>!step||String(a.flags?.step||'')===String(step)),ids=new Set(list.map(a=>String(a.sourceObjectId)));if(state?.combatSteps?.active){for(const id of participantIds(state))if(stepEligible(state,id,step||state.combatSteps.current))ids.add(String(id))}let sources=[...ids].map(id=>sourceAudit(state,id,step,list)),reasons=sources.flatMap(x=>x.reasons.map(r=>idLabel(x.sourceObjectId)+': '+r)),reviewReasons=sources.flatMap(x=>x.reviewReasons.map(r=>idLabel(x.sourceObjectId)+': '+r));return{ok:sources.every(x=>x.ok),review:sources.some(x=>x.review),step:step||null,sources,reasons,reviewReasons}}
function idLabel(id){return String(id||'source')}
function excessForAssignment(state,a){if(!a||a.target?.kind!=='object')return{known:false,reason:'not-creature-target',excess:'0'};let src=object(state,a.sourceObjectId),t=object(state,a.target.objectId);if(!src||!t)return{known:false,reason:'object-missing',excess:'0'};let need=lethalNeed(state,src,t);if(need===null)return{known:false,reason:'toughness-unknown',excess:'0'};let amt=bi(a.amount),ex=amt>need?amt-need:0n;return{known:true,reason:'known',lethal:need.toString(),assigned:amt.toString(),excess:ex.toString()}}
function safeSbaPlan(state){if(typeof root.MTGStateBasedActions==='undefined')return{actions:[],attachmentActions:[],review:true};let p=root.MTGStateBasedActions.plan(state);return{actions:(p.actions||[]).map(clone),attachmentActions:(p.attachmentActions||[]).map(clone),unknown:(p.unknown||[]).map(clone),review:!!((p.attachmentReview||[]).length)}}
function localQA(engine){let c=[],q=(n,v)=>c.push([n,!!v]);let base=engine.normalizeState({life:{1:40,2:40},battle:[{id:'fs',owner:1,controllerId:1,typeLine:'Creature',combatMeta:{power:'2',toughness:'2',traits:{firstStrike:true}}},{id:'n',owner:2,controllerId:2,typeLine:'Creature',combatMeta:{power:'2',toughness:'2',traits:{}}}],combat:{active:true,attackers:[{objectId:'fs',defender:{kind:'player',playerId:2},blocked:false}],blockers:[{blockerObjectId:'n',attackerObjectId:'fs'}]},events:[],snapshots:[],feed:[]});let snap=firstSnapshot(base);base.combatSteps={active:true,current:'first',firstStepRequired:true,completed:[],resolvedAssignmentIds:[],sequence:1,firstSnapshot:snap};q('first-step snapshot freezes first-strike identity',snap.sources.fs.hadFirstOrDouble&&!snap.sources.n.hadFirstOrDouble);base.battle.find(o=>o.id==='fs').combatMeta.traits.firstStrike=false;base.combatSteps.current='normal';q('losing first strike after first step does not grant second hit',!stepEligible(base,'fs','normal'));base.battle.find(o=>o.id==='n').combatMeta.traits.firstStrike=true;q('gaining first strike after first step does not erase normal hit',stepEligible(base,'n','normal'));base.battle.find(o=>o.id==='fs').combatMeta.traits.doubleStrike=true;q('current double strike grants normal-step damage',stepEligible(base,'fs','normal'));
 let tr=engine.normalizeState({life:{1:40,2:40},battle:[{id:'t',owner:1,controllerId:1,typeLine:'Creature',combatMeta:{power:'7',toughness:'7',traits:{trample:true,deathtouch:true}}},{id:'b1',owner:2,controllerId:2,typeLine:'Creature',combatMeta:{power:'2',toughness:'8',traits:{}}},{id:'b2',owner:2,controllerId:2,typeLine:'Creature',combatMeta:{power:'2',toughness:'9',traits:{}}}],combat:{active:true,attackers:[{objectId:'t',defender:{kind:'player',playerId:2},blocked:true}],blockers:[{blockerObjectId:'b1',attackerObjectId:'t'},{blockerObjectId:'b2',attackerObjectId:'t'}],damageAssignments:[]},events:[],snapshots:[],feed:[]});q('deathtouch makes one damage lethal for trample assignment',lethalNeed(tr,tr.battle[0],tr.battle[1])===1n&&lethalNeed(tr,tr.battle[0],tr.battle[2])===1n);tr.combat.damageAssignments=[{assignmentId:'x1',sourceObjectId:'t',target:{kind:'object',objectId:'b2'},amount:'1'},{assignmentId:'x2',sourceObjectId:'t',target:{kind:'object',objectId:'b1'},amount:'1'},{assignmentId:'x3',sourceObjectId:'t',target:{kind:'player',playerId:2},amount:'5'}];q('post-Foundations blocker distribution has no damage-order requirement',auditAssignments(tr).ok);tr.combat.damageAssignments=[{assignmentId:'x1',sourceObjectId:'t',target:{kind:'object',objectId:'b1'},amount:'1'},{assignmentId:'x3',sourceObjectId:'t',target:{kind:'player',playerId:2},amount:'6'}];q('trample still requires lethal to every current blocker before defender damage',auditAssignments(tr).reasons.some(x=>/trample-lethal/.test(x)));
 let gone=engine.normalizeState({life:{1:40,2:40},battle:[{id:'a',owner:1,controllerId:1,typeLine:'Creature',combatMeta:{power:'4',toughness:'4',traits:{}}}],combat:{active:true,attackers:[{objectId:'a',defender:{kind:'player',playerId:2},blocked:true}],blockers:[],damageAssignments:[]},events:[],snapshots:[],feed:[]});q('blocked history survives after blocker leaves',wasBlocked(gone,'a'));q('blocked nontrampler cannot hit defender after blocker leaves',!legalTargets(gone,'a').targets.some(t=>t.kind==='player'));gone.battle[0].combatMeta.traits.trample=true;q('trample can hit defender when all blockers are gone',legalTargets(gone,'a').targets.some(t=>t.kind==='player'));let pw=engine.normalizeState({life:{1:40,2:40},battle:[{id:'pa',owner:1,controllerId:1,typeLine:'Creature',combatMeta:{power:'3',toughness:'3',traits:{}}},{id:'pw',owner:2,controllerId:2,typeLine:'Planeswalker'}],combat:{active:true,attackers:[{objectId:'pa',defender:{kind:'object',objectId:'pw'},blocked:false}],blockers:[],damageAssignments:[]},events:[],snapshots:[],feed:[]}),pwa=auditAssignments(pw,null,[{assignmentId:'apw',sourceObjectId:'pa',target:{kind:'object',objectId:'pw'},amount:'3'}]);q('unsupported attacked-object resource damage routes to review',pwa.review&&pwa.reviewReasons.some(x=>/attacked-object-damage-model-unsupported/.test(x)));
 let inc=validateIncremental(tr,'t',{kind:'player',playerId:2},'8',null,'new');q('incremental validator rejects over-assignment',!inc.ok&&inc.reason==='exceeds-known-power');let ex=excessForAssignment(tr,{sourceObjectId:'t',target:{kind:'object',objectId:'b1'},amount:'4'});q('safe excess damage is calculated before prevention',ex.known&&ex.lethal==='1'&&ex.excess==='3');let sba=engine.normalizeState({battle:[{id:'d',owner:1,controllerId:1,typeLine:'Creature',combatMeta:{power:'2',toughness:'2',traits:{}},damageMarked:'2'},{id:'z',owner:2,controllerId:2,typeLine:'Creature',combatMeta:{power:'1',toughness:'0',traits:{indestructible:true}},damageMarked:'0'}],events:[],snapshots:[],feed:[]}),sp=safeSbaPlan(sba);q('post-damage SBA plan catches lethal and zero toughness together',sp.actions.length===2);if(engine){let st=engine.normalizeState({life:{1:40,2:40},phase:'DECLARE BLOCKERS',active:1,turn:2,battle:[{id:'atk',owner:1,controllerId:1,typeLine:'Creature',controlledSinceTurn:1,combatMeta:{power:'3',toughness:'3',traits:{}}},{id:'blk',owner:2,controllerId:2,typeLine:'Creature',controlledSinceTurn:1,combatMeta:{power:'2',toughness:'2',traits:{}}}],combat:{active:true,attackers:[{objectId:'atk',defender:{kind:'player',playerId:2}}],blockers:[]},events:[],snapshots:[],feed:[]});engine.reduce(st,engine.makeEvent(st,'BLOCKER_DECLARED',{blockerObjectId:'blk',attackerObjectId:'atk'},2,{source:'qa'}));q('authoritative blocker declaration records blocked history',st.combat.attackers[0]?.blocked===true);engine.reduce(st,engine.makeEvent(st,'COMBAT_DAMAGE_SEQUENCE_STARTED',{firstStepRequired:false},1,{source:'qa'}));q('authoritative damage sequence persists first-step snapshot',!!st.combatSteps.firstSnapshot?.captured);engine.reduce(st,engine.makeEvent(st,'COMBAT_DAMAGE_ASSIGNED',{assignmentId:'over',sourceObjectId:'atk',target:{kind:'object',objectId:'blk'},amount:'4',flags:{step:'normal'}},1,{source:'qa'}));q('authoritative reducer rejects known combat over-assignment',!st.combat.damageAssignments.some(a=>a.assignmentId==='over'))}q('version identifies Phase 94',VERSION.includes('phase94'));return{ok:c.every(x=>x[1]),checks:c}}
return{VERSION,bi,object,traits,stats,attackerRecord,blockerRecordsForAttacker,blockerRecord,participantIds,firstSnapshot,normalizeSnapshot,stepEligible,sourcePower,marked,lethalNeed,targetKey,sameTarget,wasBlocked,legalTargets,assignmentsFor,validateIncremental,sourceAudit,auditAssignments,excessForAssignment,safeSbaPlan,localQA};
});
