
/* Whole-table public rules observer — Phase 95 event context, Phase 96 phased-out visibility; Phase 97 link records remain authoritative state. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGTableObserver=api})(typeof globalThis!=='undefined'?globalThis:this,function(root){
 'use strict';const VERSION='phase99-whole-table-observer-facedown-1';
 const n=v=>Number(v)||0,lc=v=>String(v||'').toLowerCase(),clone=x=>JSON.parse(JSON.stringify(x)),biSafe=v=>{try{return BigInt(String(v??0))}catch{return 0n}};
 function legacyCapture(state={},type='',payload={}){return root.MTGLKI?.capture?root.MTGLKI.capture(state,type,payload):{battle:[],objects:[]}}
 function needsBefore(){return true}
 function snapshot(state={},type='',payload={}){return legacyCapture(state,type,payload)}
 function playerSubject(id,extra={}){id=Number(id);return{id:'player:'+id,name:'Player '+id,owner:id,controllerId:id,type:'Player',typeLine:'Player',sub:[],q:'1',...extra}}
 function battleObject(state,id){return (state?.battle||[]).find(o=>(String(o.id)===String(id)||String(o.stableObjectId)===String(id)||String(o.incarnationId)===String(id))&&!root.MTGPhasing?.isPhasedOut(o))||null}
 function isCreature(o){if(Array.isArray(o?.types))return o.types.some(x=>lc(x)==='creature');return /(?:^|\W)creature(?:$|\W)/i.test(String(o?.typeLine||o?.type||''))}
 function lifeDeltaDescriptors(before={},after={}){let ids=new Set([...Object.keys(before?.life||{}),...Object.keys(after?.life||{})]),out=[];for(const raw of ids){let id=Number(raw);if(!id)continue;let a,b;try{a=BigInt(String(before.life?.[raw]??before.life?.[id]??0));b=BigInt(String(after.life?.[raw]??after.life?.[id]??0))}catch{continue}if(b>a)out.push({event:'LIFE_GAINED',subject:playerSubject(id,{amount:(b-a).toString()}),observationMode:'POST_EVENT'});else if(b<a)out.push({event:'LIFE_LOST',subject:playerSubject(id,{amount:(a-b).toString()}),observationMode:'POST_EVENT'})}return out}
 function libraryDrawDescriptors(before={},after={}){let ids=new Set([...Object.keys(before?.libraryCounts||{}),...Object.keys(after?.libraryCounts||{})]),out=[];for(const raw of ids){let id=Number(raw),a=Number(before?.libraryCounts?.[raw]?.draws??before?.libraryCounts?.[id]?.draws??0),b=Number(after?.libraryCounts?.[raw]?.draws??after?.libraryCounts?.[id]?.draws??0),d=Math.max(0,b-a);if(id&&d)out.push({event:'CARD_DRAWN',subject:playerSubject(id,{q:String(d),cardsDrawn:d}),observationMode:'POST_EVENT'})}return out}
 function eventStates(e,before={},after={}){if(root.MTGLKI&&e?.phase95Context)return{before:root.MTGLKI.preState(e,before),after:root.MTGLKI.postState(e,after)};return{before:before||{},after:after||{}}}
 function descriptors(e,before={},after={}){if(!e)return[];let states=eventStates(e,before,after);before=states.before;after=states.after;let p=e.payload||{},out=[],push=(event,subject,extraSources=[],observationMode='POST_EVENT')=>{if(subject)out.push({event,subject,extraSources,observationMode,atomicBatchId:e.atomicBatchId||e.phase95Context?.atomicBatchId||null})};
  if(e.type==='PERMANENT_ADDED'){push('PERMANENT_ENTERED',battleObject(after,p.object?.id));return out}
  if(e.type==='FACE_DOWN_PERMANENT_ENTERED'){push('PERMANENT_ENTERED',battleObject(after,p.objectId));return out}
  if(e.type==='PERMANENT_FACE_UP_SPECIAL_ACTION'||e.type==='PERMANENT_FACE_UP_SET'){push('TURNED_FACE_UP',battleObject(after,p.objectId));return out}
  if(e.type==='TOKEN_COHORT_CREATED'){push('PERMANENT_ENTERED',battleObject(after,p.cohort?.id));return out}
  if(e.type==='ATTACKER_DECLARED'){let old=battleObject(before,p.objectId),cur=battleObject(after,p.objectId);push('ATTACKS',cur);if(old&&cur&&!old.tapped&&cur.tapped)push('BECOMES_TAPPED',cur);return out}
  if(e.type==='PERMANENT_TAPPED_SET'){let old=battleObject(before,p.objectId),cur=battleObject(after,p.objectId);if(!old||!cur||!!old.tapped===!!cur.tapped)return out;push(cur.tapped?'BECOMES_TAPPED':'BECOMES_UNTAPPED',cur);return out}
  if(e.type==='PERMANENT_REMOVED'){let old=battleObject(before,p.objectId);push('PERMANENT_LEFT',old,[old].filter(Boolean),'PRE_EVENT_LOOKBACK');return out}
  if(e.type==='OBJECT_ZONE_CHANGED'){let old=battleObject(before,p.objectId),to=lc(p.toZone||'battlefield');if(to==='battlefield'){push('PERMANENT_ENTERED',battleObject(after,p.objectId));return out}if(old){push('PERMANENT_LEFT',old,[old],'PRE_EVENT_LOOKBACK');if(to==='graveyard'&&isCreature(old))push('PERMANENT_DIED',old,[old],'PRE_EVENT_LOOKBACK')}return out}
  if(e.type==='STATE_BASED_ACTIONS_APPLIED'){let ids=(p.objectIds||[]).map(String),dead=(before?.battle||[]).filter(o=>ids.includes(String(o.id))&&!battleObject(after,o.id));for(const old of dead){push('PERMANENT_LEFT',old,dead,'PRE_EVENT_LOOKBACK');if(isCreature(old))push('PERMANENT_DIED',old,dead,'PRE_EVENT_LOOKBACK')}for(const a of e.phase90AttachmentActions||[]){if(a.kind!=='aura-graveyard'||dead.some(x=>String(x.id)===String(a.sourceObjectId)))continue;let old=(before?.battle||[]).find(x=>String(x.id)===String(a.sourceObjectId));if(old&&!battleObject(after,old.id)){push('PERMANENT_LEFT',old,[old],'PRE_EVENT_LOOKBACK');if(isCreature(old))push('PERMANENT_DIED',old,[old],'PRE_EVENT_LOOKBACK')}}return out}
  if(e.type==='LIFE_CHANGED'||e.type==='LIFE_CHANGED_EXACT'){let d;try{d=BigInt(String(p.delta||0))}catch{d=0n}let id=Number(p.playerId??e.actorId);if(d>0n)push('LIFE_GAINED',playerSubject(id,{amount:d.toString()}));else if(d<0n)push('LIFE_LOST',playerSubject(id,{amount:(-d).toString()}));return out}
  if(e.type==='LIFE_LOST'){let id=Number(p.playerId??p.targetPlayerId??e.actorId),a=String(p.amount||0);if(id&&a!=='0')push('LIFE_LOST',playerSubject(id,{amount:a}));return out}
  if(e.type==='DAMAGE_DEALT'||e.type==='COMMANDER_DAMAGE_DEALT'){let id=Number(p.defenderId??p.targetPlayerId??e.actorId),a=String(p.amount||0);if(id&&a!=='0')push('LIFE_LOST',playerSubject(id,{amount:a,damage:true,sourcePlayerId:Number(p.sourcePlayerId??e.actorId)}));return out}
  if(e.type==='LIBRARY_COUNT_CHANGED'&&String(p.reason||'').toLowerCase()==='draw'){let id=Number(p.playerId??e.actorId),d=Math.max(0,-Number(p.delta||0));if(id&&d)push('CARD_DRAWN',playerSubject(id,{q:String(d),cardsDrawn:d}));return out}
  if(e.type==='COMBAT_DAMAGE_RESOLVED'||e.type==='COMBAT_DAMAGE_STEP_RESOLVED'){let dif=lifeDeltaDescriptors(before,after);if(Array.isArray(e.phase94LifeGainEvents)&&e.phase94LifeGainEvents.length){dif=dif.filter(x=>x.event!=='LIFE_GAINED');for(const g of e.phase94LifeGainEvents)if(Number(g.playerId)&&biSafe(g.amount)>0n)push('LIFE_GAINED',playerSubject(Number(g.playerId),{amount:String(g.amount),sourceObjectId:String(g.sourceObjectId||''),lifelink:true}));dif.push(...out);return dif}return dif}
  if(e.type==='TURN_ADVANCED'){let id=Number(after?.active||0),phase=String(after?.phase||'');if(id&&phase)push('PHASE_BEGIN',playerSubject(id,{phase,turn:Number(after?.turn||0)}));if(phase==='UNTAP'){for(const old of before?.battle||[]){let cur=battleObject(after,old.id);if(old?.tapped&&cur&&!cur.tapped)push('BECOMES_UNTAPPED',cur)}}out.push(...libraryDrawDescriptors(before,after));return out}
  return out
 }
 function localQA(engine){let checks=[],q=(name,v)=>checks.push([name,!!v]),p1={id:'a',name:'Watcher',owner:1,controllerId:1,type:'Creature',typeLine:'Creature — Cleric',tapped:false},p2={id:'b',name:'Other',owner:2,controllerId:2,type:'Creature',typeLine:'Creature — Elf',tapped:false},base={battle:[p1,p2],life:{1:40,2:40},active:1,phase:'MAIN 1'},tap={...base,battle:[p1,{...p2,tapped:true}]};q('tap transition observed',descriptors({type:'PERMANENT_TAPPED_SET',payload:{objectId:'b'}},base,tap)[0]?.event==='BECOMES_TAPPED');let gone={...base,battle:[p1]};let leave=descriptors({type:'OBJECT_ZONE_CHANGED',payload:{objectId:'b',toZone:'graveyard'}},base,gone);q('graveyard leave uses look-back mode',leave.some(x=>x.event==='PERMANENT_DIED'&&x.observationMode==='PRE_EVENT_LOOKBACK'));let drawBefore={...base,libraryCounts:{2:{draws:1,value:90}}},drawAfter={...base,libraryCounts:{2:{draws:3,value:88}}};q('tracked multi-card draw remains exact',libraryDrawDescriptors(drawBefore,drawAfter)[0]?.subject.q==='2');if(engine&&root.MTGLKI){let r=root.MTGLKI.localQA(engine);q('Phase 95 LKI kernel QA passes',r.ok)}let fu={...base,battle:[p1,{...p2,formState:{faceDown:false}}]};q('face-up special action emits turned-face-up descriptor',descriptors({type:'PERMANENT_FACE_UP_SPECIAL_ACTION',payload:{objectId:'b'}},base,fu)[0]?.event==='TURNED_FACE_UP');q('observer version identifies Phase 99',VERSION.includes('phase99'));return{ok:checks.every(x=>x[1]),checks}}
 return{VERSION,needsBefore,snapshot,playerSubject,battleObject,isCreature,lifeDeltaDescriptors,libraryDrawDescriptors,eventStates,descriptors,localQA};
});
