
/* Phase 102 — Suspend compound keyword, time-counter triggers, and exact exile cast window. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MTGSuspend=api})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const VERSION='phase102-suspend-time-counter-casting-1';
const clone=x=>JSON.parse(JSON.stringify(x));
const permanentType=tl=>/\b(?:Creature|Artifact|Enchantment|Planeswalker|Battle)\b/i.test(String(tl||''));
const creatureType=tl=>/\bCreature\b/i.test(String(tl||''));
function blank(){return{version:VERSION,records:{}}}
function normalizeRecord(raw={},id=''){let r=raw&&typeof raw==='object'?raw:{};r.id=String(r.id||id||'');r.playerId=Number(r.playerId||0)||0;r.stableObjectId=String(r.stableObjectId||r.objectId||'');r.objectId=String(r.objectId||r.stableObjectId||'');r.incarnationId=String(r.incarnationId||'');r.zoneChangeId=String(r.zoneChangeId||'');r.initialTime=Math.max(0,Math.trunc(Number(r.initialTime||0)));r.timeRemaining=Math.max(0,Math.trunc(Number(r.timeRemaining??r.initialTime??0)));r.suspendCost=String(r.suspendCost||'');r.createdSeq=Number(r.createdSeq||0);r.active=r.active!==false&&!r.invalidated&&!r.cast&&!r.declined&&!r.lastTriggerCountered;r.invalidated=!!r.invalidated;r.cast=!!r.cast;r.declined=!!r.declined;r.lastTriggerCountered=!!r.lastTriggerCountered;r.lastCounterTriggered=!!r.lastCounterTriggered;r.lastCounterSeq=Number(r.lastCounterSeq||0);r.permissionId=r.permissionId?String(r.permissionId):null;r.version=VERSION;return r}
function normalizeState(state={}){state.suspend=state.suspend&&typeof state.suspend==='object'?state.suspend:blank();state.suspend.version=VERSION;state.suspend.records=state.suspend.records&&typeof state.suspend.records==='object'?state.suspend.records:{};for(const [id,raw] of Object.entries(state.suspend.records)){let r=normalizeRecord(raw,id);if(!r.id){delete state.suspend.records[id];continue}if(r.id!==id){delete state.suspend.records[id];state.suspend.records[r.id]=r}else state.suspend.records[id]=r}return state.suspend}
function parseAll(card={}){let text=String(card.oracleText||card.oracle_text||''),out=[];for(const m of text.matchAll(/\bSuspend\s+(\d+)\s*[—–-]\s*((?:\{[^}]+\})+)/gi)){let n=Math.max(0,Math.trunc(Number(m[1]||0))),cost=String(m[2]||'');if(n>0&&cost)out.push({time:n,cost,index:out.length})}return out}
function parse(card={},instanceIndex=0){let all=parseAll(card),i=Math.max(0,Math.trunc(Number(instanceIndex||0)));return all[i]||null}
function priorityAvailable(state={},playerId=0){let h=Number(state.priorityFlow?.holder??state.priority??playerId);return !h||h===Number(playerId)}
function basicCastTiming(state={},playerId=0,card={}){if(!priorityAvailable(state,playerId))return{ok:false,reason:'suspend-priority-required',review:false};if(root.MTGAdvancedSpellResolution?.castPermission){let v=root.MTGAdvancedSpellResolution.castPermission(state,playerId,card,{fromZone:'hand'});if(v?.hardBlock)return{ok:false,reason:'suspend-cast-prohibited',review:false,details:v.reasons||[]};if(v?.manual||v?.reviewReasons?.length)return{ok:false,reason:'suspend-cast-permission-uncertain',review:true,details:v.reviewReasons||[]};if(v?.ok)return{ok:true}}let instant=/\bInstant\b/i.test(String(card.typeLine||''))||/\bFlash\b/i.test(String(card.oracleText||''))||(card.keywords||[]).some?.(x=>String(x).toLowerCase()==='flash');if(instant)return{ok:true};if(Number(state.active||0)!==Number(playerId))return{ok:false,reason:'suspend-normal-cast-timing',review:false};let ph=String(state.phase||'').toUpperCase();if(ph!=='MAIN 1'&&ph!=='MAIN 2')return{ok:false,reason:'suspend-normal-cast-timing',review:false};if((state.stack||[]).length)return{ok:false,reason:'suspend-normal-cast-timing',review:false};return{ok:true}}
function publicObject(card={},playerId=0,id=''){let c=root.MTGDeckEngine?.normalizeCard?root.MTGDeckEngine.normalizeCard(card):clone(card),pc=root.MTGDeckEngine?.publicCardRecord?root.MTGDeckEngine.publicCardRecord(c):clone(c);return{id:String(id||('suspend_'+Date.now().toString(36))),stableObjectId:String(id||('suspend_'+Date.now().toString(36))),name:String(c.n||c.name||'Card'),owner:Number(playerId),controllerId:Number(playerId),type:root.MTGDeckEngine?.primaryPermanentType?.(c.typeLine)||'Card',typeLine:String(c.typeLine||''),oracleText:String(c.oracleText||''),oracleId:c.oracleId||null,layout:String(c.layout||''),colors:Array.isArray(c.colors)?c.colors.slice():[],sub:Array.isArray(c.subtypes)?c.subtypes.slice():[],q:'1',c:{},token:0,phase100CardPublic:pc,faceDefinitions:clone(c.faces||[])}}
function removeHandObject(state={},ref=''){let a=state.zones?.hand||[],i=a.findIndex(o=>String(o.id||'')===String(ref)||String(o.stableObjectId||'')===String(ref));return i>=0?a.splice(i,1)[0]:null}
function suspendCard(state={},spec={},event=null){normalizeState(state);let playerId=Number(spec.playerId||event?.actorId||0),card=spec.cardPublic||{},parsed=parse(card,spec.instanceIndex||0);if(!parsed)return{ok:false,review:true,reason:'suspend-definition-unresolved'};let timing=basicCastTiming(state,playerId,card);if(!timing.ok)return{ok:false,review:!!timing.review,reason:timing.reason,details:timing.details||[]};if(spec.paymentConfirmed!==true)return{ok:false,review:false,reason:'suspend-cost-unconfirmed'};let o=removeHandObject(state,spec.objectId)||publicObject(card,playerId,spec.objectId);if(root.MTGLKI?.nextIncarnation)root.MTGLKI.nextIncarnation(o,event,'exile');o.c=o.c&&typeof o.c==='object'?o.c:{};o.c.time=String(parsed.time);o.phase102Suspend={timeRemaining:parsed.time,suspendCost:parsed.cost};state.zones??={};state.zones.exile??=[];state.zones.exile.push(o);if(root.MTGLKI?.normalizeIdentity)root.MTGLKI.normalizeIdentity(o);let id='suspend:'+String(o.incarnationId||o.id),r=normalizeRecord({id,playerId,stableObjectId:o.stableObjectId||o.id,objectId:o.id,incarnationId:o.incarnationId,zoneChangeId:o.zoneChangeId,initialTime:parsed.time,timeRemaining:parsed.time,suspendCost:parsed.cost,createdSeq:Number(event?.seq||state.meta?.seq||0)});state.suspend.records[id]=r;o.phase102Suspend={...o.phase102Suspend,recordId:id};return{ok:true,object:o,record:r,parsed}}
function syncRecordWithObject(state={},r=null,o=null){if(!r||!o)return r;let current=Math.max(0,Math.trunc(Number(o.c?.time??r.timeRemaining??0))),was=Math.max(0,Math.trunc(Number(r.timeRemaining||0)));r.timeRemaining=current;o.phase102Suspend={...(o.phase102Suspend||{}),recordId:r.id,timeRemaining:current,suspendCost:r.suspendCost};if(current>0&&!r.invalidated&&!r.cast){if((r.declined||r.lastTriggerCountered||was===0)&&r.permissionId){root.MTGCastPermissions?.revoke?.(state,r.permissionId,null,'suspend-time-counter-restored');r.permissionId=null}r.active=true;r.declined=false;r.lastTriggerCountered=false;r.lastCounterTriggered=false}return r}
function recordForObject(state={},ref=''){normalizeState(state);let found=root.MTGCastPermissions?.zoneObject?.(state,ref,'exile'),o=found?.object;if(!o)return null;if(root.MTGLKI?.normalizeIdentity)root.MTGLKI.normalizeIdentity(o);let r=Object.values(state.suspend.records).find(r=>r.incarnationId===String(o.incarnationId||''))||null;return syncRecordWithObject(state,r,o)}
function isSuspended(state={},o={}){let r=recordForObject(state,o.id);return !!(r&&r.active&&r.timeRemaining>0&&String(o.zone||'exile').toLowerCase()==='exile')}
function upkeepCandidates(state={},playerId=0){normalizeState(state);let out=[];for(const o of state.zones?.exile||[]){let r=recordForObject(state,o.id);if(!r||!r.active||r.playerId!==Number(playerId)||r.timeRemaining<=0)continue;out.push({item:{id:'stack_suspend_upkeep_'+String(r.id).replace(/[^A-Za-z0-9_-]/g,'_')+'_'+String(state.meta?.seq||0),kind:'trigger-group',name:'Suspend — remove a time counter',count:'1',controllerId:r.playerId,sourceObjectId:o.id,targets:[],effect:{type:'suspend-remove-time',recordId:r.id,objectId:o.id,incarnationId:r.incarnationId},oracleText:'At the beginning of your upkeep, if this card is suspended, remove a time counter from it.',triggerEvent:'PHASE_BEGIN',rulesProfileVersion:VERSION},baseCount:'1',modifiers:[]})}return out}
function removeTimeCounter(state={},spec={},event=null){normalizeState(state);let r=state.suspend.records[String(spec.recordId||'')]||recordForObject(state,spec.objectId);if(!r)return{ok:false,ignored:true,reason:'suspend-record-not-active'};let found=root.MTGCastPermissions?.zoneObject?.(state,spec.objectId||r.objectId,'exile'),o=found?.object;if(!o)return{ok:false,ignored:true,reason:'suspended-card-not-in-exile'};syncRecordWithObject(state,r,o);if(!r.active)return{ok:false,ignored:true,reason:'suspend-record-not-active'};if(root.MTGLKI?.normalizeIdentity)root.MTGLKI.normalizeIdentity(o);if(String(o.incarnationId||'')!==String(r.incarnationId||''))return{ok:false,ignored:true,reason:'suspend-incarnation-changed'};let current=Math.max(0,Math.trunc(Number(o.c?.time??r.timeRemaining??0)));if(current<=0)return{ok:false,ignored:true,reason:'no-time-counter'};current-=1;o.c??={};o.c.time=String(current);r.timeRemaining=current;o.phase102Suspend={...(o.phase102Suspend||{}),recordId:r.id,timeRemaining:current,suspendCost:r.suspendCost};let last=current===0;if(last&&!r.lastCounterTriggered){r.lastCounterTriggered=true;r.lastCounterSeq=Number(event?.seq||state.meta?.seq||0)}return{ok:true,object:o,record:r,remaining:current,lastRemoved:last}}
function lastCounterCandidates(state={},event={}){let r=event?.phase102SuspendResult?.record||state.suspend?.records?.[event?.payload?.recordId],res=event?.phase102SuspendResult;if(!r||!res?.lastRemoved)return[];return[{item:{id:'stack_suspend_cast_'+String(r.id).replace(/[^A-Za-z0-9_-]/g,'_')+'_'+String(event.seq||0),kind:'trigger-group',name:'Suspend — play the card',count:'1',controllerId:Number(r.playerId),sourceObjectId:String(r.objectId),targets:[],effect:{type:'suspend-cast',optional:true,recordId:String(r.id),objectId:String(r.objectId),incarnationId:String(r.incarnationId)},oracleText:'When the last time counter is removed from this card, if it is exiled, you may play it without paying its mana cost if able.',triggerEvent:'LAST_TIME_COUNTER_REMOVED',rulesProfileVersion:VERSION},baseCount:'1',modifiers:[]}]
}
function grantCastPermission(state={},spec={},event=null){normalizeState(state);let r=state.suspend.records[String(spec.recordId||'')];if(!r||r.invalidated||r.cast||r.declined||r.lastTriggerCountered)return{ok:false,review:true,reason:'suspend-record-unavailable'};let found=root.MTGCastPermissions?.zoneObject?.(state,spec.objectId||r.objectId,'exile'),o=found?.object;if(!o)return{ok:false,review:false,reason:'suspend-card-no-longer-exiled'};if(root.MTGLKI?.normalizeIdentity)root.MTGLKI.normalizeIdentity(o);if(String(o.incarnationId||'')!==String(r.incarnationId||''))return{ok:false,review:false,reason:'suspend-incarnation-changed'};if(r.timeRemaining!==0)return{ok:false,review:false,reason:'suspend-time-counters-remain'};let g=root.MTGCastPermissions?.grant?.(state,o,{kind:'suspend',playerId:r.playerId,allowedZone:'exile',allowedMode:'normal',timingOverride:true,withoutManaCost:true,xMustBeZero:true,source:'suspend-last-counter-trigger',suspendRecordId:r.id,suspendHaste:true},event);if(!g?.ok)return{ok:false,review:true,reason:g?.reason||'suspend-permission-failed'};r.permissionId=g.record.id;return{ok:true,record:r,permission:g.record,object:o,card:root.MTGCastPermissions.cardForPermission(o,g.record)}}
function internalCastAllowed(state={},playerId=0,objectRef='',permissionId=''){normalizeState(state);let r=Object.values(state.suspend.records).find(x=>x.permissionId===String(permissionId||'')&&x.playerId===Number(playerId));if(!r)return false;let v=root.MTGCastPermissions?.validateCast?.(state,playerId,objectRef,{permissionId,fromZone:'exile',mode:'normal'});return !!v?.ok}
function onCastCommitted(state={},o={},permission={},item=null,event=null){normalizeState(state);if(String(permission.kind||'')!=='suspend')return{ok:true,ignored:true};let r=Object.values(state.suspend.records).find(x=>x.permissionId===String(permission.id||'')&&x.incarnationId===String(permission.incarnationId||''));if(r){r.active=false;r.cast=true;r.castSeq=Number(event?.seq||state.meta?.seq||0)}o.phase102SuspendCast={recordId:r?.id||permission.suspendRecordId||null,grantedHaste:creatureType((item?.publicCard||o.phase100CardPublic||{}).typeLine||o.typeLine),controllerId:Number(item?.controllerId||permission.playerId||o.controllerId||o.owner)};return{ok:true,record:r||null}}
function markDeclined(state={},recordId='',event=null){normalizeState(state);let r=state.suspend.records[String(recordId||'')];if(!r)return{ok:false,ignored:true};r.active=false;r.declined=true;r.declinedSeq=Number(event?.seq||state.meta?.seq||0);if(r.permissionId)root.MTGCastPermissions?.revoke?.(state,r.permissionId,event,'suspend-declined');return{ok:true,record:r}}
function markLastTriggerCountered(state={},recordId='',event=null){normalizeState(state);let r=state.suspend.records[String(recordId||'')];if(!r)return{ok:false,ignored:true};r.active=false;r.lastTriggerCountered=true;r.counteredSeq=Number(event?.seq||state.meta?.seq||0);if(r.permissionId)root.MTGCastPermissions?.revoke?.(state,r.permissionId,event,'suspend-trigger-countered');return{ok:true,record:r}}
function onZoneChange(state={},o={},event=null){normalizeState(state);if(root.MTGLKI?.normalizeIdentity)root.MTGLKI.normalizeIdentity(o);let sid=String(o.stableObjectId||o.id||''),inc=String(o.incarnationId||''),invalidated=[];for(const r of Object.values(state.suspend.records)){if(!r.active)continue;if(r.stableObjectId===sid&&r.incarnationId!==inc){r.active=false;r.invalidated=true;r.invalidatedSeq=Number(event?.seq||state.meta?.seq||0);if(r.permissionId)root.MTGCastPermissions?.revoke?.(state,r.permissionId,event,'suspend-object-changed-zone');invalidated.push(r.id)}}return{ok:true,invalidated}}
function statusLabel(state={},o={}){let r=recordForObject(state,o.id);if(!r)return'';if(r.timeRemaining>0)return'SUSPENDED · '+r.timeRemaining+' TIME';if(r.cast)return'SUSPEND · CAST';if(r.declined)return'SUSPEND · LEFT EXILED';if(r.lastTriggerCountered)return'SUSPEND · TRIGGER COUNTERED';return'SUSPEND · 0 TIME'}
function localQA(engine){
 let c=[],q=(n,v)=>c.push([n,!!v]);
 const card={n:'Rift Bolt',manaCost:'{2}{R}',typeLine:'Sorcery',oracleText:'Rift Bolt deals 3 damage to any target.\nSuspend 1—{R}',resolved:true};
 const creature={n:'Test Beast',manaCost:'{5}{R}',typeLine:'Creature — Beast',oracleText:'Suspend 1—{R}',resolved:true};
 const multi={n:'Multi Suspend',manaCost:'{3}',typeLine:'Sorcery',oracleText:'Suspend 2—{1}\nSuspend 4—{2}',resolved:true};
 q('numeric Suspend parser extracts time count and cost',parse(card)?.time===1&&parse(card)?.cost==='{R}');
 q('multiple printed Suspend instances remain distinct',parseAll(multi).length===2&&parse(multi,1)?.time===4&&parse(multi,1)?.cost==='{2}');
 q('ambiguous Suspend X is never guessed',parse({oracleText:'Suspend X—{R}'})===null);
 if(!engine)return{ok:false,checks:[...c,['engine supplied',false]]};
 const base=()=>engine.normalizeState({life:{1:40,2:40},battle:[],stack:[],zones:{exile:[],graveyard:[],hand:[],command:[]},events:[],snapshots:[],feed:[],active:1,priority:1,turn:4,phase:'MAIN 1'});
 let locked=base();locked.battle.push({id:'lock',owner:2,controllerId:2,typeLine:'Enchantment',oracleText:"Players can't cast spells."});
 let timing=basicCastTiming(locked,1,card);q('public cant-cast prohibition prevents Suspend special action',timing.ok===false&&timing.review===false);
 let st=base(),sr=suspendCard(st,{playerId:1,objectId:'s1',cardPublic:card,paymentConfirmed:true},{seq:1,id:'suspend'}),o=st.zones.exile[0];
 q('Suspend special action exiles exact public card',sr.ok&&o?.name==='Rift Bolt');
 q('Suspend zone move creates a new exact incarnation',!!sr.record?.incarnationId&&sr.record.incarnationId===o?.incarnationId);
 q('Suspend starts with exact time counters',o?.c?.time==='1'&&sr.record?.timeRemaining===1);
 q('suspended designation requires exile plus positive time counter',isSuspended(st,o));
 q('no cast permission exists while time counters remain',!Object.values(st.castPermissions?.records||{}).some(x=>x.active));
 let cs=upkeepCandidates(st,1);q('upkeep creates owner trigger without removing counter immediately',cs.length===1&&o.c.time==='1'&&cs[0].item.effect.type==='suspend-remove-time');
 q('opponent upkeep does not remove this card time counter',upkeepCandidates(st,2).length===0);
 let ev=engine.dispatch(st,'SUSPEND_TIME_COUNTER_REMOVED',{recordId:sr.record.id,objectId:o.id},1,{source:'qa'});
 q('resolving upkeep trigger removes exactly one time counter',ev.phase102SuspendResult?.ok&&o.c.time==='0');
 let last=lastCounterCandidates(st,ev);q('last time counter creates separate optional cast trigger',last.length===1&&last[0].item.effect?.type==='suspend-cast'&&last[0].item.effect?.optional===true);
 let gp=grantCastPermission(st,{recordId:sr.record.id,objectId:o.id},{seq:3,id:'grant'});
 q('last-counter window binds exact exile incarnation',gp.ok&&gp.permission?.kind==='suspend'&&gp.permission?.incarnationId===o.incarnationId);
 let br=root.MTGCastPermissions.bridgePermission(gp.permission);q('Suspend permission supplies timing override and free cast',br.timingOverride&&br.withoutManaCost);
 q('Suspend permission forces X to zero',br.xMustBeZero===true);
 q('internal Suspend cast is exact-permission gated',internalCastAllowed(st,1,o.id,gp.permission.id)&&!internalCastAllowed(st,2,o.id,gp.permission.id));
 let item={id:'spell',controllerId:1,publicCard:card};onCastCommitted(st,o,gp.permission,item,{seq:4,id:'cast'});q('successful suspended cast consumes exact record',sr.record.cast===true&&sr.record.active===false);
 let ds=base(),dr=suspendCard(ds,{playerId:1,objectId:'d',cardPublic:card,paymentConfirmed:true},{seq:10,id:'d'}),doo=ds.zones.exile[0];removeTimeCounter(ds,{recordId:dr.record.id,objectId:doo.id},{seq:11,id:'rm'});markDeclined(ds,dr.record.id,{seq:12,id:'no'});
 q('declining Suspend cast keeps card exiled at zero counters',dr.record.declined===true&&doo.c.time==='0'&&ds.zones.exile.some(x=>x.id===doo.id));
 doo.c.time='1';let resumed=recordForObject(ds,doo.id);q('later-added time counter makes card suspended again',resumed.active&&resumed.timeRemaining===1&&!resumed.declined&&isSuspended(ds,doo));
 let again=removeTimeCounter(ds,{recordId:resumed.id,objectId:doo.id},{seq:13,id:'again'});q('re-suspended card can create another last-counter trigger',again.ok&&again.lastRemoved&&lastCounterCandidates(ds,{phase102SuspendResult:again,seq:13}).length===1);
 let cs2=base(),cr2=suspendCard(cs2,{playerId:1,objectId:'countered',cardPublic:card,paymentConfirmed:true},{seq:20,id:'c'}),co2=cs2.zones.exile[0],ce=engine.dispatch(cs2,'SUSPEND_TIME_COUNTER_REMOVED',{recordId:cr2.record.id,objectId:co2.id},1,{source:'qa'});markLastTriggerCountered(cs2,cr2.record.id,{seq:22,id:'counter'});
 q('countered last-counter trigger opens no cast permission',grantCastPermission(cs2,{recordId:cr2.record.id,objectId:co2.id},{seq:23,id:'bad'}).ok===false);
 co2.c.time='1';let rr=recordForObject(cs2,co2.id);q('later time counter restores suspension after countered trigger',rr.active&&rr.timeRemaining===1&&!rr.lastTriggerCountered);
 removeTimeCounter(cs2,{recordId:rr.id,objectId:co2.id},{seq:24,id:'again'});q('fresh last-counter event can open fresh permission',grantCastPermission(cs2,{recordId:rr.id,objectId:co2.id},{seq:25,id:'fresh'}).ok===true);
 let hs=base(),hr=suspendCard(hs,{playerId:1,objectId:'h',cardPublic:creature,paymentConfirmed:true},{seq:30,id:'h'}),ho=hs.zones.exile[0];removeTimeCounter(hs,{recordId:hr.record.id,objectId:ho.id},{seq:31,id:'h2'});let hg=grantCastPermission(hs,{recordId:hr.record.id,objectId:ho.id},{seq:32,id:'h3'}),pi={controllerId:1,publicCard:creature,phase100CardObject:clone(ho),phase100PermissionRecord:hg.permission},perm=root.MTGCastPermissions.permanentFromStack(pi);
 q('creature cast through Suspend receives tracked haste grant',!!perm?.phase102SuspendCast?.grantedHaste&&root.MTGCombatRules?.hasTrait?.(perm,'haste',{battle:[perm],continuousEffects:[]})===true);
 let control=engine.normalizeState({life:{1:40,2:40},battle:[perm],events:[],snapshots:[],feed:[]});engine.dispatch(control,'PERMANENT_CONTROLLER_CHANGED',{objectId:perm.id,controllerId:2},2,{source:'qa'});q('Suspend haste grant ends when control is lost',control.battle[0]?.phase102SuspendCast?.grantedHaste===false&&root.MTGCombatRules?.hasTrait?.(control.battle[0],'haste',control)===false);
 let kicker=root.MTGAdvancedCastingCosts?.createPending?.(hs,{playerId:1,name:'Kicker Suspender',cardPublic:{n:'Kicker Suspender',manaCost:'{X}{R}',typeLine:'Sorcery',oracleText:'Kicker {1}\nSuspend 1—{R}'},fromZone:'exile',castPermission:root.MTGCastPermissions.bridgePermission(hg.permission)},[]);q('Phase 91 forces X zero but preserves supported additional costs',kicker?.choices?.xValue===0&&kicker?.kicker?.kind==='kicker');
 let zs=base(),zr=suspendCard(zs,{playerId:1,objectId:'z',cardPublic:card,paymentConfirmed:true},{seq:40,id:'z'}),zo=zs.zones.exile[0],oldInc=zo.incarnationId;engine.dispatch(zs,'OBJECT_ZONE_CHANGED',{objectId:zo.id,toZone:'graveyard'},1,{source:'qa'});q('zone change invalidates old Suspend incarnation record',zr.record.invalidated===true&&zs.zones.graveyard[0]?.incarnationId!==oldInc);
 let rec=engine.normalizeState(JSON.parse(JSON.stringify(ds)));q('Suspend state survives reconnect normalization',rec.suspend?.version===VERSION&&rec.suspend.records[dr.record.id]?.incarnationId===dr.record.incarnationId);
 q('version identifies Phase 102',VERSION.includes('phase102'));
 return{ok:c.every(x=>x[1]),checks:c}
}
return{VERSION,normalizeRecord,normalizeState,parseAll,parse,basicCastTiming,suspendCard,syncRecordWithObject,recordForObject,isSuspended,upkeepCandidates,removeTimeCounter,lastCounterCandidates,grantCastPermission,internalCastAllowed,onCastCommitted,markDeclined,markLastTriggerCountered,onZoneChange,statusLabel,localQA};
});
