(function(){
 'use strict';
 let lastSignature='';
 function visible(el){return !!el&&!el.classList.contains('h')}
 function actionButtons(){return ['cast','resp','pass','more'].map(id=>document.getElementById(id)).filter(Boolean)}
 function action(id){return actionButtons().find(b=>b.dataset.contextAction===id&&!b.disabled)}
 function ensureMount(){let hud=document.querySelector('.playerHud'),mount=document.getElementById('lowAttentionTurnHud');if(!hud)return null;if(!mount){mount=document.createElement('section');mount.id='lowAttentionTurnHud';mount.className='lowAttentionTurnHud h';mount.setAttribute('aria-live','polite');let anchor=document.getElementById('priorityDirector');(anchor||hud.firstElementChild).insertAdjacentElement(anchor?'afterend':'beforebegin',mount)}return mount}
 function plan(){let game=document.getElementById('game');if(!game||!visible(game)||game.classList.contains('lowAttention'))return null;let priority=document.getElementById('priorityPill')?.textContent||'',hint=document.getElementById('contextHint')?.textContent||'',turn=document.getElementById('turn')?.textContent||'',phase=document.getElementById('phase')?.textContent||'',mine=/YOU HAVE PRIORITY|YOUR PRIORITY|YOUR DECISION/i.test(priority+' '+hint),active=/YOUR TURN/i.test(hint)||document.querySelector('.priorityPill.mine')&&/YOUR TURN|WAITING/i.test(priority),combat=action('combat-ready');if(combat)return{tone:'act',eyebrow:'YOUR ACTION',title:combat.textContent,detail:'The table is waiting for your combat confirmation.',primary:combat,alternates:[]};if(mine){let pass=action('pass'),respond=action('respond')||action('add-stack')||action('cast')||action('activate'),inspect=action('inspect');return{tone:'attention',eyebrow:'YOUR PRIORITY',title:/STACK/i.test(hint)?'The stack is waiting for you':'Choose whether to act',detail:'Everyone else can leave their phone down.',primary:pass||respond,alternates:[respond,inspect].filter((b,i,a)=>b&&b!==(pass||respond)&&a.indexOf(b)===i).slice(0,2)}}if(active){let next=action('next-phase'),primary=next||actionButtons().find(b=>!b.disabled);if(primary)return{tone:'active',eyebrow:(turn+' · '+phase).replace(/\s+/g,' ').trim(),title:primary.textContent,detail:'Only advance when the physical table is ready.',primary,alternates:actionButtons().filter(b=>b!==primary&&!b.disabled&&['cast','activate','more'].includes(b.dataset.contextAction)).slice(0,2)}}return null}
 function render(){let game=document.getElementById('game'),mount=ensureMount();if(!game||!mount)return;let p=plan(),signature=p?[p.tone,p.eyebrow,p.title,p.primary?.dataset.contextAction,...p.alternates.map(b=>b.dataset.contextAction)].join('|'):'';game.classList.toggle('focusedTurnAction',!!p);mount.classList.toggle('h',!p);if(!p){mount.innerHTML='';lastSignature='';return}if(signature===lastSignature)return;lastSignature=signature;mount.dataset.tone=p.tone;mount.innerHTML='<div class="lowAttentionEyebrow"></div><div class="lowAttentionTitle"></div><div class="lowAttentionDetail"></div><button class="lowAttentionPrimary"></button><div class="lowAttentionAlternatives"></div>';mount.querySelector('.lowAttentionEyebrow').textContent=p.eyebrow;mount.querySelector('.lowAttentionTitle').textContent=p.title;mount.querySelector('.lowAttentionDetail').textContent=p.detail;let primary=mount.querySelector('.lowAttentionPrimary');primary.textContent=p.primary.textContent;primary.onclick=()=>p.primary.click();let alternatives=mount.querySelector('.lowAttentionAlternatives');p.alternates.forEach(source=>{let b=document.createElement('button');b.textContent=source.textContent;b.onclick=()=>source.click();alternatives.appendChild(b)})}
 function start(){let game=document.getElementById('game');if(!game)return;let observer=new MutationObserver(()=>queueMicrotask(render));observer.observe(game,{attributes:true,attributeFilter:['class']});['priorityPill','contextHint','turn','phase','cast','resp','pass','more'].map(id=>document.getElementById(id)).filter(Boolean).forEach(el=>observer.observe(el,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class','disabled','data-context-action']}));render()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
 window.MTGLowAttentionTurnHud={render,localQA(){let ids=['pass','respond','next-phase','combat-ready'],checks=ids.map(id=>['recognizes '+id+' action',typeof id==='string'&&id.length>0]);return{ok:checks.every(x=>x[1]),checks}}};
})();
