const { chromium } = require('playwright');
const BASE=process.env.PREVIEW_URL||'https://mtg-table-engine1-git-premium-cohe-6cdabc-brylancreatesart-7523.vercel.app';
const deck=`1 Giada, Font of Hope\n99 Plains`;
const report={base:BASE,checks:[],errors:[],startedAt:new Date().toISOString()};
const check=(name,ok,details='')=>{report.checks.push({name,ok:!!ok,details});if(!ok)throw new Error(name+(details?': '+details:''))};
async function wire(p,label){p.on('pageerror',e=>report.errors.push({label,type:'pageerror',text:String(e)}));p.on('console',m=>{if(m.type()==='error')report.errors.push({label,type:'console',text:m.text()})})}
async function guestLobby(p,name){await p.goto(BASE,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForSelector('#authGuestBtn',{state:'visible',timeout:25000});await p.waitForFunction(()=>typeof Peer==='function',null,{timeout:15000});await p.click('#authGuestBtn');await p.waitForSelector('#createProfileBtn',{state:'visible'});await p.fill('#displayNameInput',name);await p.click('#createProfileBtn');await p.waitForSelector('#deck',{state:'visible'});await p.fill('#deck',deck);await p.click('#ver');await p.waitForFunction(()=>document.querySelectorAll('#commanderSelect option').length>1,null,{timeout:30000});await p.selectOption('#commanderSelect',{label:'Giada, Font of Hope'});await p.click('#cont');await p.waitForSelector('#lobby:not(.h)',{timeout:12000})}
async function ready(p){await p.click('#rdy');await p.waitForSelector('#modal:not(.h)',{timeout:10000});await p.getByRole('button',{name:'KEEP 7 · 0 MULLIGANS',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#modal')?.classList.contains('h'),null,{timeout:5000})}
async function battle(p){await p.waitForSelector('#battleIntro:not(.h), #game:not(.h)',{timeout:20000});if(await p.locator('#battleIntroSkip').isVisible().catch(()=>false))await p.click('#battleIntroSkip');await p.waitForSelector('#game:not(.h)',{timeout:10000})}
(async()=>{const browser=await chromium.launch({headless:true});let host,join;try{const hc=await browser.newContext({viewport:{width:390,height:844}}),jc=await browser.newContext({viewport:{width:390,height:844}}),deviceMock=()=>{window.__companionDevice={wakeRequests:0,vibrations:[]};Object.defineProperty(navigator,'wakeLock',{configurable:true,value:{request:async()=>{window.__companionDevice.wakeRequests++;return{release:async()=>{},addEventListener:()=>{}}}}});Object.defineProperty(navigator,'vibrate',{configurable:true,value:pattern=>{window.__companionDevice.vibrations.push(pattern);return true}})};await hc.addInitScript(deviceMock);await jc.addInitScript(deviceMock);host=await hc.newPage();join=await jc.newPage();await wire(host,'host');await wire(join,'join');await guestLobby(host,'PhoneDown Host');await host.click('#host');await host.waitForFunction(()=>/^[A-Z0-9]{6}$/.test((document.querySelector('#code')?.textContent||'').trim()),null,{timeout:20000});const room=(await host.locator('#code').textContent()).trim();await host.waitForFunction(()=>/HOST ONLINE/.test((document.querySelector('#net')?.textContent||'').toUpperCase()),null,{timeout:25000});await guestLobby(join,'PhoneDown Join');await join.click('#join');await join.fill('#jc',room);await join.click('#con');await join.waitForFunction(()=>/CONNECTED/.test((document.querySelector('#net')?.textContent||'').toUpperCase()),null,{timeout:30000});await ready(join);await ready(host);await host.waitForFunction(()=>((document.querySelector('#slots')?.textContent||'').match(/READY/g)||[]).length>=2,null,{timeout:12000}).catch(()=>{});await host.click('#start');await Promise.all([battle(host),battle(join)]);
await join.waitForFunction(()=>document.querySelector('#game')?.classList.contains('lowAttention'),null,{timeout:10000});check('opponent-turn player enters passive Sidekick mode',await join.evaluate(()=>document.querySelector('#game')?.classList.contains('lowAttention')));check('passive mode exposes monitoring control',await join.locator('#hudWakeBtn').isVisible());check('passive control identifies Sidekick monitoring',/SIDEKICK MONITORING/.test((await join.locator('#hudWakeBtn').textContent())||''));
check('battle requests screen wake lock on host',await host.evaluate(()=>window.__companionDevice.wakeRequests>0));check('battle requests screen wake lock on joining player',await join.evaluate(()=>window.__companionDevice.wakeRequests>0));
check('wake lock remains active during an opponent turn',await join.evaluate(()=>document.querySelector('#game')?.classList.contains('lowAttention')&&window.__companionDevice.wakeRequests>0));
await join.click('#hudWakeBtn');await join.waitForFunction(()=>!document.querySelector('#game')?.classList.contains('lowAttention'),null,{timeout:3000});check('tap immediately reopens full controls',await join.evaluate(()=>!document.querySelector('#game')?.classList.contains('lowAttention')));
await join.waitForFunction(()=>document.querySelector('#game')?.classList.contains('lowAttention'),null,{timeout:34000});check('manual wake automatically returns to passive mode after grace period',await join.evaluate(()=>document.querySelector('#game')?.classList.contains('lowAttention')));
check('no uncaught browser errors',report.errors.length===0,JSON.stringify(report.errors));report.ok=report.checks.every(x=>x.ok);report.room=room;}catch(e){report.ok=false;report.fatal=String(e?.stack||e);throw e}finally{report.finishedAt=new Date().toISOString();require('fs').writeFileSync('phone-down-smoke-report.json',JSON.stringify(report,null,2)+'\n');await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
